### ISSUE TITLE
panic: runtime error: index out of range when setting offset: 0 in tour/basic/9

### ISSUE THREAD

**Issue by patpatnz** [dgraph-io/dgraph#1056]
On the tour at https://tour.dgraph.io/basic/9/ , if you change the default query to offset: 0 like this:

```
{
  michael_friends_first(func: allofterms(name, "Michael")) {
    name
    age
    friend (orderasc: name, offset: 0, first: 2) {
        name
    }
  }
}
```

Get a index out of bounds panic:

```
panic: runtime error: index out of range

goroutine 2490 [running]:
github.com/dgraph-io/dgraph/worker.intersectBucket(0xc420165e50, 0xc42024baa6, 0x4, 0xc42a84f1e4, 0x5, 0xc42a84ed80, 0x1, 0x1, 0x0, 0x0)
	/Users/pjs/Projects/GO/src/github.com/dgraph-io/dgraph/worker/sort.go:360 +0x69e
github.com/dgraph-io/dgraph/worker.sortWithIndex(0x51b1b28, 0xc42add3400, 0xc420165e50, 0x0, 0x0, 0x0)
	/Users/pjs/Projects/GO/src/github.com/dgraph-io/dgraph/worker/sort.go:221 +0x6c4
github.com/dgraph-io/dgraph/worker.processSort.func2(0x51b1b28, 0xc42add3400, 0xc420165e50, 0xc42a85e5a0)
	/Users/pjs/Projects/GO/src/github.com/dgraph-io/dgraph/worker/sort.go:278 +0x43
created by github.com/dgraph-io/dgraph/worker.processSort
	/Users/pjs/Projects/GO/src/github.com/dgraph-io/dgraph/worker/sort.go:283 +0x197
```
This is repeatable.

**Comment by pawanrawal** [comment]
Fix merged to `release/v0.7.7` and `master`.
