### ISSUE TITLE
panic when 'eq' query at root in dgraph cluster

### ISSUE THREAD

**Issue by Rader** [dgraph-io/dgraph#1069]
I am running Dgraph v0.7.6, with `debugmode` turn on. Query with `id` is OK, but not with `func:eq`.

The group config
```
// If * is specified prefix matching would be done, otherwise equality matching would be done.

1: _uid_,device_click
2: click_msg
3: push_to,name,tag

// Default formula for getting group where fp is the fingerprint of a predicate.
default: fp % 3 + 1
```

The query
```
query{
	id(func:eq(tag,"msg")){
		name
	}
}
```
The error log
```
2017/06/15 15:34:03 lists.go:284: Dirty map size: 118
2017/06/15 15:34:03 lists.go:137: Commit counters. done:   118 noop:     0
[ 274] Writing batch of size: 118
2017/06/15 15:34:08 lists.go:284: Dirty map size: 0
Taking snapshot for group: 3 at watermark: 6746

Writing snapshot to WAL: {Data:[9 3 0 0 0 0 0 0 0 16 3 26 19 49 48 46 49 56 51 46 49 48 53 46 56 49 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[3] XXX_unrecognized:[]} Index:6746 Term:2 XXX_unrecognized:[]} XXX_unrecognized:[]}




panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc1fc1b]

goroutine 249314 [running]:
github.com/dgraph-io/dgraph/worker.(*grpcWorker).ServeTask(0xc42055a080, 0x7f6a6dc0d8f8, 0xc498f10a80, 0xc468ace5b0, 0xc42055a080, 0x10, 0x0)
	/home/rader/projects/go/src/github.com/dgraph-io/dgraph/worker/task.go:703 +0x8b
github.com/dgraph-io/dgraph/protos/workerp._Worker_ServeTask_Handler(0x10b3060, 0xc42055a080, 0x7f6a6dc0d8f8, 0xc498f10a80, 0xc498e58410, 0x0, 0x0, 0x0, 0xc42051b040, 0x4)
	/home/rader/projects/go/src/github.com/dgraph-io/dgraph/protos/workerp/payload.pb.go:376 +0x28d
google.golang.org/grpc.(*Server).processUnaryRPC(0xc4205b2000, 0x1746040, 0xc4933a2160, 0xc498eda300, 0xc4205681e0, 0x172ff28, 0xc498f10b10, 0x0, 0x0)
	/home/rader/projects/go/src/google.golang.org/grpc/server.go:797 +0xc41
google.golang.org/grpc.(*Server).handleStream(0xc4205b2000, 0x1746040, 0xc4933a2160, 0xc498eda300, 0xc498f10b10)
	/home/rader/projects/go/src/google.golang.org/grpc/server.go:997 +0x15a6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc43abc82d0, 0xc4205b2000, 0x1746040, 0xc4933a2160, 0xc498eda300)
	/home/rader/projects/go/src/google.golang.org/grpc/server.go:561 +0xa9
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/rader/projects/go/src/google.golang.org/grpc/server.go:562 +0xa1
```
The line 703 cause panic in my code base is this,
```
	x.Trace(ctx, "Attribute: %q NumUids: %v groupId: %v ServeTask", q.Attr, len(q.UidList.Uids), gid)
```

**Comment by MichaelJCompton** [comment]
I get same on master and 0.7.7 release.  

My groups config is
```
default: fp % 3 + 1
```

For example, I ran

```
~/go/src/github.com/dgraph-io/dgraph/cmd/dgraph/dgraph --group_conf ~/dgraph/groups.conf --groups "0,1" --idx 1 --port 8081 --workerport 12345 --my "127.0.0.1:12345" --p ~/dgraph/svr1/p --w ~/dgraph/svr1/w > ~/dgraph/svr1/dgraph.log 2>&1 &
```

```
~/go/src/github.com/dgraph-io/dgraph/cmd/dgraph/dgraph --group_conf ~/dgraph/groups.conf --groups "1,2" --idx 2 --port 8082 --workerport 12346 --my "127.0.0.1:12346" --peer "127.0.0.1:12345" --p ~/dgraph/svr2/p --w ~/dgraph/svr2/w > ~/dgraph/svr2/dgraph.log 2>&1 &
```

```
~/go/src/github.com/dgraph-io/dgraph/cmd/dgraph/dgraph --group_conf ~/dgraph/groups.conf --groups "2,3" --idx 3 --port 8083 --workerport 12347 --my "127.0.0.1:12347" --peer "127.0.0.1:12346" --p ~/dgraph/svr3/p --w ~/dgraph/svr3/w > ~/dgraph/svr3/dgraph.log 2>&1 &
```

loaded data with

```
~/go/src/github.com/dgraph-io/dgraph/cmd/dgraphloader/dgraphloader --d 127.0.0.1:8081 --s ~/dgraph/21million.schema --r ~/dgraph/1million.rdf.gz
```

(all on the one machine) Loading works fine no matter what server I send it to, and queries to the 1,2 an 2,3 groups work find, but queries to the 0,1 server always result in

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x46e84db]

goroutine 1200018 [running]:
github.com/dgraph-io/dgraph/worker.(*grpcWorker).ServeTask(0xc4202001d0, 0x532e848, 0xc47cb545d0, 0xc420128ee0, 0xc4202001d0, 0x402afbe, 0x0)
	/Users/Michael/go/src/github.com/dgraph-io/dgraph/worker/task.go:797 +0x8b
github.com/dgraph-io/dgraph/protos._Worker_ServeTask_Handler(0x48aeb60, 0xc4202001d0, 0x532e848, 0xc47cb545d0, 0xc43af82960, 0x0, 0x0, 0x0, 0xc48239dce0, 0x46a23b4)
	/Users/Michael/go/src/github.com/dgraph-io/dgraph/protos/payload.pb.go:359 +0x28d
google.golang.org/grpc.(*Server).processUnaryRPC(0xc42009a480, 0x4c79e00, 0xc49ea3c840, 0xc445531c00, 0xc42027aff0, 0x4ced048, 0xc47cb54690, 0x0, 0x0)
	/Users/Michael/go/src/google.golang.org/grpc/server.go:770 +0xc41
google.golang.org/grpc.(*Server).handleStream(0xc42009a480, 0x4c79e00, 0xc49ea3c840, 0xc445531c00, 0xc47cb54690)
	/Users/Michael/go/src/google.golang.org/grpc/server.go:969 +0x15a0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc49dfb3820, 0xc42009a480, 0x4c79e00, 0xc49ea3c840, 0xc445531c00)
	/Users/Michael/go/src/google.golang.org/grpc/server.go:537 +0xa9
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/Michael/go/src/google.golang.org/grpc/server.go:538 +0xa1

```
