### ISSUE TITLE
Out Of Range Server Panic In GCE

### ISSUE THREAD

**Issue by willcj33** [dgraph-io/dgraph#1079]
When running Dgraph on GCE with a 8 vcpu machine with 12 g of ram and 30 ssd, we see a panic from time to time after a spike in cpu. The following is the stack trace:

```
panic: runtime error: index out of range

goroutine 4901238 [running]:
golang.org/x/net/trace.(*trace).addEvent(0xc466b98000, 0xfb8ec0, 0xc4cf9859e0, 0xc43dec0000)
    /home/travis/gopath/src/golang.org/x/net/trace/trace.go:756 +0x65f
golang.org/x/net/trace.(*trace).LazyPrintf(0xc466b98000, 0x10aeebd, 0x27, 0xc43decffa0, 0x2, 0x2)
    /home/travis/gopath/src/golang.org/x/net/trace/trace.go:785 +0xa5
github.com/dgraph-io/dgraph/x.Trace(0x1739e40, 0xc461293c00, 0x10aeebd, 0x27, 0xc43decffa0, 0x2, 0x2)
    /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/x.go:117 +0xa9
github.com/dgraph-io/dgraph/query.ProcessGraph(0x1739e40, 0xc461293c00, 0xc4591ff8c0, 0xc4591ff680, 0xc4d5e665a0)
    /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1658 +0x1e4
created by github.com/dgraph-io/dgraph/query.ProcessGraph
    /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1824 +0x1051
```

**Comment by willcj33** [comment]
I attached the pprof/profile for whats going on when this happens. We cannot get our CPU back down under 99% now.

[pprof_profile.zip](https://github.com/dgraph-io/dgraph/files/1095975/pprof_profile.zip)

**Comment by willcj33** [comment]
It seems like doing an admin shutdown, brings the pegged cpu down.

**Comment by Rader** [comment]
I think it could be better if you give the version of dgraph you are using. For example,  a release version, or commit.

**Comment by willcj33** [comment]
@Rader 
```
Dgraph version   : v0.7.7
Commit SHA-1     : 20700f2
Commit timestamp : 2017-06-14 19:23:49 +1000
Branch           : HEAD
```

Also, I am attaching another profile for when the CPU started randomly spiking from a query containing some filters. The following query usually returns in a matter of MS, but this time it was over 30 seconds and timed out: 
```
{ var(id: 4bd244a5371ecdad) @cascade { me as ACCOUNT_hasEntity @filter(eq(ENTITY_resolvedType, 3)) (orderdesc: ENTITY_resolvedType, first: 1) } var(id: var(me)) @cascade { final as ENTITY_hasRelationship @filter(lt(RELATIONSHIP_lastEventDate, "2016-12-25T11:43:39Z")){ RELATIONSHIP_score er as ~ENTITY_hasRelationship @filter(NOT var(me) AND (eq(ENTITY_resolvedType, 3) OR eq(ENTITY_resolvedType, 13))){ _id ENTITY_resolvedName ENTITY_resolvedType } }	} start(id: var(me)) @normalize { ENTITY_hasRelationship @filter(var(final)) (orderdesc: RELATIONSHIP_score, first: 10){ score: RELATIONSHIP_score ~ENTITY_hasRelationship @filter(var(er)){ id: _id name: ENTITY_resolvedName type: ENTITY_resolvedType email: ENTITY_PROFILE_emails avatar: ENTITY_PROFILE_images job: ENTITY_PROFILE_jobs } } }}
```

[cpu_spiking_profile.zip](https://github.com/dgraph-io/dgraph/files/1097668/cpu_spiking_profile.zip)

**Comment by willcj33** [comment]
Seems like the heap keeps growing and the goroutines as well during normal execution --> 
<img width="268" alt="screen shot 2017-06-23 at 12 47 15 pm" src="https://user-images.githubusercontent.com/6556570/27491912-2f90bc58-5812-11e7-893e-f2c3996a1145.png">

**Comment by manishrjain** [comment]
@pawanrawal : If you look at the above stack trace, it looks like a trace printf issue like the ones you fixed before. Can you check this one as well? From release/v0.7.7.

Also, let's switch over to cockroachdb/cmux.

**Comment by manishrjain** [comment]
```ROUTINE ======================== github.com/dgraph-io/dgraph/worker.convertValue in /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/task.go
         0     19.68s (flat, cum) 59.03% of Total
         .          .     90:	t, err := schema.State().TypeOf(attr)
         .          .     91:	if err != nil {
         .          .     92:		return types.Val{}, err
         .          .     93:	}
         .          .     94:	if !t.IsScalar() {
         .     19.68s     95:		return types.Val{}, x.Errorf("Attribute %s is not valid scalar type", attr)
         .          .     96:	}
         .          .     97:
         .          .     98:	src := types.Val{types.StringID, []byte(data)}
         .          .     99:	dst, err := types.Convert(src, t)
         .          .    100:	return dst, err
```

**Comment by manishrjain** [comment]
```(pprof) list ValueForTag
Total: 33.34s
ROUTINE ======================== github.com/dgraph-io/dgraph/posting.(*List).ValueForTag in /home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/list.go
     140ms      9.53s (flat, cum) 28.58% of Total
         .          .    685:	l.RLock()
         .          .    686:	defer l.RUnlock()
         .          .    687:	return l.postingForLangs(langs)
         .          .    688:}
         .          .    689:
         .      150ms    690:func (l *List) ValueForTag(tag string) (rval types.Val, rerr error) {
      40ms       40ms    691:	l.RLock()
      10ms       10ms    692:	defer l.RUnlock()
         .          .    693:	p, err := l.postingForTag(tag)
         .          .    694:	if err != nil {
         .          .    695:		return rval, err
         .          .    696:	}
      90ms      9.33s    697:	return copyValueToVal(p), nil
         .          .    698:}
         .          .    699:
         .          .    700:func copyValueToVal(p *protos.Posting) (rval types.Val) {
         .          .    701:	val := make([]byte, len(p.Value))
         .          .    702:	copy(val, p.Value)
```

**Comment by manishrjain** [comment]
```         .          .   1643:			if result.IntersectDest {
         .      560ms   1644:				sg.DestUIDs = algo.IntersectSorted(result.UidMatrix)
         .          .   1645:			} else {
         .          .   1646:				sg.DestUIDs = algo.MergeSorted(result.UidMatrix)
         .          .   1647:			}
         .          .   1648:
         .          .   1649:			if parent == nil {
         .          .   1650:				// I'm root. We reach here if root had a function.
         .     19.69s   1651:				sg.uidMatrix = []*protos.List{sg.DestUIDs}
         .          .   1652:			}
         .          .   1653:		}
         .          .   1654:	}
         .          .   1655:
```

**Comment by manishrjain** [comment]
```ROUTINE ======================== github.com/dgraph-io/dgraph/posting.(*List).postingFor in /home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/list.go
      10ms      9.45s (flat, cum) 28.34% of Total
         .          .    679:		return rval, err
         .          .    680:	}
         .          .    681:	return copyValueToVal(p), nil
         .          .    682:}
         .          .    683:
      10ms       10ms    684:func (l *List) postingFor(langs []string) (p *protos.Posting, rerr error) {
         .          .    685:	l.RLock()
         .          .    686:	defer l.RUnlock()
         .      9.44s    687:	return l.postingForLangs(langs)
         .          .    688:}
```

**Comment by manishrjain** [comment]
[ ] Also, we should check if `x.Trace(..)` still costs CPU cycles even if the context has no trace.

**Comment by manishrjain** [comment]
```         .          .    404:		}
         .          .    405:		tokenizers := schema.State().TokenizerNames(q.Attr)
         .          .    406:		var found bool
         .          .    407:		for _, t := range tokenizers {
         .          .    408:			if t == "trigram" { // TODO(tzdybal) - maybe just rename to 'regex' tokenizer?
         .          .    409:				found = true
         .          .    410:			}
         .          .    411:		}
         .          .    412:		if !found {
         .          .    413:			return nil,
         .      9.06s    414:				x.Errorf("Attribute %v does not have trigram index for regex matching.", q.Attr)
         .          .    415:		}
         .          .    416:
         .          .    417:		query := cindex.RegexpQuery(srcFn.regex.Syntax)
         .          .    418:		empty := protos.List{}
         .          .    419:		uids, err := uidsForRegex(attr, gid, query, &empty)
         .          .    420:		if uids != nil {
         .          .    421:			out.UidMatrix = append(out.UidMatrix, uids)
         .          .    422:
```

**Comment by manishrjain** [comment]
```ROUTINE ======================== github.com/dgraph-io/dgraph/posting.(*List).getPostingList in /home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/list.go
      30ms      8.36s (flat, cum) 61.02% of Total
         .          .    197:
         .          .    198:// getPostingList tries to get posting list from l.pbuffer. If it is nil, then
         .          .    199:// we query RocksDB. There is no need for lock acquisition here.
         .          .    200:func (l *List) getPostingList(loop int) *protos.PostingList {
         .          .    201:	if loop >= 10 {
         .      8.33s    202:		x.Fatalf("This is over the 10th loop: %v", loop)
         .          .    203:	}
         .          .    204:	l.AssertRLock()
```

**Comment by manishrjain** [comment]
Looks like we should stop using `x.Errorf` and `x.Fatalf` etc., which generate new strings. Or, convert them to how trace uses lazyprintf, if we realize that trace strings is cheap if there's no trace object.

**Comment by manishrjain** [comment]
- [ ] Also, in iterateParallel, do we check whether the context is valid to continue the iteration?

**Comment by pawanrawal** [comment]
I have updated the binaries. Tracing was on by default because of go-grpc. I have turned it off now unless the user sets the `tracing` flag explicitly while running dgraph. Also all trace calls are now inline, which should make things faster. @willcj33 can you please download and check with the latest binary please?

**Comment by willcj33** [comment]
Thank you @pawanrawal , I am downloading now.

**Comment by pawanrawal** [comment]
@willcj33

Is there something more we can do regarding this issue? If not then can you please close this along with #1028?

Of-course, feel free to open another issue if you face any other problems.

**Comment by pawanrawal** [comment]
I talked to @willcj33. Closing this as it's not been happening anymore.
