### ISSUE TITLE
Index out of range panic

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1163]
```
panic: runtime error: index out of range

goroutine 2443487 [running]:
github.com/dgraph-io/dgraph/posting.(*PIterator).Posting(0xc425419018, 0xc4d0fb00a0)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/posting/list.go:174 +0xc2
github.com/dgraph-io/dgraph/posting.(*List).iterate(0xc4f22980e0, 0x0, 0xc425419078)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/posting/list.go:578 +0x2c0
github.com/dgraph-io/dgraph/posting.(*List).Postings(0xc4f22980e0, 0x0, 0x0, 0xc4254195d8)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/posting/list.go:771 +0x9a
github.com/dgraph-io/dgraph/worker.processTask(0x7f965d656bb0, 0xc470b5bda0, 0xc4d2aa0070, 0x1, 0x0, 0x0, 0x0)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/worker/task.go:330 +0x2261
github.com/dgraph-io/dgraph/worker.ProcessTaskOverNetwork(0x7f965d656bb0, 0xc470b5bda0, 0xc4d2aa0070, 0x0, 0x0, 0x0)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/worker/task.go:63 +0x8a9
github.com/dgraph-io/dgraph/query.ProcessGraph(0x12f5dc0, 0xc470b5bda0, 0xc51331d8c0, 0xc51331d680, 0xc470b5be60)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/query/query.go:1581 +0x2628
created by github.com/dgraph-io/dgraph/query.ProcessGraph
	/home/pawan/go/src/github.com/dgraph-io/dgraph/query/query.go:1811 +0x112d
```

While running the following query
```
{
	actor(func: eq(name, "Tom Hanks"))  {
		name@en
	}
}
```

**Comment by pawanrawal** [comment]
Fixed and merged to master with f5c7893f1c28c8976b504a83e6dcc4f9f4339316.
