### ISSUE TITLE
SEGFAULT on query using var as func

### ISSUE THREAD

**Issue by TBotV63** [dgraph-io/dgraph#1195]
### Version

```
Dgraph version   : v0.7.7
Commit SHA-1     : 6d934ae
Commit timestamp : 2017-06-29 16:24:30 +1000
Branch           : HEAD
```

I am on arch and I installed dgraph with the script from `get.dgraph.io`

### Schema:

```
mutation {
  schema {
    ipaddr: string @index(fulltext) .
    sid: int @index(int) .
    network: uid @reverse .
  }
}
```

When I execute the following query (from the local http gui) the server segfaults:

```
{
    user(func: eq(steamid, <steamid>), first: 1) { _uid_, N AS network }
    addr(func: eq(ipaddr, <ip>), first: 1) { _uid_ }
    netw(func: var(N)) {
        name
        _uid_
    }
}
```

It appears to have something to do with my (attempted) use of `var` while fiddling around with dgraph.

### `-debugmode` Log:

```
Starting commit routine.
2017/07/15 00:40:20 worker.go:90: Worker listening at address: [::]:12345
2017/07/15 00:40:20 main.go:1088: grpc server started.
2017/07/15 00:40:20 main.go:1089: http server started.
2017/07/15 00:40:20 main.go:1090: Server listening on port 8080
Node with GroupID: 0, ID: 1
Node with GroupID: 1, ID: 1
Found hardstate: {Data:[] Metadata:{ConfState:{Nodes:[] XXX_unrecognized:[]} Index:0 Term:0 XXX_unrecognized:[]} XXX_unrecognized:[]}
Found Snapshot: {Data:[9 1 0 0 0 0 0 0 0 16 1 26 15 108 111 99 97 108 104 111 115 116 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[1] XXX_unrecognized:[]} Index:6 Term:5 XXX_unrecognized:[]} XXX_unrecognized:[]}
Group 0 found 23 entries
Found hardstate: {Data:[9 1 0 0 0 0 0 0 0 16 1 26 15 108 111 99 97 108 104 111 115 116 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[1] XXX_unrecognized:[]} Index:6 Term:5 XXX_unrecognized:[]} XXX_unrecognized:[]}
Restarting node for group: 0
Group 1 found 0 entries
Restarting node for group: 1
raft2017/07/15 00:40:20 INFO: 1 became follower at term 5
raft2017/07/15 00:40:20 INFO: 1 became follower at term 5
raft2017/07/15 00:40:20 INFO: newRaft 1 [peers: [], term: 5, commit: 23, applied: 0, lastindex: 23, lastterm: 5]
raft2017/07/15 00:40:20 INFO: newRaft 1 [peers: [1], term: 5, commit: 6, applied: 6, lastindex: 6, lastterm: 5]
2017/07/15 00:40:20 draft.go:459: group: 0 Addr: "localhost:12345" leader: true dead: false
----------------------------
2017/07/15 00:40:20 draft.go:459: group: 1 Addr: "localhost:12345" leader: true dead: false
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:23}
----------------------------
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:23}]
----------------------------
2017/07/15 00:40:20 draft.go:459: group: 0 Addr: "localhost:12345" leader: false dead: false
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:4}
----------------------------
----------------------------
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:9}
----------------------------
2017/07/15 00:40:20 draft.go:459: group: 0 Addr: "localhost:12345" leader: true dead: false
2017/07/15 00:40:20 draft.go:459: group: 1 Addr: "localhost:12345" leader: false dead: false
2017/07/15 00:40:20 draft.go:459: group: 1 Addr: "localhost:12345" leader: true dead: false
2017/07/15 00:40:20 draft.go:459: group: 0 Addr: "localhost:12345" leader: true dead: false
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:23}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:4}]
2017/07/15 00:40:20 draft.go:459: group: 0 Addr: "localhost:12345" leader: true dead: false
2017/07/15 00:40:20 draft.go:459: group: 0 Addr: "localhost:12345" leader: true dead: false
----------------------------
----------------------------
2017/07/15 00:40:20 draft.go:459: group: 1 Addr: "localhost:12345" leader: false dead: false
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:7}
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:13}
----------------------------
----------------------------
2017/07/15 00:40:20 draft.go:459: group: 0 Addr: "localhost:12345" leader: false dead: false
----------------------------
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:20}
----------------------------
----------------------------
2017/07/15 00:40:20 draft.go:459: group: 0 Addr: "localhost:12345" leader: true dead: false
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:3}
----------------------------
----------------------------
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:6}
2017/07/15 00:40:20 draft.go:459: group: 0 Addr: "localhost:12345" leader: true dead: false
----------------------------
----------------------------
----------------------------
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:16}
2017/07/15 00:40:20 draft.go:459: group: 1 Addr: "localhost:12345" leader: false dead: false
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:21}
----------------------------
2017/07/15 00:40:20 draft.go:459: group: 1 Addr: "localhost:12345" leader: false dead: false
----------------------------
2017/07/15 00:40:20 draft.go:459: group: 0 Addr: "localhost:12345" leader: false dead: false
2017/07/15 00:40:20 draft.go:459: group: 1 Addr: "localhost:12345" leader: true dead: false
2017/07/15 00:40:20 draft.go:459: group: 1 Addr: "localhost:12345" leader: true dead: false
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:7}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:4}]
----------------------------
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:5}
----------------------------
----------------------------
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:15}
----------------------------
----------------------------
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:12}
----------------------------
----------------------------
----------------------------
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:18}
----------------------------
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:11}
----------------------------
----------------------------
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:22}
----------------------------
----------------------------
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:10}
----------------------------
----------------------------
====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:17}
----------------------------
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:7}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:5}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:7}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:20}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:3}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:20}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:20}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:6}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:9}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:20}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:16}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:20}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:21}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:20}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:21}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:15}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:21}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:12}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:21}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:18}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:13}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:18}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:11}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:18}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:11}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:22}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:10}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:11}]
Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:17}]
Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:10}]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc0028f]

goroutine 52 [running]:
github.com/dgraph-io/dgraph/algo.IntersectWith(0xc420220bc0, 0x0, 0xc420220bc0)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/algo/uidlist.go:44 +0x2f
github.com/dgraph-io/dgraph/query.ProcessGraph(0x173ef40, 0xc4202a5140, 0xc420087b00, 0x0, 0xc42048c300)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1620 +0x2c41
created by github.com/dgraph-io/dgraph/query.ProcessQuery
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1254 +0x729
```

**Comment by TBotV63** [comment]
Duh, updating fixed it.
