### ISSUE TITLE
Error Running K-ShortestPath

### ISSUE THREAD

**Issue by willcj33** [dgraph-io/dgraph#1215]
I am running an 8 core, 16g ram, 30gb ssd machine on GCE. Testing the k-shortestpath functionality, I ran into the following error looking for 2 shortest paths on version 0.8 :
```
Dgraph version   : v0.8.0
Commit SHA-1     : 0231fcc1
Commit timestamp : 2017-07-17 19:09:42 +1000
Branch           : HEAD
```
my config.yaml:
```
port: 8080

grpc_port: 9080

max_memory_mb: 13000

trace: 0.00

p: p

w: w

debugmode: false

bindall: true
```
 
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xd40dd3, 0x16)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:596 +0x95
runtime.sysMap(0xc7cc720000, 0x100000, 0x457400, 0x138f8d8)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x13768a0, 0x100000, 0x7f289c201430)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/malloc.go:428 +0x374
runtime.(*mheap).grow(0x13768a0, 0x1, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mheap.go:774 +0x62
runtime.(*mheap).allocSpanLocked(0x13768a0, 0x1, 0x7f289c201430)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mheap.go:678 +0x44f
runtime.(*mheap).alloc_m(0x13768a0, 0x1, 0x1b, 0x7f289c240000)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mheap.go:562 +0xe2
runtime.(*mheap).alloc.func1()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mheap.go:627 +0x4b
runtime.systemstack(0x7f28cdfb4d98)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:343 +0xab
runtime.(*mheap).alloc(0x13768a0, 0x1, 0x1000000001b, 0x7f289c201430)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mheap.go:628 +0xa0
runtime.(*mcentral).grow(0x13787a0, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mcentral.go:212 +0x8e
runtime.(*mcentral).cacheSpan(0x13787a0, 0x7f289c201430)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mcentral.go:93 +0x12a
runtime.(*mcache).refill(0x7f28d18b2960, 0xc70000001b, 0x7f289c201430)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mcache.go:122 +0xa0
runtime.(*mcache).nextFree.func1()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/malloc.go:526 +0x32
runtime.systemstack(0xc42001d900)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:1132

goroutine 143718 [running]:
runtime.systemstack_switch()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:281 fp=0xc44b807620 sp=0xc44b807618
runtime.(*mcache).nextFree(0x7f28d18b2960, 0x21b, 0xc44b807728, 0x412c72, 0xc7cc718980)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/malloc.go:527 +0xb9 fp=0xc44b807678 sp=0xc44b807620
runtime.mallocgc(0x280, 0xc9d200, 0x547301, 0xc4853e1ad8)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/malloc.go:679 +0x827 fp=0xc44b807718 sp=0xc44b807678
runtime.makeslice(0xc9d200, 0x14, 0x14, 0xc7cc718980, 0xc5bd452000, 0x13)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/slice.go:54 +0x7b fp=0xc44b807768 sp=0xc44b807718
github.com/dgraph-io/dgraph/query.KShortestPath(0x1300e80, 0xc459295e00, 0xc456f77440, 0x8, 0xc15a01, 0xc45e3604b0, 0xc458fcc340, 0x7f28d1836460)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/query/shortest.go:358 +0x650 fp=0xc44b807a08 sp=0xc44b807768
github.com/dgraph-io/dgraph/query.ShortestPath(0x1300e80, 0xc459295e00, 0xc456f77440, 0xffffffff4149000d, 0xc43f954300, 0x0, 0x0, 0x7c484c539b142b4a)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/query/shortest.go:432 +0x154e fp=0xc44b807f40 sp=0xc44b807a08
github.com/dgraph-io/dgraph/query.(*QueryRequest).ProcessQuery.func2(0xc47aa95fa0, 0xc458f15270, 0x1300e80, 0xc459295e00, 0xc456f77440, 0xc459295e60)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:2193 +0x4c fp=0xc44b807fb0 sp=0xc44b807f40
runtime.goexit()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc44b807fb8 sp=0xc44b807fb0
created by github.com/dgraph-io/dgraph/query.(*QueryRequest).ProcessQuery
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:2195 +0x6d5

goroutine 1 [chan receive, 11 minutes]:
main.main()
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:709 +0x348

goroutine 17 [syscall, 11 minutes, locked to thread]:
runtime.goexit()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:2197 +0x1

goroutine 8 [chan receive]:
github.com/dgraph-io/dgraph/x.init.2.func1(0xc420018b00)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/x/metrics.go:92 +0x4c
created by github.com/dgraph-io/dgraph/x.init.2
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/x/metrics.go:100 +0x4fc

goroutine 18 [syscall, 11 minutes]:
os/signal.signal_recv(0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/os/signal/signal_unix.go:28 +0x41

goroutine 19 [chan receive, 11 minutes]:
github.com/dgraph-io/dgraph/query.release()
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:234 +0x63
created by github.com/dgraph-io/dgraph/query.init.1
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:249 +0x64

goroutine 142833 [select]:
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*node).run(0xc44b79ed20, 0xc4362085a0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/node.go:314 +0x11c9
created by github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.RestartNode
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/node.go:224 +0x33e

goroutine 142727 [chan receive, 11 minutes]:
github.com/dgraph-io/dgraph/x.(*WaterMark).process(0xc44766a448)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/x/watermark.go:156 +0x1f9
created by github.com/dgraph-io/dgraph/x.(*WaterMark).Init
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/x/watermark.go:76 +0xc8

goroutine 146 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc4200ea510, 0xc42031e930)
	/home/travis/gopath/src/github.com/dgraph-io/badger/levels.go:156 +0x204
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/home/travis/gopath/src/github.com/dgraph-io/badger/levels.go:142 +0x89

goroutine 147 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc4200ea510, 0xc42031e930)
	/home/travis/gopath/src/github.com/dgraph-io/badger/levels.go:156 +0x204
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/home/travis/gopath/src/github.com/dgraph-io/badger/levels.go:142 +0x89

goroutine 148 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc4200ea510, 0xc42031e930)
	/home/travis/gopath/src/github.com/dgraph-io/badger/levels.go:156 +0x204
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/home/travis/gopath/src/github.com/dgraph-io/badger/levels.go:142 +0x89

goroutine 162 [select, 11 minutes]:
github.com/dgraph-io/badger.(*KV).doWrites(0xc420344000, 0xc4202f4000)
	/home/travis/gopath/src/github.com/dgraph-io/badger/kv.go:583 +0x587
created by github.com/dgraph-io/badger.NewKV
	/home/travis/gopath/src/github.com/dgraph-io/badger/kv.go:240 +0xa90

goroutine 149 [chan receive, 11 minutes]:
github.com/dgraph-io/badger.(*KV).flushMemtable(0xc420344000, 0xc42031e960, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dgraph-io/badger/kv.go:880 +0xe2
created by github.com/dgraph-io/badger.NewKV
	/home/travis/gopath/src/github.com/dgraph-io/badger/kv.go:172 +0x711

goroutine 163 [select, 3 minutes]:
github.com/dgraph-io/badger.(*valueLog).runGCInLoop(0xc420344108, 0xc4202f4030)
	/home/travis/gopath/src/github.com/dgraph-io/badger/value.go:745 +0x163
created by github.com/dgraph-io/badger.NewKV
	/home/travis/gopath/src/github.com/dgraph-io/badger/kv.go:243 +0xaf8

goroutine 152 [chan receive, 11 minutes]:
main.setupListener.func1(0x0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:566 +0xed
created by main.setupListener
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:573 +0x31a

goroutine 143715 [chan receive]:
github.com/dgraph-io/dgraph/query.(*QueryRequest).ProcessQuery(0xc44b509c08, 0x1300e80, 0xc459295e00, 0xc0d9e0, 0xc458f14eca)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:2211 +0x7d9
github.com/dgraph-io/dgraph/query.(*QueryRequest).ProcessWithMutation(0xc44b509c08, 0x1300e80, 0xc459295e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:2348 +0x62f
main.queryHandler(0x1300180, 0xc45cdb6b60, 0xc460b4c900)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:290 +0x97a
net/http.HandlerFunc.ServeHTTP(0xd63738, 0x1300180, 0xc45cdb6b60, 0xc460b4c900)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x1370de0, 0x1300180, 0xc45cdb6b60, 0xc460b4c900)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc44b658000, 0x1300180, 0xc45cdb6b60, 0xc460b4c900)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4202fc780, 0x1300e00, 0xc458fcc180)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:2668 +0x2ce

goroutine 142745 [select]:
github.com/dgraph-io/dgraph/worker.(*node).Run(0xc44766a240)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:717 +0xfcc
created by github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:976 +0x17f

goroutine 142747 [chan receive, 11 minutes]:
github.com/dgraph-io/dgraph/worker.(*node).batchAndSendMessages(0xc44766a240)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:441 +0x127
created by github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:980 +0x1c9

goroutine 142631 [chan receive, 11 minutes]:
github.com/dgraph-io/badger.(*KV).flushMemtable(0xc420344300, 0xc444d8b800, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dgraph-io/badger/kv.go:880 +0xe2
created by github.com/dgraph-io/badger.NewKV
	/home/travis/gopath/src/github.com/dgraph-io/badger/kv.go:172 +0x711

goroutine 142748 [select]:
github.com/dgraph-io/dgraph/worker.(*groupi).periodicSyncMemberships(0xc420182150)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/groups.go:514 +0x13f
created by github.com/dgraph-io/dgraph/worker.StartRaftNodes
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/groups.go:175 +0x44a

goroutine 151 [IO wait, 11 minutes]:
net.runtime_pollWait(0x7f28d17858b0, 0x72, 0x12fa6c0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42011aed8, 0x72, 0x12f5208, 0xc44aece9a0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42011aed8, 0xffffffffffffffff, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc42011ae70, 0x0, 0x12f8880, 0xc44aece9a0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc44b5e6000, 0xc4201ae710, 0xc44b5d2e08, 0x18)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc44b5e6000, 0xd632b0, 0xc447a88280, 0x12fff80, 0xc44b5e6000)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/tcpsock.go:228 +0x49
google.golang.org/grpc.(*Server).Serve(0xc447a88280, 0x12fff80, 0xc44b5e6000, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:444 +0x196
github.com/dgraph-io/dgraph/worker.RunServer(0x1)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/worker.go:115 +0x2e2
created by main.setupServer
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:611 +0x5c

goroutine 142834 [chan receive, 11 minutes]:
github.com/dgraph-io/dgraph/worker.(*node).processApplyCh(0xc44766a360)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:579 +0x101
created by github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:975 +0x15a

goroutine 142641 [chan receive, 11 minutes]:
github.com/dgraph-io/dgraph/x.(*WaterMark).process(0xc44766a328)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/x/watermark.go:156 +0x1f9
created by github.com/dgraph-io/dgraph/x.(*WaterMark).Init
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/x/watermark.go:76 +0xc8

goroutine 142836 [select]:
github.com/dgraph-io/dgraph/worker.(*node).snapshotPeriodically(0xc44766a360)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:839 +0x176
created by github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:979 +0x1a4

goroutine 142743 [select]:
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*node).run(0xc42033e540, 0xc4362321e0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/node.go:314 +0x11c9
created by github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.RestartNode
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/node.go:224 +0x33e

goroutine 142636 [select]:
github.com/dgraph-io/dgraph/posting.periodicCommit()
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/lists.go:174 +0x59f
created by github.com/dgraph-io/dgraph/posting.Init
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/lists.go:241 +0x1ec

goroutine 142744 [chan receive, 11 minutes]:
github.com/dgraph-io/dgraph/worker.(*node).processApplyCh(0xc44766a240)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:579 +0x101
created by github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:975 +0x15a

goroutine 143716 [IO wait]:
net.runtime_pollWait(0x7f28d1785730, 0x72, 0x15)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc45ef368b8, 0x72, 0x12fa6c0, 0x12f5208)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc45ef368b8, 0xc458fcc1d1, 0x1)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc45ef36850, 0xc458fcc1d1, 0x1, 0x1, 0x0, 0x12fa6c0, 0x12f5208)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc477b031f0, 0xc458fcc1d1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/net.go:181 +0x70
github.com/dgraph-io/dgraph/vendor/github.com/cockroachdb/cmux.(*MuxConn).Read(0xc42030f720, 0xc458fcc1d1, 0x1, 0x1, 0xc430f4a480, 0x435b08, 0xd63dd8)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/cockroachdb/cmux/cmux.go:218 +0x113
net/http.(*connReader).backgroundRead(0xc458fcc1c0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:656 +0x58
created by net/http.(*connReader).startBackgroundRead
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:652 +0xdf

goroutine 142749 [chan receive, 11 minutes]:
github.com/dgraph-io/dgraph/x.(*WaterMark).process(0xc44b820140)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/x/watermark.go:156 +0x1f9
created by github.com/dgraph-io/dgraph/x.(*WaterMark).Init
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/x/watermark.go:76 +0xc8

goroutine 153 [chan receive, 11 minutes]:
main.setupListener.func1(0x0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:566 +0xed
created by main.setupListener
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:573 +0x31a

goroutine 142835 [select]:
github.com/dgraph-io/dgraph/worker.(*node).Run(0xc44766a360)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:717 +0xfcc
created by github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:976 +0x17f

goroutine 142629 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc4200ea090, 0xc444d8b7d0)
	/home/travis/gopath/src/github.com/dgraph-io/badger/levels.go:156 +0x204
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/home/travis/gopath/src/github.com/dgraph-io/badger/levels.go:142 +0x89

goroutine 154 [IO wait, 11 minutes]:
net.runtime_pollWait(0x7f28d1785970, 0x72, 0x12fa6c0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4201746f8, 0x72, 0x12f5208, 0xc44aed6440)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4201746f8, 0xffffffffffffffff, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc420174690, 0x0, 0x12f8880, 0xc44aed6440)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc44b5dc008, 0xc4202d5840, 0xc43a927e20, 0x18)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc44b5dc008, 0xd632b0, 0xc44b65a000, 0x12fff80, 0xc44b5dc008)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/tcpsock.go:228 +0x49
google.golang.org/grpc.(*Server).Serve(0xc44b65a000, 0x12fff80, 0xc44b5dc008, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:444 +0x196
main.serveGRPC(0x12fff80, 0xc44b5dc008)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:584 +0x195
created by main.setupServer
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:647 +0x55f

goroutine 142628 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc4200ea090, 0xc444d8b7d0)
	/home/travis/gopath/src/github.com/dgraph-io/badger/levels.go:156 +0x204
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/home/travis/gopath/src/github.com/dgraph-io/badger/levels.go:142 +0x89

goroutine 142633 [select, 11 minutes]:
github.com/dgraph-io/badger.(*KV).doWrites(0xc420344300, 0xc444d8b950)
	/home/travis/gopath/src/github.com/dgraph-io/badger/kv.go:583 +0x587
created by github.com/dgraph-io/badger.NewKV
	/home/travis/gopath/src/github.com/dgraph-io/badger/kv.go:240 +0xa90

goroutine 142635 [chan receive, 11 minutes]:
github.com/dgraph-io/dgraph/schema.batchSync()
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/schema/schema.go:326 +0x134
created by github.com/dgraph-io/dgraph/schema.Init
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/schema/schema.go:274 +0x83

goroutine 142639 [IO wait]:
net.runtime_pollWait(0x7f28d1785a30, 0x72, 0x12fa6c0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420174688, 0x72, 0x12f5208, 0xc6573f3fa0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420174688, 0xffffffffffffffff, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc420174620, 0x0, 0x12f8880, 0xc6573f3fa0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc44b5dc000, 0xc44b80dd90, 0x8b53bc, 0x4598d0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc44b5dc000, 0xd62348, 0xc420171400, 0x1304720, 0xc479ad7270)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/tcpsock.go:228 +0x49
github.com/dgraph-io/dgraph/vendor/github.com/cockroachdb/cmux.(*cMux).Serve(0xc420171400, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/cockroachdb/cmux/cmux.go:124 +0x95
main.setupServer(0xc420062c00)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:661 +0x801
created by main.main
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:706 +0x2da

goroutine 142637 [select, 11 minutes, locked to thread]:
runtime.gopark(0xd63f60, 0x0, 0xd2e5d8, 0x6, 0x18, 0x2)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc44b5d6f50, 0x0, 0x18)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc44b5d6f50)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:2197 +0x1

goroutine 142638 [chan receive, 11 minutes]:
main.main.func2(0xc420062a80)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:698 +0x53
created by main.main
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:702 +0x29a

goroutine 142634 [select, 1 minutes]:
github.com/dgraph-io/badger.(*valueLog).runGCInLoop(0xc420344408, 0xc444d8b980)
	/home/travis/gopath/src/github.com/dgraph-io/badger/value.go:745 +0x163
created by github.com/dgraph-io/badger.NewKV
	/home/travis/gopath/src/github.com/dgraph-io/badger/kv.go:243 +0xaf8

goroutine 142829 [chan receive]:
github.com/dgraph-io/dgraph/x.(*WaterMark).process(0xc44b7a0b40)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/x/watermark.go:156 +0x1f9
created by github.com/dgraph-io/dgraph/x.(*WaterMark).Init
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/x/watermark.go:76 +0xc8

goroutine 157 [chan receive, 11 minutes]:
main.setupServer.func1(0x12fff80, 0xc44b5dc008, 0x12fff80, 0xc44b5dc000)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:652 +0x42
created by main.setupServer
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:656 +0x609

goroutine 156 [chan receive, 11 minutes]:
github.com/dgraph-io/dgraph/vendor/github.com/cockroachdb/cmux.(*muxListener).Accept(0xc44b5da180, 0xc44aff8b70, 0xc47520, 0x12e4c70, 0xcb3a80)
	<autogenerated>:9 +0x7a
net/http.(*Server).Serve(0xc43f970a50, 0x1300340, 0xc44b5da180, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:2643 +0x228
main.serveHTTP(0x1300340, 0xc44b5da180)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:597 +0xb6
created by main.setupServer
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:649 +0x5bd

goroutine 155 [chan receive]:
github.com/dgraph-io/dgraph/vendor/github.com/cockroachdb/cmux.(*muxListener).Accept(0xc44b5da160, 0xd63998, 0xc42017fcc0, 0x1300ec0, 0xc44affc150)
	<autogenerated>:9 +0x7a
net/http.(*Server).Serve(0xc44b658000, 0x1300340, 0xc44b5da160, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:2643 +0x228
main.serveHTTP(0x1300340, 0xc44b5da160)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:597 +0xb6
created by main.setupServer
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:648 +0x58b

goroutine 142837 [chan receive, 11 minutes]:
github.com/dgraph-io/dgraph/worker.(*node).batchAndSendMessages(0xc44766a360)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:441 +0x127
created by github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:980 +0x1c9

goroutine 142630 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc4200ea090, 0xc444d8b7d0)
	/home/travis/gopath/src/github.com/dgraph-io/badger/levels.go:156 +0x204
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/home/travis/gopath/src/github.com/dgraph-io/badger/levels.go:142 +0x89
```

**Comment by manishrjain** [comment]
8 core machine with only 16GB of RAM seems too low. With 8 cores, you'd want at least 32GB.

**Comment by ashwin95r** [comment]
I have used sync.Pool to reuse the allocations for path array. This should reduce the usage. Recently we've seen some harmless looking queries like:
```
{
  bladerunner(func:ge(initial_release_date, "1900")) {
   expand(_all_) {
    expand(_all_)
  }
  }
}
```
 which access a lot of PL's triggering OOM. 

@willcj33 can you try with this commit 1f386203aa46898deb9eaa274ddbefe97db0f92e. Or share the data and query that caused it so that I can check if it happens?

**Comment by pawanrawal** [comment]
Closing this for now. Feel free to reopen if you see this issue again.
