### ISSUE TITLE
Not cleaning up .sst files upon panic. Will not start up.

### ISSUE THREAD

**Issue by elbow-jason** [dgraph-io/dgraph#1294]
### What happened:

I shut down dgraph improperly and it wouldn't restart.

### What I expected:

I expected to shutdown dgraph improperly and then restart it.

### What I did:

I interrupted a running dgraph server with two rapid SIGINTs (`Ctrl + c`) causing a panic (I think).

The first SIGINT:
```
^C2017/08/02 02:02:17 main.go:732: Caught Ctrl-C. Terminating now (this may take a few seconds)...
```
The second SIGINT:

```
^Cpanic: send on closed channel
```

Upon attempting to restart dgraph is error occurred:

```
2017/08/02 02:02:22 read /var/lib/dgraph/p/000005.sst: invalid argument
```

A temporary fix:

Removing the `.sst` file (`rm /var/lib/dgraph/p/000005.sst`) seems to have resolved the issue; dgraph was able to startup properly afterward.

The full log:
```
2017/08/02 02:01:52 draft.go:422: 		SENDING: MsgVoteResp 3-->1
2017/08/02 02:01:52 draft.go:1043: RECEIVED: MsgVote 1-->3
2017/08/02 02:01:52 raft.go:612: INFO: 3 [term: 1180] received a MsgVote message with higher term from 1 [term: 1181]
2017/08/02 02:01:52 raft.go:493: INFO: 3 became follower at term 1181
2017/08/02 02:01:52 raft.go:864: INFO: 3 [logterm: 0, index: 0, vote: 0] voted for 1 [logterm: 3, index: 75] at term 1181
2017/08/02 02:01:52 draft.go:422: 		SENDING: MsgVoteResp 3-->1
^C2017/08/02 02:02:17 main.go:732: Caught Ctrl-C. Terminating now (this may take a few seconds)...
2017/08/02 02:02:17 main.go:492: Got clean exit request
2017/08/02 02:02:17 Stopped taking more http(s) requests. Err: mux: listener closed
2017/08/02 02:02:17 All http(s) requests finished.
2017/08/02 02:02:17 Stopped taking more http(s) requests. Err: mux: listener closed
2017/08/02 02:02:17 All http(s) requests finished.
2017/08/02 02:02:17 gRpc server stopped : accept tcp [::]:9080: use of closed network connection
2017/08/02 02:02:17 wal.go:84: Writing snapshot to WAL: {Data:[9 3 0 0 0 0 0 0 0 16 4 26 15 108 111 99 97 108 104 111 115 116 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[3] XXX_unrecognized:[]} Index:3 Term:3 XXX_unrecognized:[]} XXX_unrecognized:[]}
2017/08/02 02:02:17 wal.go:84: Writing snapshot to WAL: {Data:[9 3 0 0 0 0 0 0 0 16 5 26 15 108 111 99 97 108 104 111 115 116 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[3] XXX_unrecognized:[]} Index:4 Term:4 XXX_unrecognized:[]} XXX_unrecognized:[]}
2017/08/02 02:02:17 wal.go:84: Writing snapshot to WAL: {Data:[9 3 0 0 0 0 0 0 0 16 3 26 15 108 111 99 97 108 104 111 115 116 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[3] XXX_unrecognized:[]} Index:3 Term:3 XXX_unrecognized:[]} XXX_unrecognized:[]}
2017/08/02 02:02:17 wal.go:84: Writing snapshot to WAL: {Data:[9 3 0 0 0 0 0 0 0 16 6 26 15 108 111 99 97 108 104 111 115 116 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[3] XXX_unrecognized:[]} Index:4 Term:4 XXX_unrecognized:[]} XXX_unrecognized:[]}
2017/08/02 02:02:17 wal.go:84: Writing snapshot to WAL: {Data:[9 3 0 0 0 0 0 0 0 16 7 26 15 108 111 99 97 108 104 111 115 116 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[3] XXX_unrecognized:[]} Index:4 Term:4 XXX_unrecognized:[]} XXX_unrecognized:[]}
^Cpanic: send on closed channel

goroutine 15 [running]:
os/signal.process(0x130faa0, 0xc42a94c760)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/os/signal/signal.go:176 +0x195
os/signal.loop()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/os/signal/signal_unix.go:22 +0x5c
created by os/signal.init.1
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/os/signal/signal_unix.go:28 +0x41
root@turfbytes-dgraph-cluster-03:~# ^C
root@turfbytes-dgraph-cluster-03:~# dgraph --config=/var/lib/dgraph/config.yaml
2017/08/02 02:02:22 main.go:167: Loading configuration from file: /var/lib/dgraph/config.yaml
2017/08/02 02:02:22 init.go:75: Picked flag from config: ["bindall" = true]
2017/08/02 02:02:22 init.go:75: Picked flag from config: ["memory_mb" = 1025]
2017/08/02 02:02:22 init.go:75: Picked flag from config: ["port" = 8080]
2017/08/02 02:02:22 init.go:75: Picked flag from config: ["trace" = 0.33]
2017/08/02 02:02:22 init.go:75: Picked flag from config: ["debugmode" = false]
2017/08/02 02:02:22 init.go:75: Picked flag from config: ["export" = /var/lib/dgraph/exports]
2017/08/02 02:02:22 init.go:75: Picked flag from config: ["gentlecommit" = 0.1]
2017/08/02 02:02:22 init.go:75: Picked flag from config: ["groups" = 0,3,4,5,6,7]
2017/08/02 02:02:22 init.go:75: Picked flag from config: ["grpc_port" = 9080]
2017/08/02 02:02:22 init.go:75: Picked flag from config: ["idx" = 3]
2017/08/02 02:02:22 init.go:75: Picked flag from config: ["p" = /var/lib/dgraph/p]
2017/08/02 02:02:22 init.go:75: Picked flag from config: ["w" = /var/lib/dgraph/w]
2017/08/02 02:02:22 init.go:75: Picked flag from config: ["workerport" = 12345]

Dgraph version   : v0.8.0-dev
Commit SHA-1     : c95b2640
Commit timestamp : 2017-08-01 17:22:27 +1000
Branch           : HEAD

2017/08/02 02:02:22 read /var/lib/dgraph/p/000005.sst: invalid argument

github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.Wrap
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/error.go:71
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.Check
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/error.go:43
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.(*Table).readNoFail
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/table.go:224
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.(*Table).readIndex
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/table.go:230
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.OpenTable
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/table.go:158
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.newLevelsController
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:103
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.NewKV
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/kv.go:214
github.com/dgraph-io/dgraph/dgraph.(*ServerState).initStorage
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/server.go:90
github.com/dgraph-io/dgraph/dgraph.NewServerState
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/server.go:54
main.main
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:700
runtime.main
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:185
runtime.goexit
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:2197
```

**Comment by srh** [comment]
This will be fixed by https://github.com/dgraph-io/badger/pull/140 which will mark tables removed in a MANIFEST file before truncating and deleting them.
