### ISSUE TITLE
Dgraph terminates while inserting data using dgraphloader without explicit error messages

### ISSUE THREAD

**Issue by kiyomaro927** [dgraph-io/dgraph#1353]
Hi, I'm now facing the problem that the Dgraph terminates while inserting data using dgraphloader.

My development environment is as follows:
* macOS Sierra 10.12.6
    * Memory: 16GB
    * SSD: 256GB
    * CPU: 2cores
* Dgraph v0.8.1 (launched from Docker)

The size of the gzipped data to be inserted is about 4GB (800M RDFs).

I launched the Dgraph with following comamnd:
```
$ docker run -it -p 127.0.0.1:8080:8080 -p 127.0.0.1:9080:9080 -v ~/path_to_mount_point:/dgraph --name dgraph dgraph/dgraph dgraph --bindall=true --memory_mb 8192
```
and inserted data with dgraphloader:
```
docker exec -it dgraph dgraphloader -r "data1.rdf.gz,data2.rdf.gz,...,data7.rdf.gz" -x
```

After the dgraphloader inserted several data, the Dgraph terminated without explicit error messages.

Do you have any idea to investigate why the Dgraph stops?
Thanks.

**Comment by pawanrawal** [comment]
Hey @kiyomaro927 

Can you share the server logs?

**Comment by kiyomaro927** [comment]
Hi, this is the tails of the server logs.
```
2017/08/22 07:30:31 schema.go:113: Setting schema type for attr xxxxx: default, tokenizer: [], directive: NONE, count: false
2017/08/22 07:30:31 schema.go:113: Setting schema type for attr xxxxx: default, tokenizer: [], directive: NONE, count: false
2017/08/22 07:30:32 schema.go:113: Setting schema type for attr xxxxx: default, tokenizer: [], directive: NONE, count: false
2017/08/22 07:30:33 schema.go:113: Setting schema type for attr xxxxx: default, tokenizer: [], directive: NONE, count: false
2017/08/22 07:30:39 schema.go:113: Setting schema type for attr xxxxx: default, tokenizer: [], directive: NONE, count: false
```

`docker inspect $container_id | grep OOM | grep OOMKilled` says `"OOMKilled": false,`.

**Comment by pawanrawal** [comment]
That looks pretty normal. How do you know Dgraph terminated? Did your dgraphloader stop processing RDF's? How many RDF's was it able to process?

**Comment by kiyomaro927** [comment]
When I was observing the progress of inserting data, and the process terminated.
The exit code was 137.

The dgraphloader also stopped processing RDF's at the same time.
The number of processed RDF's was about 885,000.

I tried to run the same process again just now, I got following WARN messages.
```
2017/08/22 08:15:09 node.go:402: WARN: A tick missed to fire. Node blocks too long!
2017/08/22 08:15:09 node.go:402: WARN: A tick missed to fire. Node blocks too long!
2017/08/22 08:15:09 node.go:402: WARN: A tick missed to fire. Node blocks too long!
2017/08/22 08:15:09 node.go:402: WARN: A tick missed to fire. Node blocks too long!
2017/08/22 08:15:09 node.go:402: WARN: A tick missed to fire. Node blocks too long!
2017/08/22 08:15:09 node.go:402: WARN: A tick missed to fire. Node blocks too long!
```

**Comment by kiyomaro927** [comment]
I have confirmed that the dgraphloader works well when I use the first 10,000 rows of each RDF file.

**Comment by manishrjain** [comment]
Based on the grep above, it looks like Dgraph was killed by OOM signal. Looks like you're allocating 8GB. How much memory do you have on host?

**Comment by kiyomaro927** [comment]
I have 16GB memory on host.
Now, I'm running Dgraph with `--memory_mb 2048`. So far dgraphloader seems to work well.

**Comment by kiyomaro927** [comment]
Hi, I installed Dgraph on the host and ran the same command. I haven't encountered the same issue so far.

**Comment by pawanrawal** [comment]
You could use a higher `memory_mb`. Since your machine has 16GB, you could try with `8192` as before.

**Comment by kiyomaro927** [comment]
Hi, I'm now running Dgraph on an AWS instance (Ubuntu16.04, 32GB Memory, 1.5TB SSD, 8core CPU).
While inserting RDFs using dgraphloader, Dgraph server sometimes crashed by receiving `Killed`. (dgraphloader was alive while the server was dead.)
After restarting the server, the inserting process also restarted.
But, now I have a problem that is similar to this one (https://github.com/dgraph-io/dgraph/issues/1152). This is the stack trace. Can I restart the server?
```
ubuntu@ip-172-31-8-247:~/path_to_dgraph$ dgraph --memory_mb 16484

Dgraph version   : v0.8.1
Commit SHA-1     : ea30ed9a
Commit timestamp : 2017-08-22 14:31:44 +1000
Branch           : HEAD

2017/08/24 09:16:51 draft.go:219: Node with GroupID: 0, ID: 1
2017/08/24 09:16:51 worker.go:112: Worker listening at address: 127.0.0.1:12345
2017/08/24 09:16:51 draft.go:219: Node with GroupID: 1, ID: 1
2017/08/24 09:16:51 gRPC server started.  Listening on port 9080
2017/08/24 09:16:51 HTTP server started.  Listening on port 8080
2017/08/24 09:16:51 draft.go:934: Found hardstate: {Data:[] Metadata:{ConfState:{Nodes:[]
 XXX_unrecognized:[]} Index:0 Term:0 XXX_unrecognized:[]} XXX_unrecognized:[]}
2017/08/24 09:16:51 draft.go:917: Found Snapshot: {Data:[9 1 0 0 0 0 0 0 0 16 1 26 15 108
 111 99 97 108 104 111 115 116 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[1] XXX_unre
cognized:[]} Index:357059 Term:9 XXX_unrecognized:[]} XXX_unrecognized:[]}
2017/08/24 09:16:51 draft.go:934: Found hardstate: {Data:[9 1 0 0 0 0 0 0 0 16 1 26 15 10
8 111 99 97 108 104 111 115 116 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[1] XXX_unr
ecognized:[]} Index:357059 Term:9 XXX_unrecognized:[]} XXX_unrecognized:[]}
2017/08/24 09:16:51 draft.go:946: Group 0 found 15 entries
2017/08/24 09:16:51 draft.go:960: Restarting node for group: 0
2017/08/24 09:16:51 logger.go:121: 1 state.commit 21 is out of range [0, 15]
panic: 1 state.commit 21 is out of range [0, 15]

goroutine 2907298 [running]:
log.(*Logger).Panicf(0xc420102140, 0xded04d, 0x2b, 0xc535ab9f00, 0x4, 0x4)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/log/log.go:215 +0xdb
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*DefaultLogger).Panicf(0x
c674f69dc0, 0xded04d, 0x2b, 0xc535ab9f00, 0x4, 0x4)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd
/raft/logger.go:121 +0x60
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*raft).loadState(0xc692ec
a000, 0x7, 0x1, 0x15, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd
/raft/raft.go:1012 +0x1c7
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.newRaft(0xc42005a540, 0x3)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd
/raft/raft.go:252 +0xcbd
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.RestartNode(0xc42005a540,
0x0, 0xc600000000)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd
/raft/node.go:220 +0x43
github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode(0xc420336360, 0xc674f69d70)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:965 +0x148
github.com/dgraph-io/dgraph/worker.StartRaftNodes.func2(0xc674f69d80, 0xc420336360)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/groups.go:170 +0x61
created by github.com/dgraph-io/dgraph/worker.StartRaftNodes
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/groups.go:171 +0x3f6
```

**Comment by janardhan1993** [comment]
@kiyomaro927 Hey can you please build a binary from latest master and try. There was a typo in log line. It would help us in debugging it.

**Comment by kiyomaro927** [comment]
I received this message.
```

Dgraph version   : v0.8.1-dev
Commit SHA-1     : 46fbd245
Commit timestamp : 2017-08-25 09:22:47 +1000
Branch           : HEAD

2017/08/28 01:12:01 draft.go:219: Node with GroupID: 0, ID: 1
2017/08/28 01:12:01 worker.go:112: Worker listening at address: [::]:12345
2017/08/28 01:12:01 gRPC server started.  Listening on port 9080
2017/08/28 01:12:01 HTTP server started.  Listening on port 8080
2017/08/28 01:12:01 draft.go:219: Node with GroupID: 1, ID: 1
2017/08/28 01:12:01 draft.go:934: Found hardstate: {Term:3 Vote:1 Commit:10 XXX_unrecognized:[]}
2017/08/28 01:12:01 draft.go:917: Found Snapshot: {Data:[9 1 0 0 0 0 0 0 0 16 1 26 15 108 111 99 97 108 104 111 115 116 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[1] XXX_unr$
cognized:[]} Index:310667 Term:4 XXX_unrecognized:[]} XXX_unrecognized:[]}
2017/08/28 01:12:01 draft.go:934: Found hardstate: {Term:4 Vote:1 Commit:313731 XXX_unrecognized:[]}
2017/08/28 01:12:01 draft.go:946: Group 0 found 10 entries
2017/08/28 01:12:01 draft.go:960: Restarting node for group: 0
2017/08/28 01:12:01 raft.go:493: INFO: 1 became follower at term 3
2017/08/28 01:12:01 raft.go:265: INFO: newRaft 1 [peers: [], term: 3, commit: 10, applied: 0, lastindex: 10, lastterm: 3]
2017/08/28 01:12:01 draft.go:544: group: 1 Addr: "localhost:12345" leader: true dead: false
2017/08/28 01:12:01 draft.go:544: group: 1 Addr: "localhost:12345" leader: false dead: false
2017/08/28 01:12:01 draft.go:544: group: 1 Addr: "localhost:12345" leader: true dead: false
2017/08/28 01:12:01 groups.go:546: ----------------------------
2017/08/28 01:12:01 draft.go:544: group: 1 Addr: "localhost:12345" leader: true dead: false
2017/08/28 01:12:01 groups.go:546: ----------------------------
2017/08/28 01:12:01 groups.go:547: ====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:6 PoolOrNil:<nil>}
2017/08/28 01:12:01 groups.go:548: ----------------------------
2017/08/28 01:12:01 groups.go:563: Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:6 PoolOrNil:<nil>}]
2017/08/28 01:12:01 groups.go:546: ----------------------------
2017/08/28 01:12:01 groups.go:547: ====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:3 PoolOrNil:<nil>}
2017/08/28 01:12:01 groups.go:548: ----------------------------
2017/08/28 01:12:01 groups.go:563: Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:6 PoolOrNil:<nil>}]
2017/08/28 01:12:01 groups.go:546: ----------------------------
2017/08/28 01:12:01 groups.go:547: ====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:3 PoolOrNil:<nil>}
2017/08/28 01:12:01 groups.go:548: ----------------------------
2017/08/28 01:12:01 groups.go:563: Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:3 PoolOrNil:<nil>}]
2017/08/28 01:12:01 draft.go:544: group: 0 Addr: "localhost:12345" leader: true dead: false
2017/08/28 01:12:01 draft.go:544: group: 1 Addr: "localhost:12345" leader: false dead: false
2017/08/28 01:12:01 groups.go:546: ----------------------------
2017/08/28 01:12:01 groups.go:547: ====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:9 PoolOrNil:<nil>}
2017/08/28 01:12:01 groups.go:548: ----------------------------
2017/08/28 01:12:01 groups.go:563: Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:9 PoolOrNil:<nil>}]
2017/08/28 01:12:01 groups.go:547: ====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:10 PoolOrNil:<nil>}
2017/08/28 01:12:01 groups.go:548: ----------------------------
2017/08/28 01:12:01 groups.go:563: Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:10 PoolOrNil:<nil>}]
2017/08/28 01:12:01 draft.go:544: group: 1 Addr: "localhost:12345" leader: true dead: false
2017/08/28 01:12:01 groups.go:546: ----------------------------
2017/08/28 01:12:01 groups.go:547: ====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:5 PoolOrNil:<nil>}
2017/08/28 01:12:01 groups.go:548: ----------------------------
2017/08/28 01:12:01 groups.go:563: Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:5 PoolOrNil:<nil>}]
2017/08/28 01:12:01 groups.go:546: ----------------------------
2017/08/28 01:12:01 groups.go:547: ====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:4 PoolOrNil:<nil>}
2017/08/28 01:12:01 groups.go:548: ----------------------------
2017/08/28 01:12:01 groups.go:563: Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:5 PoolOrNil:<nil>}]
2017/08/28 01:12:01 groups.go:563: Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:4 PoolOrNil:<nil>}]
2017/08/28 01:12:01 groups.go:546: ----------------------------
2017/08/28 01:12:01 groups.go:547: ====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:7 PoolOrNil:<nil>}
2017/08/28 01:12:01 groups.go:548: ----------------------------
2017/08/28 01:12:01 groups.go:563: Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:7 PoolOrNil:<nil>}]
2017/08/28 01:12:01 groups.go:563: Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:4 PoolOrNil:<nil>}]
2017/08/28 01:12:01 draft.go:946: Group 1 found 3063 entries
2017/08/28 01:12:01 draft.go:960: Restarting node for group: 1
2017/08/28 01:12:01 logger.go:121: 1 state.commit 313731 is out of range [310667, 313730]
panic: 1 state.commit 313731 is out of range [310667, 313730]

goroutine 2593333 [running]:
log.(*Logger).Panicf(0xc42005ce10, 0xdf0284, 0x2b, 0xc693bcdac0, 0x4, 0x4)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/log/log.go:215 +0xdb
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*DefaultLogger).Panicf(0xc69444e940, 0xdf0284, 0x2b, 0xc693bcdac0, 0x4, 0x4)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/logger.go:121 +0x60
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*raft).loadState(0xc6a5600000, 0x4, 0x1, 0x4c983, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/raft.go:1012 +0x1c7
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.newRaft(0xc42005a460, 0x3)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/raft.go:252 +0xcbd
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.RestartNode(0xc42005a460, 0x1, 0xc600000001)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/node.go:220 +0x43
github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode(0xc66c296a20, 0xc6941c9da0)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:965 +0x148
github.com/dgraph-io/dgraph/worker.StartRaftNodes.func2(0xc6941c9db0, 0xc66c296a20)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/groups.go:170 +0x61
created by github.com/dgraph-io/dgraph/worker.StartRaftNodes
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/groups.go:171 +0x3f6
```

**Comment by janardhan1993** [comment]
@kiyomaro927 Hey you need to clear the p and w directory and start again.
There was an missing entry, i pushed an fix to master and it shouldn't happen again.

**Comment by kiyomaro927** [comment]
Hi, the out of range problem seems to be solved.
But, now received the error about log entry.

```
2017/08/29 01:20:38 draft.go:219: Node with GroupID: 0, ID: 1
2017/08/29 01:20:38 worker.go:112: Worker listening at address: [::]:12345
2017/08/29 01:20:38 draft.go:219: Node with GroupID: 1, ID: 1
2017/08/29 01:20:38 gRPC server started.  Listening on port 9080
2017/08/29 01:20:38 HTTP server started.  Listening on port 8080
2017/08/29 01:20:38 draft.go:934: Found hardstate: {Term:4 Vote:1 Commit:10 XXX_unrecognized:[]}
2017/08/29 01:20:38 draft.go:917: Found Snapshot: {Data:[9 1 0 0 0 0 0 0 0 16 1 26 15 108 111 99 97 108 104 111 115 116 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[1] XXX_unr$cognized:[]} Index:301444 Term:6 XXX_unrecognized:[]} XXX_unrecognized:[]}
2017/08/29 01:20:38 draft.go:934: Found hardstate: {Term:6 Vote:1 Commit:304156 XXX_unrecognized:[]}
2017/08/29 01:20:38 draft.go:946: Group 0 found 5 entries
raft2017/08/29 01:20:38 missing log entry [last: 0, append at: 6]
panqic: missing log entry [last: 0, append at: 6]
goroutine 2158960 [running]:
log.(*Logger).Panicf(0xc4201a6280, 0xd7186c, 0x2b, 0xc424f26f40, 0x2, 0x2)
        /usr/local/go/src/log/log.go:223 +0xdb
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*DefaultLogger).Panicf(0x143eb60, 0xd7186c, 0x2b, 0xc424f26f40, 0x2, 0x2)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/logger.go:121 +0x60
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*MemoryStorage).Append(0xc51d7cc620, 0xc420084480, 0x5, 0x8, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/storage.go:265 +0x641
github.com/dgraph-io/dgraph/worker.(*node).initFromWal(0xc529aee120, 0xc5f54a5770, 0x4420d4, 0xc4201a4c8c, 0x2a6e200)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/draft.go:950 +0x50a
github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode(0xc529aee120, 0xc5f54a5770)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/draft.go:956 +0x4f
github.com/dgraph-io/dgraph/worker.StartRaftNodes.func2(0xc5f54b1160, 0xc529aee120)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/groups.go:170 +0x61
created by github.com/dgraph-io/dgraph/worker.StartRaftNodes
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/groups.go:168 +0x3a8
ubuntu@ip-172-31-8-247:~/kanashimi$ ~/go/bin/dgraph --memory_mb 16384 --bindall=true
2017/08/29 03:09:04 draft.go:219: Node with GroupID: 0, ID: 1
2017/08/29 03:09:04 worker.go:112: Worker listening at address: [::]:12345
2017/08/29 03:09:04 gRPC server started.  Listening on port 9080
2017/08/29 03:09:04 HTTP server started.  Listening on port 8080
2017/08/29 03:09:04 draft.go:219: Node with GroupID: 1, ID: 1
2017/08/29 03:09:04 draft.go:934: Found hardstate: {Term:4 Vote:1 Commit:10 XXX_unrecognized:[]}
2017/08/29 03:09:04 draft.go:917: Found Snapshot: {Data:[9 1 0 0 0 0 0 0 0 16 1 26 15 108 111 99 97 108 104 111 115 116 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[1] XXX_unrecognized:[]} Index:301444 Term:6 XXX_unrecognized:[]} XXX_unrecognized:[]}
2017/08/29 03:09:04 draft.go:934: Found hardstate: {Term:6 Vote:1 Commit:304156 XXX_unrecognized:[]}
2017/08/29 03:09:04 draft.go:946: Group 0 found 5 entries
raft2017/08/29 03:09:04 missing log entry [last: 0, append at: 6]
panic: missing log entry [last: 0, append at: 6]

goroutine 2560866 [running]:
log.(*Logger).Panicf(0xc4201a02d0, 0xd7186c, 0x2b, 0xc4200d73c0, 0x2, 0x2)
        /usr/local/go/src/log/log.go:223 +0xdb
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*DefaultLogger).Panicf(0x143eb60, 0xd7186c, 0x2b, 0xc4200d73c0, 0x2, 0x2)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/logger.go:121 +0x60
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*MemoryStorage).Append(0xc5cd2080e0, 0xc420084480, 0x5, 0x8, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/storage.go:265 +0x641
github.com/dgraph-io/dgraph/worker.(*node).initFromWal(0xc5cd20a120, 0xc5dc9d39f0, 0x4420d4, 0xc424dfc70c, 0x3e83200)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/draft.go:950 +0x50a
github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode(0xc5cd20a120, 0xc5dc9d39f0)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/draft.go:956 +0x4f
github.com/dgraph-io/dgraph/worker.StartRaftNodes.func2(0xc5dc9db940, 0xc5cd20a120)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/groups.go:170 +0x61
created by github.com/dgraph-io/dgraph/worker.StartRaftNodes
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/groups.go:168 +0x3a8
```

**Comment by manishrjain** [comment]
You seem to be reusing at least some of the older directories. I think might be better to install Dgraph directly on the host machine, instead of running via docker.

**Comment by janardhan1993** [comment]
@kiyomaro927 
It's slow if we use a shared directory between host and container. The recommended way is to use docker data volumes. I have updated the docs for the same.
https://docs.dgraph.io/master/get-started/#on-non-linux-distributions.

https://docs.docker.com/docker-for-mac/osxfs-caching/

You shouldn't face this issue if you are using named volumes or docker data volumes.

**Comment by janardhan1993** [comment]
@kiyomaro927 Closing the issue for now. Please reopen the issue if you are still facing the issue.
