### ISSUE TITLE
Error when Running Export in cluster mode

### ISSUE THREAD

**Issue by willcj33** [dgraph-io/dgraph#1371]
Server Details: 
```
Dgraph version   : v0.8.1
Commit SHA-1     : 39a0f3fe
Commit timestamp : 2017-08-21 09:48:09 +1000
Branch           : HEAD

3 machines on GCE
Data dispersed between the 3 machines

39G ram per machine
6 cores per machine

```

error message: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb67e58]

goroutine 78836 [running]:
github.com/dgraph-io/dgraph/worker.(*node).Raft(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:199 +0x38
github.com/dgraph-io/dgraph/worker.(*node).AmLeader(0x0, 0x100000003)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:989 +0x43
github.com/dgraph-io/dgraph/worker.handleExportForGroup(0x7fc1e01da1f0, 0xc420014450, 0x59ebd26792216bf8, 0x3, 0x0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/export.go:332 +0x67
github.com/dgraph-io/dgraph/worker.ExportOverNetwork.func1(0xc4578ad980, 0x7fc1e01da1f0, 0xc420014450, 0xc400000003)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/export.go:467 +0x4b
created by github.com/dgraph-io/dgraph/worker.ExportOverNetwork
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/export.go:468 +0x157
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb67e58]

goroutine 78834 [running]:
github.com/dgraph-io/dgraph/worker.(*node).Raft(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:199 +0x38
github.com/dgraph-io/dgraph/worker.(*node).AmLeader(0x0, 0x100000002)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:989 +0x43
github.com/dgraph-io/dgraph/worker.handleExportForGroup(0x7fc1e01da1f0, 0xc420014450, 0x3f784e94ec36151a, 0x2, 0x0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/export.go:332 +0x67
github.com/dgraph-io/dgraph/worker.ExportOverNetwork.func1(0xc4578ad980, 0x7fc1e01da1f0, 0xc420014450, 0xc400000002)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/export.go:467 +0x4b
created by github.com/dgraph-io/dgraph/worker.ExportOverNetwork
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/export.go:468 +0x157
```

**Comment by pawanrawal** [comment]
A fix has been pushed to `master` and `release/v0.8.1` branch. The binaries should be updated in an hour.
