### ISSUE TITLE
Crashes when mutating single nested node

### ISSUE THREAD

**Issue by Phaze1D** [dgraph-io/dgraph#1474]
Recreating bug 

Graph schema looks like this
```
{
  name: string @index(exact) .
  type: string @index(exact) .
  num: int .
  subNode: uid @reverse .
}
```

Graph structure 
```
NodeA = {
  name = "NameValue"
  subNode = {
    type="facebook"
    num=12
  }
}

NodeB = { 
  uid = 0x2
  name = "OtherName"
  subNode = {
    type="facebook"
    num=1
  }
}
```

### Bug 1
```
{
  user(func: uid("0x2")){
    said as subNode @filter(eq(type, "facebook"))
  }
}
  
mutation {
  set {
    uid(said) <num> "123" .
  }
}
```
This mutation should only change NodeB.subNode.num to 123 but instead it changes all subNode.num to 123

### Crash Bug
```
{
  user(func: uid("0x2")){
    subNode @filter(eq(type, "facebook")) {
      said as _uid_
    }
  }
}
  
mutation {
  set {
    uid(said) <num> "65" .
  }
}
```
This mutation will crash the server with this error 
```
2017/09/16 00:57:05 http: panic serving 172.17.0.1:48286: runtime error: index out of range  [9/1885]
goroutine 10278 [running]:                                                                           
net/http.(*conn).serve.func1(0xc4202d20a0)                                                           
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:1721 +0xd0             
panic(0xd243c0, 0x1416d90)                                                                           
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:489 +0x2cf               
github.com/dgraph-io/dgraph/query.(*SubGraph).populateUidValVar(0xc4201cec80, 0xc4201aec60, 0xc42012e
090, 0x2, 0x2, 0x2, 0x2)                                                                             
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1428 +0x367
github.com/dgraph-io/dgraph/query.(*SubGraph).assignVars(0xc4201cec80, 0xc4201aec60, 0xc42012e080, 0$
2, 0x2, 0x0, 0xc42012e080)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1382 +0x106
github.com/dgraph-io/dgraph/query.(*SubGraph).populateVarMap(0xc4201cec80, 0xc4201aec60, 0xc42012e080
, 0x2, 0x2, 0xc42012e080, 0x1)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1372 +0x5fe
github.com/dgraph-io/dgraph/query.(*SubGraph).populateVarMap(0xc4201ce500, 0xc4201aec60, 0xc42012e080
, 0x2, 0x2, 0xc420086158, 0x0)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1327 +0x1a6
github.com/dgraph-io/dgraph/query.(*SubGraph).populateVarMap(0xc4201ce000, 0xc4201aec60, 0xc420086158
, 0x1, 0x1, 0x0, 0xc420066de0)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1327 +0x1a6
github.com/dgraph-io/dgraph/query.(*QueryRequest).ProcessQuery(0xc424de1bf8, 0x14335e0, 0xc420066d20,
 0xc4201407d0, 0x0)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:2333 +0xbb1
github.com/dgraph-io/dgraph/query.(*QueryRequest).ProcessWithMutation(0xc424de1bf8, 0x14335e0, 0xc420
066d20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4201aec30, ...)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:2455 +0x62f
main.queryHandler(0x14328a0, 0xc420206380, 0xc42a4dc100)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:307 +0x9ee
net/http.HandlerFunc.ServeHTTP(0xe38398, 0x14328a0, 0xc420206380, 0xc42a4dc100)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:1942 +0x44     net/http.(*ServeMux).ServeHTTP(0x14a3c80, 0x14328a0, 0xc420206380, 0xc42a4dc100)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:2238 +0x130 net/http.serverHandler.ServeHTTP(0xc4200a4370, 0x14328a0, 0xc420206380, 0xc42a4dc100)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4202d20a0, 0x1433560, 0xc42a24a040)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:2668 +0x2ce

```

**Comment by pawanrawal** [comment]
Thanks for reporting the issue @Phaze1D 

The first bug was fixed with ad1d6e4336da4d3b1c38bb2a9803ceaec283f5e0 and the second issue has been fixed with afb10be2d8b448968dcf6fb7b3ae2d81ab8403f2. Both the fixes will be part of the upcoming release.
