### ISSUE TITLE
Crash during predicate move

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1692]
Seen in master at 6ba6f276 (EDIT: also at the latest master at be4f27ae).

The "goldendata" dataset is used. Setup is a cluster with 3 dgraph instances, 00 and 01 are replicas, 02 is in its own group. The predicate `name` is moved from one group to the other, and causes the receiving dgraph to crash.

Full log:

```
Starting container:
7fe6df9ea9d98cb044d990ec2f40118eec252e578bfa5c9fcf7326027a812ac4
==> bulk-loader.log <==

==> dg00.log <==

==> dg01.log <==

==> dg02.log <==

==> zero.log <==
Setting up listener at: localhost:8888
Setting up listener at: localhost:8889
2017/10/29 23:42:02 node.go:230: Group 0 found 0 entries
2017/10/29 23:42:02 raft.go:567: INFO: 1 became follower at term 0
2017/10/29 23:42:02 raft.go:315: INFO: newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017/10/29 23:42:02 raft.go:567: INFO: 1 became follower at term 1
Running Dgraph zero...
2017/10/29 23:42:05 raft.go:749: INFO: 1 is starting a new election at term 1
2017/10/29 23:42:05 raft.go:580: INFO: 1 became candidate at term 2
2017/10/29 23:42:05 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 2
2017/10/29 23:42:05 raft.go:621: INFO: 1 became leader at term 2
2017/10/29 23:42:05 node.go:301: INFO: raft.node: 1 elected leader 1 at term 2

==> bulk-loader.log <==
{
	"RDFDir": "/data/goldendata.rdf.gz",
	"SchemaFile": "/data/goldendata.schema",
	"DgraphsDir": "out",
	"LeaseFile": "LEASE",
	"TmpDir": "tmp",
	"NumGoroutines": 4,
	"MapBufSize": 67108864,
	"ExpandEdges": true,
	"BlockRate": 0,
	"SkipMapPhase": false,
	"CleanupTmp": true,
	"NumShufflers": 1,
	"Version": false,
	"StoreXids": false,
	"ZeroAddr": "localhost:8888",
	"MapShards": 2,
	"ReduceShards": 2
}
The bulk loader needs to open many files at once. This number depends on the size of the data set loaded, the map file output size, and the level of indexing. 100,000 is adequate for most data set sizes. See `man ulimit` for details of how to change the limit.
[32mCurrent max open files limit: 1048576
[0mMAP 01s rdf_count:387.0 rdf_speed:383.2/sec edge_count:1.252k edge_speed:1.240k/sec
MAP 02s rdf_count:814.0 rdf_speed:404.9/sec edge_count:2.649k edge_speed:1.318k/sec
MAP 03s rdf_count:1.390k rdf_speed:461.6/sec edge_count:4.444k edge_speed:1.476k/sec
MAP 04s rdf_count:2.188k rdf_speed:545.4/sec edge_count:6.999k edge_speed:1.745k/sec
MAP 05s rdf_count:4.449k rdf_speed:887.7/sec edge_count:14.34k edge_speed:2.862k/sec
MAP 06s rdf_count:201.4k rdf_speed:33.51k/sec edge_count:638.4k edge_speed:106.2k/sec
MAP 07s rdf_count:472.8k rdf_speed:67.42k/sec edge_count:1.528M edge_speed:217.9k/sec
MAP 08s rdf_count:730.0k rdf_speed:91.11k/sec edge_count:2.394M edge_speed:298.8k/sec
MAP 09s rdf_count:992.4k rdf_speed:110.1k/sec edge_count:3.269M edge_speed:362.7k/sec
MAP 10s rdf_count:1.121M rdf_speed:110.7k/sec edge_count:3.695M edge_speed:364.8k/sec
MAP 11s rdf_count:1.121M rdf_speed:100.7k/sec edge_count:3.695M edge_speed:332.0k/sec
MAP 12s rdf_count:1.121M rdf_speed:92.41k/sec edge_count:3.695M edge_speed:304.6k/sec
REDUCE 13s [5.87%] edge_count:217.0k edge_speed:217.0k/sec plist_count:192.8k plist_speed:192.8k/sec
REDUCE 14s [15.11%] edge_count:558.5k edge_speed:558.4k/sec plist_count:373.0k plist_speed:372.9k/sec
REDUCE 15s [46.40%] edge_count:1.715M edge_speed:857.1k/sec plist_count:583.8k plist_speed:291.9k/sec
REDUCE 16s [56.04%] edge_count:2.071M edge_speed:690.1k/sec plist_count:780.3k plist_speed:260.1k/sec
REDUCE 17s [64.16%] edge_count:2.371M edge_speed:592.6k/sec plist_count:1.005M plist_speed:251.3k/sec
REDUCE 18s [73.97%] edge_count:2.733M edge_speed:546.5k/sec plist_count:1.122M plist_speed:224.4k/sec
REDUCE 19s [85.64%] edge_count:3.165M edge_speed:527.3k/sec plist_count:1.399M plist_speed:233.1k/sec
REDUCE 20s [93.76%] edge_count:3.465M edge_speed:494.9k/sec plist_count:1.652M plist_speed:235.9k/sec
REDUCE 21s [100.00%] edge_count:3.695M edge_speed:461.8k/sec plist_count:1.741M plist_speed:217.6k/sec
REDUCE 21s [100.00%] edge_count:3.695M edge_speed:459.1k/sec plist_count:1.741M plist_speed:216.3k/sec
Total: 21s

==> dg00.log <==
2017/10/29 23:42:28 groups.go:107: Current Raft Id: 10
2017/10/29 23:42:28 gRPC server started.  Listening on port 9080
2017/10/29 23:42:28 HTTP server started.  Listening on port 8080
2017/10/29 23:42:28 pool.go:104: == CONNECT ==> Setting localhost:8888
2017/10/29 23:42:28 worker.go:103: Worker listening at address: [::]:12345
2017/10/29 23:42:28 groups.go:127: Connected to group zero. Connection state: member:<id:10 group_id:1 addr:"localhost:12345" > state:<counter:939 groups:<key:1 value:<members:<key:10 value:<id:10 group_id:1 addr:"localhost:12345" > > > > zeros:<key:1 value:<id:1 addr:"localhost:8888" leader:true > > maxLeaseId:102630000 maxTxnTs:10000 > 
2017/10/29 23:42:28 draft.go:136: Node ID: 10 with GroupID: 1
2017/10/29 23:42:28 node.go:230: Group 1 found 0 entries
2017/10/29 23:42:28 draft.go:669: New Node for group: 1
2017/10/29 23:42:28 raft.go:567: INFO: a became follower at term 0
2017/10/29 23:42:28 raft.go:315: INFO: newRaft a [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017/10/29 23:42:28 raft.go:567: INFO: a became follower at term 1
Asking if I can serve tablet for: _predicate_
Asking if I can serve tablet for: name
2017/10/29 23:42:28 raft.go:749: INFO: a is starting a new election at term 1
2017/10/29 23:42:28 raft.go:580: INFO: a became candidate at term 2
2017/10/29 23:42:28 raft.go:664: INFO: a received MsgVoteResp from a at term 2
2017/10/29 23:42:28 raft.go:621: INFO: a became leader at term 2
2017/10/29 23:42:28 node.go:301: INFO: raft.node: a elected leader a at term 2
2017/10/29 23:42:28 mutation.go:166: Done schema update predicate:"_predicate_" value_type:9 list:true 
Asking if I can serve tablet for: initial_release_date

==> zero.log <==
2017/10/29 23:42:28 zero.go:244: Got connection request: id:10 addr:"localhost:12345" 
2017/10/29 23:42:28 pool.go:104: == CONNECT ==> Setting localhost:12345
2017/10/29 23:42:28 zero.go:340: Connected

==> dg00.log <==
Asking if I can serve tablet for: type.property.schema
Asking if I can serve tablet for: type.property.reverse_property
Asking if I can serve tablet for: http://www.w3.org/2000/01/rdf-schema#domain
Asking if I can serve tablet for: directed_by
Asking if I can serve tablet for: director.film
Asking if I can serve tablet for: type.property.expected_type
Asking if I can serve tablet for: http://www.w3.org/2002/07/owl#inverseOf
Asking if I can serve tablet for: http://www.w3.org/2000/01/rdf-schema#range
2017/10/29 23:42:29 pool.go:104: == CONNECT ==> Setting localhost:12355
2017/10/29 23:42:29 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:42:29 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:42:29 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:42:29 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:42:29 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:42:29 node.go:464: RECEIVED: MsgAppResp 11-->10

==> dg01.log <==
2017/10/29 23:42:29 groups.go:107: Current Raft Id: 11
2017/10/29 23:42:29 pool.go:104: == CONNECT ==> Setting localhost:8888
2017/10/29 23:42:29 worker.go:103: Worker listening at address: 127.0.0.1:12355
2017/10/29 23:42:29 gRPC server started.  Listening on port 9090
2017/10/29 23:42:29 HTTP server started.  Listening on port 8090
2017/10/29 23:42:29 groups.go:127: Connected to group zero. Connection state: member:<id:11 group_id:1 addr:"localhost:12355" > state:<counter:963 groups:<key:1 value:<members:<key:10 value:<id:10 group_id:1 addr:"localhost:12345" leader:true last_update:1509320549 > > members:<key:11 value:<id:11 group_id:1 addr:"localhost:12355" > > tablets:<key:"_predicate_" value:<group_id:1 predicate:"_predicate_" space:45553016 > > tablets:<key:"directed_by" value:<group_id:1 predicate:"directed_by" space:16 > > tablets:<key:"director.film" value:<group_id:1 predicate:"director.film" space:18 > > tablets:<key:"http://www.w3.org/2000/01/rdf-schema#domain" value:<group_id:1 predicate:"http://www.w3.org/2000/01/rdf-schema#domain" space:363 > > tablets:<key:"http://www.w3.org/2000/01/rdf-schema#range" value:<group_id:1 predicate:"http://www.w3.org/2000/01/rdf-schema#range" space:47 > > tablets:<key:"http://www.w3.org/2002/07/owl#inverseOf" value:<group_id:1 predicate:"http://www.w3.org/2002/07/owl#inverseOf" space:44 > > tablets:<key:"initial_release_date" value:<group_id:1 predicate:"initial_release_date" space:33784446 > > tablets:<key:"name" value:<group_id:1 predicate:"name" space:62564327 > > tablets:<key:"type.property.expected_type" value:<group_id:1 predicate:"type.property.expected_type" space:32 > > tablets:<key:"type.property.reverse_property" value:<group_id:1 predicate:"type.property.reverse_property" space:125 > > tablets:<key:"type.property.schema" value:<group_id:1 predicate:"type.property.schema" space:271 > > > > zeros:<key:1 value:<id:1 addr:"localhost:8888" leader:true > > maxLeaseId:102630000 maxTxnTs:10000 > 
2017/10/29 23:42:29 pool.go:104: == CONNECT ==> Setting localhost:12345
2017/10/29 23:42:29 draft.go:136: Node ID: 11 with GroupID: 1
2017/10/29 23:42:29 node.go:230: Group 1 found 0 entries
2017/10/29 23:42:29 draft.go:669: New Node for group: 1
2017/10/29 23:42:29 draft.go:645: Calling JoinCluster
2017/10/29 23:42:29 draft.go:649: Done with JoinCluster call
2017/10/29 23:42:29 raft.go:567: INFO: b became follower at term 0
2017/10/29 23:42:29 raft.go:315: INFO: newRaft b [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017/10/29 23:42:29 raft.go:567: INFO: b became follower at term 1
2017/10/29 23:42:29 raft.go:708: INFO: b [term: 1] received a MsgHeartbeat message with higher term from a [term: 2]
2017/10/29 23:42:29 raft.go:567: INFO: b became follower at term 2
2017/10/29 23:42:29 node.go:301: INFO: raft.node: b elected leader a at term 2
2017/10/29 23:42:29 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:42:29 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:42:29 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:42:29 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:42:29 mutation.go:145: Done schema update predicate:"_predicate_" value_type:9 list:true 
2017/10/29 23:42:29 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:42:29 node.go:161: 		SENDING: MsgAppResp 11-->10

==> zero.log <==
2017/10/29 23:42:29 zero.go:244: Got connection request: id:11 addr:"localhost:12355" 
2017/10/29 23:42:29 pool.go:104: == CONNECT ==> Setting localhost:12355
2017/10/29 23:42:29 zero.go:340: Connected

==> dg00.log <==
2017/10/29 23:42:30 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:42:30 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:42:30 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:42:30 pool.go:104: == CONNECT ==> Setting localhost:12365
2017/10/29 23:42:30 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:42:30 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:42:30 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:42:30 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:42:30 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:42:30 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:42:30 node.go:464: RECEIVED: MsgAppResp 11-->10

==> dg01.log <==
2017/10/29 23:42:30 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:42:30 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:42:30 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:42:30 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:42:30 pool.go:104: == CONNECT ==> Setting localhost:12365
2017/10/29 23:42:30 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:42:30 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:42:30 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:42:30 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:42:30 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:42:30 node.go:161: 		SENDING: MsgAppResp 11-->10

==> dg02.log <==
2017/10/29 23:42:30 groups.go:107: Current Raft Id: 12
2017/10/29 23:42:30 pool.go:104: == CONNECT ==> Setting localhost:8888
2017/10/29 23:42:30 worker.go:103: Worker listening at address: 127.0.0.1:12365
2017/10/29 23:42:30 gRPC server started.  Listening on port 9100
2017/10/29 23:42:30 HTTP server started.  Listening on port 8100
2017/10/29 23:42:30 groups.go:127: Connected to group zero. Connection state: member:<id:12 group_id:2 addr:"localhost:12365" > state:<counter:964 groups:<key:1 value:<members:<key:10 value:<id:10 group_id:1 addr:"localhost:12345" leader:true last_update:1509320549 > > members:<key:11 value:<id:11 group_id:1 addr:"localhost:12355" > > tablets:<key:"_predicate_" value:<group_id:1 predicate:"_predicate_" space:45553016 > > tablets:<key:"directed_by" value:<group_id:1 predicate:"directed_by" space:16 > > tablets:<key:"director.film" value:<group_id:1 predicate:"director.film" space:18 > > tablets:<key:"http://www.w3.org/2000/01/rdf-schema#domain" value:<group_id:1 predicate:"http://www.w3.org/2000/01/rdf-schema#domain" space:363 > > tablets:<key:"http://www.w3.org/2000/01/rdf-schema#range" value:<group_id:1 predicate:"http://www.w3.org/2000/01/rdf-schema#range" space:47 > > tablets:<key:"http://www.w3.org/2002/07/owl#inverseOf" value:<group_id:1 predicate:"http://www.w3.org/2002/07/owl#inverseOf" space:44 > > tablets:<key:"initial_release_date" value:<group_id:1 predicate:"initial_release_date" space:33784446 > > tablets:<key:"name" value:<group_id:1 predicate:"name" space:62564327 > > tablets:<key:"type.property.expected_type" value:<group_id:1 predicate:"type.property.expected_type" space:32 > > tablets:<key:"type.property.reverse_property" value:<group_id:1 predicate:"type.property.reverse_property" space:125 > > tablets:<key:"type.property.schema" value:<group_id:1 predicate:"type.property.schema" space:271 > > > > groups:<key:2 value:<members:<key:12 value:<id:12 group_id:2 addr:"localhost:12365" > > > > zeros:<key:1 value:<id:1 addr:"localhost:8888" leader:true > > maxLeaseId:102630000 maxTxnTs:10000 > 
2017/10/29 23:42:30 pool.go:104: == CONNECT ==> Setting localhost:12345
2017/10/29 23:42:30 pool.go:104: == CONNECT ==> Setting localhost:12355
2017/10/29 23:42:30 draft.go:136: Node ID: 12 with GroupID: 2
2017/10/29 23:42:30 node.go:230: Group 2 found 0 entries
2017/10/29 23:42:30 draft.go:669: New Node for group: 2
2017/10/29 23:42:30 raft.go:567: INFO: c became follower at term 0
2017/10/29 23:42:30 raft.go:315: INFO: newRaft c [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017/10/29 23:42:30 raft.go:567: INFO: c became follower at term 1
2017/10/29 23:42:30 raft.go:749: INFO: c is starting a new election at term 1
2017/10/29 23:42:30 raft.go:580: INFO: c became candidate at term 2
2017/10/29 23:42:30 raft.go:664: INFO: c received MsgVoteResp from c at term 2
2017/10/29 23:42:30 raft.go:621: INFO: c became leader at term 2
2017/10/29 23:42:30 node.go:301: INFO: raft.node: c elected leader c at term 2

==> zero.log <==
2017/10/29 23:42:30 zero.go:244: Got connection request: id:12 addr:"localhost:12365" 
2017/10/29 23:42:30 pool.go:104: == CONNECT ==> Setting localhost:12365
2017/10/29 23:42:30 zero.go:340: Connected

==> dg00.log <==
Asking if I can serve tablet for: _dummy_
2017/10/29 23:47:29 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:47:29 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:47:29 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:47:29 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:47:29 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:47:29 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:47:29 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:47:29 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:47:29 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:47:29 node.go:464: RECEIVED: MsgAppResp 11-->10

==> dg01.log <==
2017/10/29 23:47:29 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:47:29 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:47:29 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:47:29 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:47:29 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:47:29 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:47:29 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:47:29 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:47:29 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:47:29 node.go:161: 		SENDING: MsgAppResp 11-->10

==> dg00.log <==
2017/10/29 23:50:02 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:50:02 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:50:02 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:50:02 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:50:02 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:50:02 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:50:02 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:50:02 node.go:464: RECEIVED: MsgAppResp 11-->10

==> dg01.log <==
2017/10/29 23:50:02 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:50:02 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:50:02 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:50:02 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:50:02 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:50:02 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:50:02 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:50:02 node.go:161: 		SENDING: MsgAppResp 11-->10

==> zero.log <==
2017/10/29 23:50:02 tablet.go:161: 

Groups sorted by size: [{gid:2 size:0} {gid:1 size:141902723}]

2017/10/29 23:50:02 tablet.go:166: size_diff 141902723
2017/10/29 23:50:02 tablet.go:83: Going to move predicate name from 1 to 2

==> dg00.log <==
2017/10/29 23:50:06 predicate_move.go:141: Sent 261663 number of keys for predicate name

==> dg02.log <==
2017/10/29 23:50:07 predicate_move.go:49: Writing 261663 keys

==> dg00.log <==
2017/10/29 23:50:08 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:50:08 node.go:464: RECEIVED: MsgAppResp 11-->10
2017/10/29 23:50:08 node.go:161: 		SENDING: MsgApp 10-->11
2017/10/29 23:50:08 node.go:464: RECEIVED: MsgAppResp 11-->10

==> dg01.log <==
2017/10/29 23:50:08 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:50:08 node.go:161: 		SENDING: MsgAppResp 11-->10
2017/10/29 23:50:08 node.go:464: RECEIVED: MsgApp 10-->11
2017/10/29 23:50:08 node.go:161: 		SENDING: MsgAppResp 11-->10

==> dg02.log <==
2017/10/29 23:50:08 predicate_move.go:236: received 261663 number of keys, error <nil>

==> dg00.log <==
2017/10/29 23:52:30 pool.go:150: Echo error from localhost:12365. Err: rpc error: code = Unavailable desc = transport is closing

==> dg01.log <==
2017/10/29 23:52:30 pool.go:150: Echo error from localhost:12365. Err: rpc error: code = Unavailable desc = transport is closing

==> dg02.log <==
panic: runtime error: slice bounds out of range

goroutine 1319 [running]:
github.com/dgraph-io/dgraph/x.Parse(0xc447e79af0, 0xc, 0x10, 0x8)
	/home/petsta/go/src/github.com/dgraph-io/dgraph/x/keys.go:288 +0x4b0
github.com/dgraph-io/dgraph/worker.(*groupi).cleanupTablets.func1(0xc42573e100)
	/home/petsta/go/src/github.com/dgraph-io/dgraph/worker/groups.go:542 +0x17f
github.com/dgraph-io/dgraph/worker.(*groupi).cleanupTablets(0xc42573e100)
	/home/petsta/go/src/github.com/dgraph-io/dgraph/worker/groups.go:570 +0x5d
created by github.com/dgraph-io/dgraph/worker.StartRaftNodes
	/home/petsta/go/src/github.com/dgraph-io/dgraph/worker/groups.go:144 +0x705

==> dg00.log <==
2017/10/29 23:52:40 pool.go:150: Echo error from localhost:12365. Err: rpc error: code = Unavailable desc = grpc: the connection is unavailable

==> dg01.log <==
2017/10/29 23:52:40 pool.go:150: Echo error from localhost:12365. Err: rpc error: code = Unavailable desc = grpc: the connection is unavailable

==> zero.log <==
2017/10/29 23:52:40 pool.go:150: Echo error from localhost:12365. Err: rpc error: code = Unavailable desc = grpc: the connection is unavailable
```

**Comment by peterstace** [comment]
This looks suspicious to me. Both groups should have some data in them, but group 2 seems to have size 0. I have the output from the bulk loader to dgraph00 and dgraph02.
```
Groups sorted by size: [{gid:2 size:0} {gid:1 size:141902723}]
```

**Comment by manishrjain** [comment]
Why is it crashing, any ideas?

**Comment by peterstace** [comment]
I haven't been able to reproduce this (although I reproduced it a few times yesterday). From looking at that area of the code, the only way I can see it happening is if I've used a previous version of bulk loader with newer dgraph.
