### ISSUE TITLE
dgraphmerge panics

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#186]
On trying to merge two stores after assigning uids to them, `dgraphmerge` panics with 

```
panic: interface conversion: interface {} is []uint8, not *posting.List

goroutine 1 [running]:
panic(0x72a0c0, 0xc420019a80)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.equalValue(0x7036c0, 0xc4201036a0, 0x7036c0, 0xc4201036c0, 0xc4201036c0)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/cmd/dgraphmerge/main.go:71 +0x41e
main.mergeFolders(0x7ffebbaed737, 0x18, 0x7ffebbaed757, 0x15)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/cmd/dgraphmerge/main.go:146 +0x1181
main.main()
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/cmd/dgraphmerge/main.go:188 +0x83
```

Verified that this error is there from atleast release `v0.4.0`.

**Comment by manishrjain** [comment]
I'm surprised we didn't catch this earlier. Git has a way to do binary searches over commits, to help figure out the culprit. https://git-scm.com/docs/git-bisect -- Maybe that could be useful?

**Comment by ashwin95r** [comment]
Commit 01bbadc8b1f9f1751a392e898f8028fa9790312f fixes the issue.
