### ISSUE TITLE
Tablet isn't being served by this instance

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1896]
I see the following error intermittently during CI tests.

Even though I haven't seen in locally, seeing in CI tests indicates that it *could* happen.

The error is always in the same form (2 examples):

```
2017/12/08 03:41:45 groups.go:300: Asking if I can serve tablet for: random
--- FAIL: TestSchemaBlock4 (0.00s)
	Error Trace:	common_test.go:257
			query_test.go:5708
	Error:		Received unexpected error:
			Tablet isn't being served by this instance.
```
```
2017/12/08 03:41:45 groups.go:300: Asking if I can serve tablet for: random
--- FAIL: TestXidInvalidJSON (0.05s)
	Error Trace:	common_test.go:247
			query_test.go:6014
	Error:		Received unexpected error:
			Tablet isn't being served by this instance.
```

**Comment by janardhan1993** [comment]
This was because of the way we wrote unit tests. We were simulating zero in unit tests and it was sending empty tablets map in the tests.

**Comment by pawanrawal** [comment]
It's still there

https://teamcity.dgraph.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=220&_focus=1928

**Comment by janardhan1993** [comment]
Fixed in master, we are no longer simulating zero in query_test

**Comment by pawanrawal** [comment]
Still there https://teamcity.dgraph.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=366&_focus=1507.

**Comment by janardhan1993** [comment]
Grpc-go had a race condition where server was closing the connection. I tried the fix from 
https://github.com/grpc/grpc-go/pull/1905 (not merged yet) and we don't see this issue anymore while  running query test with race flag.

**Comment by manishrjain** [comment]
This is a funny thread!

**Comment by janardhan1993** [comment]
Should be fixed with latest grpc master

**Comment by yatender-oktalk** [comment]
my dgraph zero 
```
Setting up grpc listener at: 0.0.0.0:5080
Setting up http listener at: 0.0.0.0:6080
2018/06/14 21:06:33 node.go:228: Found hardstate: {Term:1 Vote:0 Commit:1 XXX_unrecognized:[]}
2018/06/14 21:06:33 node.go:240: Group 0 found 1 entries
2018/06/14 21:06:33 raft.go:420: Restarting node for dgraphzero
2018/06/14 21:06:33 raft.go:567: INFO: 1 became follower at term 1
2018/06/14 21:06:33 raft.go:316: INFO: newRaft 1 [peers: [], term: 1, commit: 1, applied: 0, lastindex: 1, lastterm: 1]
Running Dgraph zero...
2018/06/14 21:06:33 node.go:118: Setting conf state to nodes:1
2018/06/14 21:06:37 raft.go:749: INFO: 1 is starting a new election at term 1
2018/06/14 21:06:37 raft.go:580: INFO: 1 became candidate at term 2
2018/06/14 21:06:37 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 2
2018/06/14 21:06:37 raft.go:621: INFO: 1 became leader at term 2
2018/06/14 21:06:37 node.go:301: INFO: raft.node: 1 elected leader 1 at term 2
2018/06/14 21:06:40 zero.go:336: Got connection request: addr:"localhost:7080"
2018/06/14 21:06:40 pool.go:108: == CONNECT ==> Setting localhost:7080
2018/06/14 21:06:40 zero.go:445: Connected
```
dgraph server
```
2018/06/14 21:11:23 groups.go:167: Error while proposing initial schema:  Tablet isn't being served by this instance.
2018/06/14 21:11:23 groups.go:167: Error while proposing initial schema:  Tablet isn't being served by this instance.
2018/06/14 21:11:23 groups.go:167: Error while proposing initial schema:  Tablet isn't being served by this instance.
2018/06/14 21:11:23 pool.go:158: Echo error from localhsot:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/06/14 21:11:23 groups.go:167: Error while proposing initial schema:  Tablet isn't being served by this instance.
2018/06/14 21:11:23 groups.go:167: Error while proposing initial schema:  Tablet isn't being served by this instance.
2018/06/14 21:11:23 groups.go:167: Error while proposing initial schema:  Tablet isn't being served by this instance.
```
any idea?

**Comment by manishrjain** [comment]
It seems like this server had some data, which it was not allowed to serve.

**Comment by rcgoodfellow** [comment]
I'm seeing the same thing as @yatender-oktalk . 4 nodes, all on the same LAN, 1 zero, 3 servers. Running on Fedora 28

zero logs
```shell
Jul 11 04:28:15 zero systemd[1]: Started Dgraph Server Service.
Jul 11 04:28:15 zero dgraph[1978]: Setting up grpc listener at: 0.0.0.0:5080
Jul 11 04:28:15 zero dgraph[1978]: Setting up http listener at: 0.0.0.0:6080
Jul 11 04:28:15 zero dgraph[1978]: 2018/07/11 04:28:15 node.go:244: Group 0 found 1 entries
Jul 11 04:28:15 zero dgraph[1978]: 2018/07/11 04:28:15 raft.go:567: INFO: 1 became follower at term 0
Jul 11 04:28:15 zero dgraph[1978]: 2018/07/11 04:28:15 raft.go:315: INFO: newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
Jul 11 04:28:15 zero dgraph[1978]: 2018/07/11 04:28:15 raft.go:567: INFO: 1 became follower at term 1
Jul 11 04:28:15 zero dgraph[1978]: Running Dgraph zero...
Jul 11 04:28:15 zero dgraph[1978]: 2018/07/11 04:28:15 node.go:135: Setting conf state to nodes:1
Jul 11 04:28:17 zero dgraph[1978]: 2018/07/11 04:28:17 raft.go:749: INFO: 1 is starting a new election at term 1
Jul 11 04:28:17 zero dgraph[1978]: 2018/07/11 04:28:17 raft.go:580: INFO: 1 became candidate at term 2
Jul 11 04:28:17 zero dgraph[1978]: 2018/07/11 04:28:17 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 2
Jul 11 04:28:17 zero dgraph[1978]: 2018/07/11 04:28:17 raft.go:621: INFO: 1 became leader at term 2
Jul 11 04:28:17 zero dgraph[1978]: 2018/07/11 04:28:17 node.go:301: INFO: raft.node: 1 elected leader 1 at term 2
Jul 11 04:28:40 zero dgraph[1978]: 2018/07/11 04:28:40 zero.go:333: Got connection request: addr:"10.0.0.5:7080"
Jul 11 04:28:40 zero dgraph[1978]: 2018/07/11 04:28:40 pool.go:108: == CONNECT ==> Setting 10.0.0.5:7080
Jul 11 04:28:40 zero dgraph[1978]: 2018/07/11 04:28:40 zero.go:441: Connected
Jul 11 04:28:40 zero dgraph[1978]: 2018/07/11 04:28:40 zero.go:333: Got connection request: addr:"10.0.0.4:7080"
Jul 11 04:28:40 zero dgraph[1978]: 2018/07/11 04:28:40 pool.go:108: == CONNECT ==> Setting 10.0.0.4:7080
Jul 11 04:28:40 zero dgraph[1978]: 2018/07/11 04:28:40 zero.go:441: Connected
Jul 11 04:28:40 zero dgraph[1978]: 2018/07/11 04:28:40 zero.go:333: Got connection request: addr:"10.0.0.3:7080"
Jul 11 04:28:40 zero dgraph[1978]: 2018/07/11 04:28:40 pool.go:108: == CONNECT ==> Setting 10.0.0.3:7080
Jul 11 04:28:40 zero dgraph[1978]: 2018/07/11 04:28:40 zero.go:441: Connected
Jul 11 04:28:41 zero dgraph[1978]: 2018/07/11 04:28:41 zero.go:333: Got connection request: addr:"10.0.0.2:7080"
Jul 11 04:28:41 zero dgraph[1978]: 2018/07/11 04:28:41 pool.go:108: == CONNECT ==> Setting 10.0.0.2:7080
Jul 11 04:28:41 zero dgraph[1978]: 2018/07/11 04:28:41 zero.go:441: Connected
```

server
```-- Logs begin at Sat 2018-06-09 15:51:40 UTC, end at Wed 2018-07-11 04:44:14 UTC. --
Jul 11 04:28:41 n0 systemd[1]: Started Dgraph Server Service.
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 server.go:116: Setting Badger option: default
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 server.go:131: Setting Badger table load option: mmap
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 server.go:143: Setting Badger value log load option: mmap
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 server.go:153: Opening postings Badger DB with options: {Dir:p ValueDir:p SyncWrites:true TableLoadingMode:2 Va>
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 groups.go:77: Current Raft Id: 0
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 worker.go:89: Worker listening at address: [::]:7080
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 gRPC server started.  Listening on port 9080
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 HTTP server started.  Listening on port 8080
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 pool.go:108: == CONNECT ==> Setting 10.0.0.1:5080
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 groups.go:104: Connected to group zero. Assigned group: 4
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 pool.go:108: == CONNECT ==> Setting 10.0.0.5:7080
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 pool.go:108: == CONNECT ==> Setting 10.0.0.4:7080
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 pool.go:108: == CONNECT ==> Setting 10.0.0.3:7080
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 pool.go:161: Echo error from 10.0.0.1:7080. Err: rpc error: code = Unavailable desc = all SubConns are in Trans>
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 pool.go:108: == CONNECT ==> Setting 10.0.0.1:7080
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 draft.go:150: Node ID: 4 with GroupID: 4
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 node.go:244: Group 4 found 1 entries
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 draft.go:1032: New Node for group: 4
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 raft.go:567: INFO: 4 became follower at term 0
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 raft.go:315: INFO: newRaft 4 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 raft.go:567: INFO: 4 became follower at term 1
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 groups.go:721: WARNING: We don't have address of any dgraphzero leader.
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 groups.go:490: WARNING: We don't have address of any Zero server.
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 node.go:135: Setting conf state to nodes:4
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 raft.go:749: INFO: 4 is starting a new election at term 1
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 raft.go:580: INFO: 4 became candidate at term 2
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 raft.go:664: INFO: 4 received MsgVoteResp from 4 at term 2
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 raft.go:621: INFO: 4 became leader at term 2
Jul 11 04:28:41 n0 dgraph[1351]: 2018/07/11 04:28:41 node.go:301: INFO: raft.node: 4 elected leader 4 at term 2
Jul 11 04:28:42 n0 dgraph[1351]: 2018/07/11 04:28:42 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:28:42 n0 dgraph[1351]: 2018/07/11 04:28:42 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:28:42 n0 dgraph[1351]: 2018/07/11 04:28:42 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:28:42 n0 dgraph[1351]: 2018/07/11 04:28:42 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
...skipping...
Jul 11 04:44:13 n0 dgraph[1351]: 2018/07/11 04:44:13 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:13 n0 dgraph[1351]: 2018/07/11 04:44:13 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:13 n0 dgraph[1351]: 2018/07/11 04:44:13 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:13 n0 dgraph[1351]: 2018/07/11 04:44:13 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:14 n0 dgraph[1351]: 2018/07/11 04:44:14 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:14 n0 dgraph[1351]: 2018/07/11 04:44:14 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:14 n0 dgraph[1351]: 2018/07/11 04:44:14 groups.go:721: WARNING: We don't have address of any dgraphzero leader.
Jul 11 04:44:14 n0 dgraph[1351]: 2018/07/11 04:44:14 groups.go:490: WARNING: We don't have address of any Zero server.
Jul 11 04:44:14 n0 dgraph[1351]: 2018/07/11 04:44:14 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:14 n0 dgraph[1351]: 2018/07/11 04:44:14 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:14 n0 dgraph[1351]: 2018/07/11 04:44:14 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:14 n0 dgraph[1351]: 2018/07/11 04:44:14 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:14 n0 dgraph[1351]: 2018/07/11 04:44:14 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:14 n0 dgraph[1351]: 2018/07/11 04:44:14 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:14 n0 dgraph[1351]: 2018/07/11 04:44:14 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:14 n0 dgraph[1351]: 2018/07/11 04:44:14 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:15 n0 dgraph[1351]: 2018/07/11 04:44:15 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:15 n0 dgraph[1351]: 2018/07/11 04:44:15 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:15 n0 dgraph[1351]: 2018/07/11 04:44:15 groups.go:490: WARNING: We don't have address of any Zero server.
Jul 11 04:44:15 n0 dgraph[1351]: 2018/07/11 04:44:15 groups.go:721: WARNING: We don't have address of any dgraphzero leader.
Jul 11 04:44:15 n0 dgraph[1351]: 2018/07/11 04:44:15 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:15 n0 dgraph[1351]: 2018/07/11 04:44:15 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:15 n0 dgraph[1351]: 2018/07/11 04:44:15 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:15 n0 dgraph[1351]: 2018/07/11 04:44:15 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:15 n0 dgraph[1351]: 2018/07/11 04:44:15 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:15 n0 dgraph[1351]: 2018/07/11 04:44:15 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:15 n0 dgraph[1351]: 2018/07/11 04:44:15 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:15 n0 dgraph[1351]: 2018/07/11 04:44:15 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:16 n0 dgraph[1351]: 2018/07/11 04:44:16 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:16 n0 dgraph[1351]: 2018/07/11 04:44:16 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:16 n0 dgraph[1351]: 2018/07/11 04:44:16 groups.go:721: WARNING: We don't have address of any dgraphzero leader.
Jul 11 04:44:16 n0 dgraph[1351]: 2018/07/11 04:44:16 groups.go:490: WARNING: We don't have address of any Zero server.
Jul 11 04:44:16 n0 dgraph[1351]: 2018/07/11 04:44:16 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:16 n0 dgraph[1351]: 2018/07/11 04:44:16 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:16 n0 dgraph[1351]: 2018/07/11 04:44:16 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.
Jul 11 04:44:16 n0 dgraph[1351]: 2018/07/11 04:44:16 groups.go:159: Error while proposing initial schema:  Tablet isn't being served by this instance.

```

```
$ pgrep -lfa dgraph
1351 /usr/local/bin/dgraph server --lru_mb=5333 --my=10.0.0.2:7080 --zero=10.0.0.1:5080
```

```
$ dgraph version

Dgraph version   : v1.0.6
Commit SHA-1     : ae8e5ffd
Commit timestamp : 2018-06-29 19:27:35 -0700
Branch           : HEAD

For Dgraph official documentation, visit https://docs.dgraph.io.
For discussions about Dgraph     , visit https://discuss.dgraph.io.
To say hi to the community       , visit https://dgraph.slack.com.

Licensed under Apache 2.0 + Commons Clause. Copyright 2015-2018 Dgraph Labs, Inc.


```

**Comment by rcgoodfellow** [comment]
Sorry, pebkac. Had the zero port set to `7080` and not `5080`. Fixed that and things seem to be working.

**Comment by The-Alchemist** [comment]
I just experienced this issue with dgraph 1.0.16 during a high write test.

```
Exception in thread "main" java.lang.RuntimeException: The query encountered an execution exception:
	at io.dgraph.DgraphAsyncClient.lambda$runWithRetries$2(DgraphAsyncClient.java:195)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNKNOWN: : rpc error: code = Unknown desc = Tablet isn't being served by this instance.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.dgraph.DgraphAsyncClient.lambda$runWithRetries$2(DgraphAsyncClient.java:173)
	... 7 more
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: : rpc error: code = Unknown desc = Tablet isn't being served by this instance.
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Is the advice just to re-run the mutation?

**Comment by manishrjain** [comment]
Yeah. Just re-run. Looks like a bunch of table moves happened and the information about who's serving what is eventual consistency model.
