### ISSUE TITLE
Dgraph crashes with unknown tablet

### ISSUE THREAD

**Issue by catroot** [dgraph-io/dgraph#2027]
```
Got schema: [predicate:"name" value_type:STRING directive:INDEX tokenizer:"term"  predicate:"age" value_type:INT directive:INDEX tokenizer:"int"  predicate:"friend" value_type:UID count:true ]
2018/01/17 13:51:20 groups.go:300: Asking if I can serve tablet for: name
2018/01/17 13:51:20 groups.go:300: Asking if I can serve tablet for: age
2018/01/17 13:51:20 groups.go:300: Asking if I can serve tablet for: friend
2018/01/17 13:51:20 mutation.go:152: Done schema update predicate:"name" value_type:STRING directive:INDEX tokenizer:"term"
2018/01/17 13:51:20 mutation.go:152: Done schema update predicate:"age" value_type:INT directive:INDEX tokenizer:"int"
2018/01/17 13:51:20 mutation.go:152: Done schema update predicate:"friend" value_type:UID count:true
2018/01/17 13:51:55 groups.go:300: Asking if I can serve tablet for: owns_pet
panic: runtime error: index out of range

goroutine 5646 [running]:
github.com/dgraph-io/dgraph/worker.getInequalityTokens(0x7, 0xc4203760fe, 0x4, 0xc4203760fb, 0x2, 0x9, 0x11c6300, 0xc4202fa230, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/tokens.go:140 +0x960
github.com/dgraph-io/dgraph/worker.parseSrcFn(0xc42b542780, 0xc420388990, 0x7fc9dd361601, 0x0)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/task.go:1087 +0x2db
github.com/dgraph-io/dgraph/worker.helpProcessTask(0x1a0b060, 0xc42afd53e0, 0xc42b542780, 0x1, 0x0, 0x0, 0x133f6e8)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/task.go:635 +0x6e
github.com/dgraph-io/dgraph/worker.processTask(0x1a0b060, 0xc42afd53e0, 0xc42b542780, 0x1, 0xc4202fa100, 0xc42b542780, 0xc42afccb48)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/task.go:622 +0x1c1
github.com/dgraph-io/dgraph/worker.ProcessTaskOverNetwork(0x1a0b060, 0xc42afd53e0, 0xc42b542780, 0x0, 0xffffffffffffffff, 0x0)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/task.go:151 +0x546
github.com/dgraph-io/dgraph/query.ProcessGraph(0x1a0b060, 0xc42afd53e0, 0xc4200a4000, 0x0, 0xc4257eb320)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1893 +0x1cbd
created by github.com/dgraph-io/dgraph/query.(*QueryRequest).ProcessQuery
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:2519 +0x964

```

Tried query on tuturial dataset:
```
{
  michaels_friends(func: eq(name, ".")) {
    name
    age
    friend {
      name@.
    }
  }
}
```

**Comment by catroot** [comment]
Also failed to start dgraph again:
```
dgraph server --memory_mb 1048 --zero localhost:5080
2018/01/17 14:16:58 groups.go:94: Current Raft Id: 0
2018/01/17 14:16:58 worker.go:99: Worker listening at address: [::]:7080
2018/01/17 14:16:58 gRPC server started.  Listening on port 9080
2018/01/17 14:16:58 HTTP server started.  Listening on port 8080
2018/01/17 14:16:58 pool.go:118: == CONNECT ==> Setting localhost:5080
2018/01/17 14:16:58 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/17 14:16:58 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/17 14:16:58 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/17 14:16:59 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/17 14:16:59 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/17 14:17:00 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/17 14:17:02 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/17 14:17:05 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/17 14:17:11 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/17 14:17:24 Unable to join cluster via dgraphzero
```
dgraph zero reports:
```
2018/01/17 14:19:13 pool.go:167: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/01/17 14:19:13 pool.go:167: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
```

**Comment by janardhan1993** [comment]
@catroot Are you using docker to run dgraph, most probably you don't have persistent storage and hence the invalid address error. If you don't have persistent storage zero will think that a new node is joining the cluster with duplicate address(same as previous node before crash)

**Comment by janardhan1993** [comment]
I have fixed the panic bug in master. Regarding restart error you must have deleted p and w directory of dgraph without removing zw directory in zero or something similar.

**Comment by catroot** [comment]
When i start dgraph zero: 
```
dgraph zero --port_offset -2000
Setting up grpc listener at: 0.0.0.0:5080
Setting up http listener at: 0.0.0.0:6080
2018/01/18 11:57:16 node.go:246: Found hardstate: {Term:7 Vote:1 Commit:89 XXX_unrecognized:[]}
2018/01/18 11:57:16 node.go:258: Group 0 found 89 entries
2018/01/18 11:57:16 raft.go:405: Restarting node for dgraphzero
2018/01/18 11:57:16 raft.go:567: INFO: 1 became follower at term 7
2018/01/18 11:57:16 raft.go:315: INFO: newRaft 1 [peers: [], term: 7, commit: 89, applied: 0, lastindex: 89, lastterm: 7]
Running Dgraph zero...
2018/01/18 11:57:16 node.go:127: Setting conf state to nodes:1
2018/01/18 11:57:16 raft.go:531: While applying proposal: Invalid address
2018/01/18 11:57:16 raft.go:531: While applying proposal: Invalid address
2018/01/18 11:57:16 raft.go:531: While applying proposal: Invalid address
2018/01/18 11:57:16 raft.go:531: While applying proposal: Invalid address
2018/01/18 11:57:16 raft.go:531: While applying proposal: Invalid address
2018/01/18 11:57:16 pool.go:167: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/01/18 11:57:16 pool.go:118: == CONNECT ==> Setting localhost:7080
2018/01/18 11:57:16 pool.go:167: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/01/18 11:57:16 raft.go:531: While applying proposal: Invalid address
2018/01/18 11:57:16 raft.go:531: While applying proposal: Invalid address
2018/01/18 11:57:16 raft.go:531: While applying proposal: Invalid address
2018/01/18 11:57:16 raft.go:531: While applying proposal: Invalid address
2018/01/18 11:57:16 raft.go:531: While applying proposal: Invalid address
2018/01/18 11:57:16 raft.go:531: While applying proposal: Invalid address
2018/01/18 11:57:16 raft.go:531: While applying proposal: Invalid address
and so on
```
after deleting p and w directories starting dgraph serverm, the zero says:
```
2018/01/18 11:58:02 zero.go:322: Got connection request: addr:"localhost:7080"
2018/01/18 11:58:02 raft.go:531: While applying proposal: Invalid address
2018/01/18 11:58:02 zero.go:412: Connected
2018/01/18 11:58:05 oracle.go:375: No healthy connection found to leader of group 1
2018/01/18 11:58:15 oracle.go:381: Error while fetching minTs from group 1, err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/01/18 11:58:16 pool.go:167: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
```
and server says:
```
dgraph server --memory_mb 1048 --zero localhost:5080
2018/01/18 11:57:49 groups.go:86: Current Raft Id: 0
2018/01/18 11:57:49 gRPC server started.  Listening on port 9080
2018/01/18 11:57:49 HTTP server started.  Listening on port 8080
2018/01/18 11:57:49 worker.go:99: Worker listening at address: [::]:7080
2018/01/18 11:57:49 pool.go:118: == CONNECT ==> Setting localhost:5080
2018/01/18 11:57:49 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/18 11:57:49 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/18 11:57:49 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/18 11:57:49 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/18 11:57:50 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/18 11:57:51 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/18 11:57:52 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/18 11:57:56 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/18 11:58:02 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/01/18 11:58:15 Unable to join cluster via dgraphzero
```
So, i can`t start dgraph.

**Comment by janardhan1993** [comment]
You need to delete zw directory of zero also.

**Comment by catroot** [comment]
Ok. That kills all my data, but works.
Is there a way to rejoin a dead node without lost anything?

**Comment by catroot** [comment]
Replaying the trick kills dgraph again.
version 1.0.2 right?

**Comment by janardhan1993** [comment]
@catroot You will loose the data when you delete p and w directory, so deleting zw directory shouldn't matter right ? 
You can just restart(without deleting any folders) and the dead node should work again.
I issue has been fixed in master, so you can get the nightly dev build to test.
`curl get.dgraph.io | bash -x nightly`

**Comment by catroot** [comment]
Thank you, @janardhan1993 It seems the bug has gone.
