### ISSUE TITLE
Dgraph server panics when doing a Ctrl + C and when Zero is not available.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#2061]
```
2018/01/30 10:56:23 groups.go:653: WARNING: We don't have address of any dgraphzero server.
2018/01/30 10:56:23 groups.go:434: WARNING: We don't have address of any dgraphzero server.
2018/01/30 10:56:24 groups.go:653: WARNING: We don't have address of any dgraphzero server.
2018/01/30 10:56:24 groups.go:434: WARNING: We don't have address of any dgraphzero server.
^Cpanic: send on closed channel

goroutine 18 [running]:
os/signal.process(0x1a080e0, 0xc44b3595a0)
	/usr/local/go/src/os/signal/signal.go:221 +0x169
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x5c
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41
```

**Comment by janardhan1993** [comment]
Fixed in master.
