### ISSUE TITLE
Node can incorrectly start as a new node even though it was part of the cluster.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#2072]
https://discuss.dgraph.io/t/unable-to-run-dgraph-in-a-multi-node-kubernetes-cluster/2147/39

From the discussion above, if a node became part of the cluster but crashed before writing Hard State or Snapshot to WAL it would start as a new node which is not correct. This is a problem because the cluster cannot get into a healthy state.

**Comment by jzhu077** [comment]
@pawanrawal has this been investigated? I ran into the similar issue again. 
I ran a rolling update that applies the CPU resource request on the existing dgraph cluster(working). 
This time 2 dgraph servers of group 6 are in crashing loop.

server-15
```
 2018/02/07 21:55:15 pool.go:118: == CONNECT ==> Setting dgraph-server-26.dgraph-server.default.svc.cluster.local:7090
2018/02/07 21:55:15 pool.go:118: == CONNECT ==> Setting dgraph-server-1.dgraph-server.default.svc.cluster.local:7090
2018/02/07 21:55:15 pool.go:118: == CONNECT ==> Setting dgraph-server-2.dgraph-server.default.svc.cluster.local:7090
2018/02/07 21:55:15 pool.go:118: == CONNECT ==> Setting dgraph-server-0.dgraph-server.default.svc.cluster.local:7090
2018/02/07 21:55:15 pool.go:118: == CONNECT ==> Setting dgraph-zero-4.dgraph-zero.default.svc.cluster.local:5080
2018/02/07 21:55:15 pool.go:118: == CONNECT ==> Setting dgraph-zero-1.dgraph-zero.default.svc.cluster.local:5080
2018/02/07 21:55:15 pool.go:118: == CONNECT ==> Setting dgraph-zero-2.dgraph-zero.default.svc.cluster.local:5080
2018/02/07 21:55:15 pool.go:118: == CONNECT ==> Setting dgraph-zero-3.dgraph-zero.default.svc.cluster.local:5080
2018/02/07 21:55:15 draft.go:140: Node ID: 25 with GroupID: 6
2018/02/07 21:55:15 node.go:231: Found Snapshot, Metadata: {ConfState:{Nodes:[25 26 27] XXX_unrecognized:[]} Index:119595 Term:26 XXX_unrecognized:[]}
2018/02/07 21:55:15 node.go:246: Found hardstate: {Term:41 Vote:25 Commit:119601 XXX_unrecognized:[]}
2018/02/07 21:55:15 node.go:258: Group 6 found 6 entries
2018/02/07 21:55:15 draft.go:661: Restarting node for group: 6
2018/02/07 21:55:15 raft.go:567: INFO: 19 became follower at term 41
2018/02/07 21:55:15 raft.go:315: INFO: newRaft 19 [peers: [19,1a,1b], term: 41, commit: 119601, applied: 119595, lastindex: 119601, lastterm: 41]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x1000a96]

goroutine 865 [running]:
github.com/dgraph-io/dgraph/posting.getNew(0xc427b07560, 0x17, 0x17, 0xc42018a1b8, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/mvcc.go:470 +0x286
github.com/dgraph-io/dgraph/posting.Get(0xc427b07560, 0x17, 0x17, 0xc427b07560)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/lists.go:253 +0xca
github.com/dgraph-io/dgraph/worker.runMutation(0x1a16000, 0xc426570180, 0xc445e16000, 0xc445e140f0, 0x124cfa0, 0xc445e3a010)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/mutation.go:80 +0x231
github.com/dgraph-io/dgraph/worker.(*node).processMutation(0xc4201c22a0, 0xc445e1e020, 0x1, 0x0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:279 +0x154
github.com/dgraph-io/dgraph/worker.(*scheduler).processTasks(0xc445598b40)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/scheduler.go:65 +0x6b
created by github.com/dgraph-io/dgraph/worker.(*scheduler).init
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/scheduler.go:56 +0xe9
```

server 16
```
2018/02/07 21:52:28 draft.go:140: Node ID: 26 with GroupID: 6
2018/02/07 21:52:28 node.go:231: Found Snapshot, Metadata: {ConfState:{Nodes:[25 26 27] XXX_unrecognized:[]} Index:119595 Term:26 XXX_unrecognized:[]}
2018/02/07 21:52:28 node.go:246: Found hardstate: {Term:24213 Vote:26 Commit:119601 XXX_unrecognized:[]}
2018/02/07 21:52:28 node.go:258: Group 6 found 8 entries
2018/02/07 21:52:28 draft.go:661: Restarting node for group: 6
2018/02/07 21:52:28 raft.go:567: INFO: 1a became follower at term 24213
2018/02/07 21:52:28 raft.go:315: INFO: newRaft 1a [peers: [19,1a,1b], term: 24213, commit: 119601, applied: 119595, lastindex: 119603, lastterm: 41]
2018/02/07 21:52:30 raft.go:749: INFO: 1a is starting a new election at term 24213
2018/02/07 21:52:30 raft.go:580: INFO: 1a became candidate at term 24214
2018/02/07 21:52:30 raft.go:664: INFO: 1a received MsgVoteResp from 1a at term 24214
2018/02/07 21:52:30 raft.go:651: INFO: 1a [logterm: 41, index: 119603] sent MsgVote request to 1b at term 24214
2018/02/07 21:52:30 raft.go:651: INFO: 1a [logterm: 41, index: 119603] sent MsgVote request to 19 at term 24214
2018/02/07 21:52:30 node.go:315: No healthy connection found to node Id: 25, err: Unhealthy connection
2018/02/07 21:52:30 node.go:315: No healthy connection found to node Id: 27, err: Unhealthy connection
2018/02/07 21:52:34 raft.go:749: INFO: 1a is starting a new election at term 24214
2018/02/07 21:52:34 raft.go:580: INFO: 1a became candidate at term 24215
2018/02/07 21:52:34 raft.go:664: INFO: 1a received MsgVoteResp from 1a at term 24215
2018/02/07 21:52:34 raft.go:651: INFO: 1a [logterm: 41, index: 119603] sent MsgVote request to 19 at term 24215
2018/02/07 21:52:34 raft.go:651: INFO: 1a [logterm: 41, index: 119603] sent MsgVote request to 1b at term 24215
2018/02/07 21:52:37 raft.go:749: INFO: 1a is starting a new election at term 24215
2018/02/07 21:52:37 raft.go:580: INFO: 1a became candidate at term 24216
2018/02/07 21:52:37 raft.go:664: INFO: 1a received MsgVoteResp from 1a at term 24216
2018/02/07 21:52:37 raft.go:651: INFO: 1a [logterm: 41, index: 119603] sent MsgVote request to 19 at term 24216
2018/02/07 21:52:37 raft.go:651: INFO: 1a [logterm: 41, index: 119603] sent MsgVote request to 1b at term 24216
2018/02/07 21:52:38 pool.go:168: Echo error from dgraph-server-24.dgraph-server.default.svc.cluster.local:7090. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/07 21:52:38 pool.go:168: Echo error from dgraph-server-25.dgraph-server.default.svc.cluster.local:7090. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/07 21:52:38 pool.go:168: Echo error from dgraph-server-26.dgraph-server.default.svc.cluster.local:7090. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/07 21:52:38 pool.go:168: Echo error from dgraph-server-20.dgraph-server.default.svc.cluster.local:7090. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/07 21:52:38 pool.go:168: Echo error from dgraph-server-21.dgraph-server.default.svc.cluster.local:7090. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/07 21:52:38 pool.go:168: Echo error from dgraph-server-22.dgraph-server.default.svc.cluster.local:7090. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/07 21:52:38 pool.go:168: Echo error from dgraph-server-23.dgraph-server.default.svc.cluster.local:7090. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/07 21:52:38 pool.go:168: Echo error from dgraph-server-27.dgraph-server.default.svc.cluster.local:7090. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/07 21:52:38 pool.go:168: Echo error from dgraph-server-28.dgraph-server.default.svc.cluster.local:7090. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/07 21:52:38 pool.go:168: Echo error from dgraph-server-29.dgraph-server.default.svc.cluster.local:7090. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/07 21:52:38 pool.go:168: Echo error from dgraph-server-15.dgraph-server.default.svc.cluster.local:7090. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/07 21:52:38 pool.go:168: Echo error from dgraph-server-17.dgraph-server.default.svc.cluster.local:7090. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/07 21:52:39 raft.go:749: INFO: 1a is starting a new election at term 24216
2018/02/07 21:52:39 raft.go:580: INFO: 1a became candidate at term 24217
2018/02/07 21:52:39 raft.go:664: INFO: 1a received MsgVoteResp from 1a at term 24217
2018/02/07 21:52:39 raft.go:651: INFO: 1a [logterm: 41, index: 119603] sent MsgVote request to 19 at term 24217
2018/02/07 21:52:39 raft.go:651: INFO: 1a [logterm: 41, index: 119603] sent MsgVote request to 1b at term 24217
2018/02/07 21:52:42 raft.go:749: INFO: 1a is starting a new election at term 24217
````

server 17
has similar logs to server 15 

They are all belong to group 6.
Image: dgraph/dgraph:master

**Comment by pawanrawal** [comment]
Sorry, did not get a chance to investigate this yet but will do it today.

**Comment by pawanrawal** [comment]
This is a new issue by the way. Notice the server says it found a snapshot. So it did not restart as a new node. I am checking this.

```
2018/02/07 21:55:15 node.go:231: Found Snapshot, Metadata: {ConfState:{Nodes:[25 26 27] XXX_unrecognized:[]} Index:119595 Term:26 XXX_unrecognized:[]}
2018/02/07 21:55:15 node.go:246: Found hardstate: {Term:41 Vote:25 Commit:119601 XXX_unrecognized:[]}
2018/02/07 21:55:15 node.go:258: Group 6 found 6 entries
```
