### ISSUE TITLE
Zero can segfault when its being restarted

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#2154]
This can happen when Dgraph server is already running and you try to restart Zero.

```
Feb 21 13:27:05 dgraph0 dgraph[6551]: Setting up grpc listener at: 0.0.0.0:5080
Feb 21 13:27:05 dgraph0 dgraph[6551]: Setting up http listener at: 0.0.0.0:6080
Feb 21 13:27:06 dgraph0 dgraph[6551]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 21 13:27:06 dgraph0 dgraph[6551]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1126683]
Feb 21 13:27:06 dgraph0 dgraph[6551]: goroutine 101 [running]:
Feb 21 13:27:06 dgraph0 dgraph[6551]: github.com/dgraph-io/dgraph/dgraph/cmd/zero.(*node).WaitLinearizableRead(0xc4200575c0, 0x1a19f
Feb 21 13:27:06 dgraph0 dgraph[6551]:         /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/raft.go:124 +0x133
Feb 21 13:27:06 dgraph0 dgraph[6551]: github.com/dgraph-io/dgraph/dgraph/cmd/zero.(*Server).latestMembershipState(0xc4200e6a80, 0x1a
Feb 21 13:27:06 dgraph0 dgraph[6551]:         /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/zero.go:547 +0x47
Feb 21 13:27:06 dgraph0 dgraph[6551]: github.com/dgraph-io/dgraph/dgraph/cmd/zero.(*Server).Update(0xc4200e6a80, 0x1a1d8c0, 0xc42610
Feb 21 13:27:06 dgraph0 dgraph[6551]:         /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/zero.go:508 +0x192
Feb 21 13:27:06 dgraph0 dgraph[6551]: github.com/dgraph-io/dgraph/protos/intern._Zero_Update_Handler(0x12f9640, 0xc4200e6a80, 0x1a1c
Feb 21 13:27:06 dgraph0 dgraph[6551]:         /home/travis/gopath/src/github.com/dgraph-io/dgraph/protos/intern/internal.pb.go:2158 
Feb 21 13:27:06 dgraph0 dgraph[6551]: google.golang.org/grpc.(*Server).processStreamingRPC(0xc420001c80, 0x1a1d500, 0xc4203c4d80, 0x
Feb 21 13:27:06 dgraph0 dgraph[6551]:         /home/travis/gopath/src/google.golang.org/grpc/server.go:1032 +0xa3e
Feb 21 13:27:06 dgraph0 dgraph[6551]: google.golang.org/grpc.(*Server).handleStream(0xc420001c80, 0x1a1d500, 0xc4203c4d80, 0xc42009f
Feb 21 13:27:06 dgraph0 dgraph[6551]:         /home/travis/gopath/src/google.golang.org/grpc/server.go:1126 +0x14c1
```

**Comment by pawanrawal** [comment]
This was fixed as part of https://github.com/dgraph-io/dgraph/commit/94173483974c1299e2ac3122c9f3f490850be7ae.
