### ISSUE TITLE
Iterator error

### ISSUE THREAD

**Issue by tactician2** [dgraph-io/dgraph#2162]
Failure appears to be on this statement:
for it.Seek(k); it.ValidForPrefix(k); it.Next()

panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x279994]

goroutine 1 [running]:
github.com/dgraph-io/badger/skl.(*Arena).getNode(...)
        /root/go/src/github.com/dgraph-io/badger/skl/arena.go:108
github.com/dgraph-io/badger/skl.(*Skiplist).getNext(0x108cf610, 0x1091a004, 0xa, 0x2803f0)
        /root/go/src/github.com/dgraph-io/badger/skl/skl.go:184 +0x4c
github.com/dgraph-io/badger/skl.(*Skiplist).findLast(0x108cf610, 0xffffffff)
        /root/go/src/github.com/dgraph-io/badger/skl/skl.go:366 +0x5c
github.com/dgraph-io/badger/skl.(*Skiplist).Empty(0x108cf610, 0x0)
        /root/go/src/github.com/dgraph-io/badger/skl/skl.go:357 +0x1c
github.com/dgraph-io/badger.(*DB).Close(0x10916000, 0x10, 0x1)
        /root/go/src/github.com/dgraph-io/badger/db.go:338 +0xc0
panic(0x2f7690, 0x4ed0f8)
        /usr/lib/go-1.9/src/runtime/panic.go:491 +0x204
github.com/dgraph-io/badger/skl.(*Arena).getKey(...)
        /root/go/src/github.com/dgraph-io/badger/skl/arena.go:113
github.com/dgraph-io/badger/skl.(*Iterator).Key(...)
        /root/go/src/github.com/dgraph-io/badger/skl/skl.go:428
github.com/dgraph-io/badger/skl.(*UniIterator).Key(0x1ce4b238, 0xc, 0x275e28, 0x1e9ae320)
        /root/go/src/github.com/dgraph-io/badger/skl/skl.go:515 +0x30
github.com/dgraph-io/badger/y.elemHeap.Less(0x1e9b0220, 0x3, 0x8, 0x2, 0x1, 0x1)
        /root/go/src/github.com/dgraph-io/badger/y/iterator.go:122 +0x3c
github.com/dgraph-io/badger/y.(*elemHeap).Less(0x1d345530, 0x2, 0x1, 0x3358e5)
        <autogenerated>:1 +0x54
container/heap.down(0x4c3728, 0x1d345530, 0x0, 0x3, 0x287274)
        /usr/lib/go-1.9/src/container/heap/heap.go:111 +0xd8
container/heap.Fix(0x4c3728, 0x1d345530, 0x0)
        /usr/lib/go-1.9/src/container/heap/heap.go:87 +0x48
github.com/dgraph-io/badger/y.(*MergeIterator).Next(0x1d345530)
        /root/go/src/github.com/dgraph-io/badger/y/iterator.go:225 +0xb8
github.com/dgraph-io/badger.(*Iterator).parseItem(0x10855740, 0x10835d01)
        /root/go/src/github.com/dgraph-io/badger/iterator.go:396 +0x878
github.com/dgraph-io/badger.(*Iterator).Next(0x10855740)
        /root/go/src/github.com/dgraph-io/badger/iterator.go:333 +0x130
main.main()
        /root/go/src/15-times-d/15-times-d.go:262 +0x908
You have new mail in /var/mail/root
root@scw-f48f5c:~#

**Comment by tactician2** [comment]
Found a way around it
