### ISSUE TITLE
Segmentation Fault in store package

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#232]
**Rocksdb installed: 4.9.3**
$ go version                                                                                                                                                                        ~
go version go1.7.1 linux/amd64

```
$ go build . && ./dgraph                                                                                                                                                                                        ~/go/src/github.com/dgraph-io/dgraph/cmd/dgraph
2016/09/22 20:01:25 main.go:493: num_cpu: 4. prev_maxprocs: 4. Set max procs to num cpus
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1000000012 pc=0x7f00ecafa944]

runtime stack:
runtime.throw(0x8e4494, 0x2a)
	/usr/lib/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x7de400, 0xc42015bda0, 0xc400000000)
	/usr/lib/go/src/runtime/cgocall.go:131 +0x110 fp=0xc42015bd70 sp=0xc42015bd30
github.com/dgraph-io/dgraph/rdb._Cfunc_rdb_options_set_block_based_table_factory(0x2f102b0, 0x2f15930)
	github.com/dgraph-io/dgraph/rdb/_obj/_cgo_gotypes.go:593 +0x41 fp=0xc42015bda0 sp=0xc42015bd70
github.com/dgraph-io/dgraph/rdb.(*Options).SetBlockBasedTableFactory(0xc42013b730, 0xc420183840)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/rdb/options.go:34 +0xfc fp=0xc42015bdf8 sp=0xc42015bda0
github.com/dgraph-io/dgraph/store.(*Store).setOpts(0xc420153da0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/store/store.go:40 +0x81 fp=0xc42015be20 sp=0xc42015bdf8
github.com/dgraph-io/dgraph/store.NewStore(0x8ceb2c, 0x1, 0x41a189, 0xc420064058, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/store/store.go:60 +0x6b fp=0xc42015be78 sp=0xc42015be20
main.main()
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:563 +0x68 fp=0xc42015bf38 sp=0xc42015be78
runtime.main()
	/usr/lib/go/src/runtime/proc.go:183 +0x1f4 fp=0xc42015bf90 sp=0xc42015bf38
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42015bf98 sp=0xc42015bf90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 34 [chan receive]:
github.com/dgraph-io/dgraph/query.release()
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/query/query.go:357 +0x55
created by github.com/dgraph-io/dgraph/query.init.1
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/query/query.go:372 +0x64
```

**Comment by jchiu0** [comment]
I used to have this problem on my macbook. It might be because your RocksDB is not in place? The problem somehow went away after I did "make shared_lib" and "sudo make install" and then "go install" everything again. Sometimes, when you go install, it might not re-link things correctly. To fix that, you could go to rdbc.cc. Type some comments to force a recompile. Or you can do a "go install -a"..

**Comment by manishrjain** [comment]
Adding a comment in rdbcc.cc actually worked! Forced a relink, and now dgraph binary runs as expected.

@jchiu0: Thanks for the tip. Once you add this in troubleshooting section in the beginners guide, you can feel free to close this issue.

**Comment by jchiu0** [comment]
No worries :) It took me a while and some luck to discover this as well.
