### ISSUE TITLE
Error in zero server

### ISSUE THREAD

**Issue by sameervitian** [dgraph-io/dgraph#2327]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
What version of Dgraph are you using?
Dgraph version : v1.0.4-dev
Commit SHA-1 : 807976c
Commit timestamp : 2018-03-22 14:55:24 +1100
Branch : HEAD

- Have you tried reproducing the issue with latest release?
I am already using nightly build as suggested in #2252

- What is the hardware spec (RAM, OS)?
3 dgraph data server node with ubuntu 14.04 / 8 core 32GB
3 node for zero with ubuntu 14.04/ 1 core 2GB

Following errors was seen on zero server and it is down and not restarting. For more detail pls see issue - https://github.com/dgraph-io/dgraph/issues/2311

```
2018/04/06 10:57:06 node.go:232: Found Snapshot, Metadata: {ConfState:{Nodes:[1 2 3] XXX_unrecognized:[]} Index:29925435 Term:1378 XXX_unrecognized:[]}
2018/04/06 10:57:06 node.go:247: Found hardstate: {Term:1420 Vote:3 Commit:29935537 XXX_unrecognized:[]}
2018/04/06 10:57:06 node.go:259: Group 0 found 971 entries
raft2018/04/06 10:57:06 missing log entry [last: 29925435, append at: 29934568]
panic: missing log entry [last: 29925435, append at: 29934568]

goroutine 1 [running]:
log.(*Logger).Panicf(0xc420067090, 0x1376658, 0x2b, 0xc42d5c6aa0, 0x2, 0x2)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/log/log.go:219 +0xdb
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*DefaultLogger).Panicf(0x1aeb700, 0x1376658, 0x2b, 0xc42d5c6aa0, 0x2, 0x2)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/logger.go:121 +0x60
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*MemoryStorage).Append(0xc4203160e0, 0xc42d5ac000, 0x3cb, 0x471, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/storage.go:267 +0x641
github.com/dgraph-io/dgraph/conn.(*Node).InitFromWal(0xc420181ad0, 0xc42003afb0, 0xc24280, 0xc420518514, 0xc4205af6b8, 0xc42d540500)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/conn/node.go:263 +0x523
github.com/dgraph-io/dgraph/dgraph/cmd/zero.(*node).initAndStartNode(0xc4203ccea0, 0xc42003afb0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/raft.go:408 +0x7e
github.com/dgraph-io/dgraph/dgraph/cmd/zero.run()
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/run.go:195 +0x83d
github.com/dgraph-io/dgraph/dgraph/cmd/zero.init.0.func1(0xc42024ab40, 0xc420249120, 0x0, 0x2)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/run.go:69 +0x52
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute(0xc42024ab40, 0xc4202490e0, 0x2, 0x2, 0xc42024ab40, 0xc4202490e0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1a60c00, 0xc420131ee8, 0x8f9f90, 0x1a682d0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute(0x1a60c00, 0x1a682d0, 0x1522bca17a874293)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/dgraph-io/dgraph/dgraph/cmd.Execute()
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:52 +0x31
main.main()
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/main.go:34 +0xad
2018/04/06 10:57:08 zero.go:333: Got connection request: id:3 addr:"172.21.253.104:7080"
2018/04/06 10:57:08 pool.go:118: == CONNECT ==> Setting 172.21.253.104:7080
2018/04/06 10:57:08 zero.go:426: Connected
2018/04/06 10:57:08 node.go:232: Found Snapshot, Metadata: {ConfState:{Nodes:[1 2 3] XXX_unrecognized:[]} Index:29925435 Term:1378 XXX_unrecognized:[]}
2018/04/06 10:57:08 node.go:247: Found hardstate: {Term:1420 Vote:3 Commit:29935537 XXX_unrecognized:[]}
2018/04/06 10:57:08 node.go:259: Group 0 found 971 entries
raft2018/04/06 10:57:08 missing log entry [last: 29925435, append at: 29934568]
panic: missing log entry [last: 29925435, append at: 29934568]
```

**Comment by pawanrawal** [comment]
While I am checking this, you can remove the zero node using the `/removeNode` endpoint and bring another one up.

**Comment by pawanrawal** [comment]
Had a look at this, somehow entries after a snapshot are missing which is weird because we update the snapshot key and delete old entries as part of the same transaction in `StoreSnapshot` method of `raftwal/wal.go`.

As can be seen from the logs, last snapshot is at index `29925435`, whereas we have entries from `29943568`. Logs from the Zero server would have helped to show if we did try to write a snapshot at a later term and index. I will be making a change where logs would be stored to a file which should make it easier to debug future issues.

**Comment by pawanrawal** [comment]
Modified badger value log replay to print all snapshot keys from all files and I can clearly see that we wrote an older snapshot key.
```
...
2018/04/17 12:05:12 db.go:122: snap: {ConfState:{Nodes:[1 2 3] XXX_unrecognized:[]} Index:26468466 Term:633 XXX_unrecognized:[]}
2018/04/17 12:05:12 db.go:122: snap: {ConfState:{Nodes:[1 2 3] XXX_unrecognized:[]} Index:26765650 Term:633 XXX_unrecognized:[]}
2018/04/17 12:05:12 db.go:122: snap: {ConfState:{Nodes:[1 2 3] XXX_unrecognized:[]} Index:29934567 Term:1382 XXX_unrecognized:[]}
2018/04/17 12:05:19 db.go:122: snap: {ConfState:{Nodes:[1 2 3] XXX_unrecognized:[]} Index:29925435 Term:1378 XXX_unrecognized:[]}
```

This explains the issue, since we had already deleted entries before `29934567` on writing an earlier snapshot, we get this error. I will try to find in what circumstances could this happen.

**Comment by sameervitian** [comment]
seems the distributed setup isn't production ready.

**Comment by pawanrawal** [comment]
Hey @sameervitian, it it possible for you to share `zw` directory from other Zero instances as well? Logs would have helped but since we don't have them, data directory would be useful.

**Comment by sameervitian** [comment]
unfortunately, I decommissioned the instance and lost those log and data directory.

**Comment by manishrjain** [comment]
The MemoryStore WAL has been replaced with Badger based WAL storage. It correctly sets the entries before writing snapshot, so we shouldn't see this again.

Feel free to reopen if you do.
