### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by aditya-pr** [dgraph-io/dgraph#2474]
- What version of Dgraph are you using?
v1.0.6

- Have you tried reproducing the issue with latest release?
using latest

- What is the hardware spec (RAM, OS)?
```yaml
         requests:
            memory: "5120Mi"
            cpu: "1000m"
          limits:
            memory: "6144Mi"
            cpu: "1250m"
```
OS: ubuntu:16.04 (docker base image)
- Steps to reproduce the issue (command/config used to run Dgraph).
Same as [here](https://github.com/dgraph-io/dgraph/blob/db4a40fa8e4225ed2b563dd3f10bb73683d750b4/contrib/config/kubernetes/dgraph-single.yaml).

- Expected behaviour and actual result.
Dgraph server crashes with `invalid memory address or nil pointer dereference`:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11beb06]

goroutine 897514 [running]:
github.com/dgraph-io/dgraph/edgraph.(*Server).Mutate(0x1bb9d40, 0x1b1fc80, 0xc4366b8630, 0xc447659b80, 0xc451e8cb20, 0x1b14580, 0xc435238be0)
	/home/aditya/go/src/github.com/dgraph-io/dgraph/edgraph/server.go:359 +0x5d6
github.com/dgraph-io/dgo/protos/api._Dgraph_Mutate_Handler(0x13171a0, 0x1bb9d40, 0x1b1fc80, 0xc4366b8630, 0xc453092230, 0x0, 0x0, 0x0, 0xc450446000, 0x7fe4d0389890)
	/home/aditya/go/src/github.com/dgraph-io/dgo/protos/api/api.pb.go:1176 +0x276
google.golang.org/grpc.(*Server).processUnaryRPC(0xc4201f82c0, 0x1b23320, 0xc436d7fe00, 0xc44e15c8c0, 0xc428f2de90, 0x1b08918, 0x0, 0x0, 0x0)
	/home/aditya/go/src/google.golang.org/grpc/server.go:923 +0x92d
google.golang.org/grpc.(*Server).handleStream(0xc4201f82c0, 0x1b23320, 0xc436d7fe00, 0xc44e15c8c0, 0x0)
	/home/aditya/go/src/google.golang.org/grpc/server.go:1148 +0x1528
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc433d34020, 0xc4201f82c0, 0x1b23320, 0xc436d7fe00, 0xc44e15c8c0)
	/home/aditya/go/src/google.golang.org/grpc/server.go:637 +0x9f
```

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/dgraph/pull/2493 should fix this.
