### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#2706]
I have 3 m5.large (8 ram) machines cluster with replication=3
running dgraph server(s) with lru_mb=1024

after loading ~20m edges got this error on 2 of 3 nodes:
```
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x1366a92, 0x16)
/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc1b8000000, 0x4000000, 0x1d9cf18)
/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x1d83720, 0x4000000, 0x7f870af54990, 0x7f8772a3cd00)
/usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x1d83720, 0x22f, 0x0)
/usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x1d83720, 0x22f, 0x1d9cf28, 0x20305100000000)
/usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x1d83720, 0x22f, 0x830101, 0x7f8717376b00)
/usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
/usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x1d83720, 0x22f, 0x7f8772010101, 0x839055)
/usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x45d7f9, 0x870101, 0x7f87ad236b00)
/usr/local/go/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
/usr/local/go/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
/usr/local/go/src/runtime/proc.go:1229
goroutine 230 [running]:
runtime.systemstack_switch()
/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc187dacbf8 sp=0xc187dacbf0 pc=0x87d930
runtime.mallocgc(0x45d7f9, 0x11fc720, 0x1, 0x0)
/usr/local/go/src/runtime/malloc.go:913 +0x896 fp=0xc187dacc98 sp=0xc187dacbf8 pc=0x82ee96
runtime.makeslice(0x11fc720, 0x45d7f9, 0x45d7f9, 0x5, 0x5, 0x0)
/usr/local/go/src/runtime/slice.go:70 +0x77 fp=0xc187daccc8 sp=0xc187dacc98 pc=0x866887
google.golang.org/grpc.(*parser).recvMsg(0xc17678ae60, 0x100000000, 0x915bba, 0x915bba, 0x12f9b80, 0xc1084b93a0, 0x0, 0x0)
/ext-go/1/src/google.golang.org/grpc/rpc_util.go:470 +0xd3 fp=0xc187dacd88 sp=0xc187daccc8 pc=0xe4c773
google.golang.org/grpc.recv(0xc17678ae60, 0x7f87ad15d080, 0x1d9b180, 0xc18acc1d00, 0x0, 0x0, 0x12f9b80, 0xc0d0189700, 0x100000000, 0x0, ...)
/ext-go/1/src/google.golang.org/grpc/rpc_util.go:578 +0x4d fp=0xc187dace70 sp=0xc187dacd88 pc=0xe4d31d
google.golang.org/grpc.(*csAttempt).recvMsg(0xc095cb8dd0, 0x12f9b80, 0xc0d0189700, 0x0, 0x0)
/ext-go/1/src/google.golang.org/grpc/stream.go:542 +0x131 fp=0xc187dacf18 sp=0xc187dace70 pc=0xe59fc1
google.golang.org/grpc.(*clientStream).RecvMsg(0xc115b7fc00, 0x12f9b80, 0xc0d0189700, 0x0, 0x0)
/ext-go/1/src/google.golang.org/grpc/stream.go:408 +0x43 fp=0xc187dacf50 sp=0xc187dacf18 pc=0xe593e3
github.com/dgraph-io/dgraph/protos/pb.(*workerStreamSnapshotClient).Recv(0xc0304a8dc0, 0xc187dad014, 0x3, 0x0)
/ext-go/1/src/github.com/dgraph-io/dgraph/protos/pb/pb.pb.go:3856 +0x62 fp=0xc187dacf90 sp=0xc187dacf50 pc=0xe92b42
github.com/dgraph-io/dgraph/worker.(*node).populateShard(0xc000030e10, 0xc0004da700, 0xc00011b0e0, 0x0, 0xc000000000, 0xc0001f9810)
/ext-go/1/src/github.com/dgraph-io/dgraph/worker/predicate.go:126 +0x227 fp=0xc187dad128 sp=0xc187dacf90 pc=0x105b6f7
github.com/dgraph-io/dgraph/worker.(*node).retrieveSnapshot(0xc000030e10, 0x1abecbc, 0xc0001f9810)
/ext-go/1/src/github.com/dgraph-io/dgraph/worker/draft.go:551 +0x75 fp=0xc187dad198 sp=0xc187dad128 pc=0x104be25
github.com/dgraph-io/dgraph/worker.(*node).retrieveSnapshot-fm(0x1d7d3a0, 0xc000000000)
/ext-go/1/src/github.com/dgraph-io/dgraph/worker/draft.go:676 +0x2a fp=0xc187dad1c0 sp=0xc187dad198 pc=0x107e21a
github.com/dgraph-io/dgraph/worker.(*node).retryUntilSuccess(0xc000030e10, 0xc187dad3d8, 0x5f5e100)
/ext-go/1/src/github.com/dgraph-io/dgraph/worker/draft.go:932 +0x82 fp=0xc187dad208 sp=0xc187dad1c0 pc=0x104f322
github.com/dgraph-io/dgraph/worker.(*node).Run(0xc000030e10)
/ext-go/1/src/github.com/dgraph-io/dgraph/worker/draft.go:676 +0x1269 fp=0xc187dadfd8 sp=0xc187dad208 pc=0x104d429
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc187dadfe0 sp=0xc187dadfd8 pc=0x87fa11
created by github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode
/ext-go/1/src/github.com/dgraph-io/dgraph/worker/draft.go:1004 +0x50b
goroutine 1 [semacquire, 4023 minutes]:
sync.runtime_Semacquire(0xc000484548)
/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc000484540)
/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/dgraph-io/dgraph/dgraph/cmd/server.setupServer()
/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/server/run.go:283 +0x663
github.com/dgraph-io/dgraph/dgraph/cmd/server.run()
/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/server/run.go:375 +0x954
github.com/dgraph-io/dgraph/dgraph/cmd/server.init.0.func1(0xc00018dd40, 0xc00032d140, 0x0, 0x3)
/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/server/run.go:55 +0x52
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute(0xc00018dd40, 0xc00032d0b0, 0x3, 0x3, 0xc00018dd40, 0xc00032d0b0)
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702 +0x2d3
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1cf8f80, 0x4, 0x0, 0x0)
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute(0x1cf8f80, 0x853fdd, 0x1d01808)
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/dgraph-io/dgraph/dgraph/cmd.Execute()
/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:47 +0x36
main.main()
/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/main.go:24 +0x88
goroutine 5 [chan receive, 1 minutes]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1d7d3a0)
/go/src/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
/go/src/github.com/golang/glog/glog.go:410 +0x203
goroutine 19 [syscall, 4023 minutes]:
os/signal.signal_recv(0x139daf8)
/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
goroutine 20 [chan receive]:
github.com/dgraph-io/dgraph/x.init.1.func1()
/ext-go/1/src/github.com/dgraph-io/dgraph/x/metrics.go:87 +0x7e
created by github.com/dgraph-io/dgraph/x.init.1
/ext-go/1/src/github.com/dgraph-io/dgraph/x/metrics.go:82 +0x52c
goroutine 148 [chan receive]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.(*WaterMark).process(0xc000116518)
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/watermark.go:125 +0x15b
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.(*WaterMark).Init
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/watermark.go:54 +0xc1
goroutine 149 [select, 1 minutes]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).updateSize(0xc000053180, 0xc0001180c0)
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:928 +0x125
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.Open
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:267 +0x7d7
goroutine 178 [runnable]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelsController).runWorker(0xc000114070, 0xc000118040)
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:248 +0x151
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelsController).startCompact
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:233 +0x82
goroutine 179 [select]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelsController).runWorker(0xc000114070, 0xc000118040)
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:248 +0x151
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelsController).startCompact
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:233 +0x82
goroutine 180 [select]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelsController).runWorker(0xc000114070, 0xc000118040)
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:248 +0x151
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelsController).startCompact
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:233 +0x82
goroutine 181 [chan receive, 4 minutes]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).flushMemtable(0xc000053180, 0xc000118060, 0x0, 0x0)
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:806 +0xd3
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.Open
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:280 +0xf3e
goroutine 183 [select]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).doWrites(0xc000053180, 0xc0001185a0)
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:670 +0x404
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.Open
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:325 +0xc81
goroutine 184 [chan receive, 4023 minutes]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).waitOnGC(0xc0000532c8, 0xc0001185c0)
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:1190 +0x61
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.Open
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:328 +0xcde
goroutine 185 [chan receive]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.(*WaterMark).process(0xc000117d78)
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/watermark.go:125 +0x15b
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.(*WaterMark).Init
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/watermark.go:54 +0xc1
goroutine 186 [select, 1 minutes]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).updateSize(0xc0004da700, 0xc0001186c0)
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:928 +0x125
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.Open
/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:267 +0x7d7
goroutine 353104602 [semacquire]:
sync.runtime_Semacquire(0xc14e6ddfc8)
/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc14e6ddfc0)
/usr/local/go/src/sync/waitgroup.go:130 +0x64

(another 4000 lines)
```

**Comment by danielmai** [comment]
It's hard to say what happened without more info (Dgraph version, how the data was loaded, etc.).

I see you started a discussion at https://discuss.dgraph.io/t/out-of-memory-error/3519. Let's continue the conversation there.
