### ISSUE TITLE
Query crashes dgraph

### ISSUE THREAD

**Issue by AriFunFarim** [dgraph-io/dgraph#2766]
**- What version of Dgraph are you using?**
v1.0.10 and v1.0.11rc3

**- Have you tried reproducing the issue with latest release?**
yes

**- What is the hardware spec (RAM, OS)?**
oVirt VM, CentOS7, 16GB RAM, 4 CPUs, dgraph running in docker.

**- Steps to reproduce the issue (command/config used to run Dgraph).**
This is the query:
```
{
  getAssets(func: eq(xid, "61f6beb6-41d9-45cf-a350-e47f66ece7fe")) {
    name
    uid
    xid
    assets: parent_of (orderasc: isDirectory, orderasc: name , offset: 0, first: 60)
      {
        name
        isDirectory
        xid
        uid
     } 
  }
}
```
**- Expected behaviour and actual result.**
We expect dgraph does not crash, but it does. 
Based on the source and some tests we found out the following:
Our result of the query is:
```
Found 52 nodes and 51 edges
```
Everything is OK, if "first" >= the number of edges, otherwise dgraph crashes.

**Here is the log entry:**
```
panic: interface conversion: interface {} is nil, not string
goroutine 1002 [running]:
github.com/dgraph-io/dgraph/types.equal(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x70)
        /ext-go/1/src/github.com/dgraph-io/dgraph/types/sort.go:187 +0x2a0
github.com/dgraph-io/dgraph/types.Equal(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x833248, 0xc00bf0cb40, 0x125e620)
        /ext-go/1/src/github.com/dgraph-io/dgraph/types/sort.go:172 +0x6c
github.com/dgraph-io/dgraph/worker.paginate(0xc00bf02840, 0xc00bf0ca80, 0xc000105500, 0x70, 0x70, 0xc000105500, 0x70, 0x70, 0x0)
        /ext-go/1/src/github.com/dgraph-io/dgraph/worker/sort.go:589 +0x114
github.com/dgraph-io/dgraph/worker.sortWithoutIndex(0x1417ce0, 0xc00befeec0, 0xc00bf02840, 0x0)
        /ext-go/1/src/github.com/dgraph-io/dgraph/worker/sort.go:128 +0x3ac
github.com/dgraph-io/dgraph/worker.processSort.func1(0x1417da0, 0xc00befc2a0, 0xc00bf028a0, 0x1417ce0, 0xc00befeec0, 0xc00bf02840)
        /ext-go/1/src/github.com/dgraph-io/dgraph/worker/sort.go:395 +0x1b8
created by github.com/dgraph-io/dgraph/worker.processSort
        /ext-go/1/src/github.com/dgraph-io/dgraph/worker/sort.go:387 +0x345
I1121 13:14:45.931584       1 init.go:80]
```

**Something about the end-condition may be wrong in worker/sort.go line 587:**
```
// For multiple sort, we need to take all equal values at the end. So we update end.
for len(ts.Order) > 1 && end < len(dest.Uids) {
	eq, err := types.Equal(vals[end-1], vals[end])
```
**But then in types/sort.go line 187:**
```
case StringID, DefaultID:
	return (a.Value.(string)) == (b.Value.(string))
```
**Obviously b.Value is null, while b.TiD has some value**

Also, i would like to suggest that you reconsider the concept of error handling.
Imagine one of the big SQL databases crashing at a bank because of a query. Unimaginable.
We can live with bugs, but not with a DB that crashes immediately with every little bug.

**Comment by gitlw** [comment]
Thanks @AriFunFarim for reporting this bug and the root cause analysis.
We'll make sure to handle nil values affecting this case, and also check if type conversion affects other cases.
