### ISSUE TITLE
panic in dgraph-io/dgraph/query/query.go:1433

### ISSUE THREAD

**Issue by relunctance** [dgraph-io/dgraph#2782]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

Dgraph version   : v1.0.11-rc3-4-g701e18d0
Commit SHA-1     : 701e18d0
Commit timestamp : 2018-11-21 23:56:55 -0800
Branch           : master

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
go1.9.2 linux/amd64
Linux dgraph.kill.docker 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 18.04.1 LTS \n \l

- Steps to reproduce the issue (command/config used to run Dgraph).
cat zero_config.json 
```
{

        "bindall":true,
        "log_dir":"/dgraph/logs",
        "wal":"/dgraph/zw",
        "port_offset":0
}
```

cat alpha_config.json 
```json
{
    "alsologtostderr":false,
        "lru_mb" : 4096,
        "bindall":true,
        "wal":"/dgraph/w",
        "postings":"/dgraph/p",
    "debugmode":false,
        "port_offset":0,
    "whitelist":"172.17.0.1:192.168.1.1",
    "v":1,
    "log_dir":"/dgraph/logs",
        "zero": "0.0.0.0:5080"
}
```

- replay step
data from : https://tour.dgraph.io/moredata/1/
url: http://127.0.0.1:8080/query?debug=true

Request Payload
```
{
  var(func: has(<actor.film>)) {
    countValues as count(<actor.film>)
  }

  nodeCount(func: has(<actor.film>)) {
    nodeCount: count(uid)
  }

  stats() {
    totalCount: sum(val(countValues))
    avgCount: avg(val(countValues))
  }
}
```

- Expected behaviour and actual result.

```
2018/11/27 08:52:15 http: panic serving 10.18.32.38:50411: runtime error: index out of range
goroutine 3388222 [running]:
net/http.(*conn).serve.func1(0xc42c48a780)
        /home/gaoqilin/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x148be40, 0x1db4190)
        /home/gaoqilin/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/dgraph-io/dgraph/query.(*SubGraph).populateUidValVar(0xc42038d080, 0xc48e1a0210, 0xc44bbb16c0, 0x1, 0x1, 0x1, 0x1)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1433 +0xcc3
github.com/dgraph-io/dgraph/query.(*SubGraph).updateVars(0xc42038d080, 0xc48e1a0210, 0xc44bbb16a8, 0x1, 0x1, 0x0, 0x7f0999bc2970)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1404 +0x106
github.com/dgraph-io/dgraph/query.(*SubGraph).populateVarMap(0xc42038d080, 0xc48e1a0210, 0xc44bbb16a8, 0x1, 0x1, 0xc44bbb16a8, 0x0)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1393 +0x59f
github.com/dgraph-io/dgraph/query.(*SubGraph).populateVarMap(0xc42038cdc0, 0xc48e1a0210, 0xc44bbb16a8, 0x1, 0x1, 0x0, 0xc42b917b60)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1346 +0x1ee
github.com/dgraph-io/dgraph/query.(*QueryRequest).ProcessQuery(0xc42b6c9ad8, 0x1de30c0, 0xc48e356480, 0x1, 0x1)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/query/query.go:2561 +0xdc6
github.com/dgraph-io/dgraph/query.(*QueryRequest).Process(0xc42b6c9ad8, 0x1de30c0, 0xc48e356480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/query/query.go:2610 +0x68
github.com/dgraph-io/dgraph/edgraph.(*Server).Query(0xc42ad0fb98, 0x1de30c0, 0xc48e356480, 0xc43e603950, 0xc42b6064e0, 0x0, 0x0)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/edgraph/server.go:494 +0x673
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.queryHandler(0x1de2000, 0xc42ae161c0, 0xc4c39a0200)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/http.go:107 +0x354
net/http.HandlerFunc.ServeHTTP(0x160bc78, 0x1de2000, 0xc42ae161c0, 0xc4c39a0200)
        /home/gaoqilin/usr/local/go/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0x1e816a0, 0x1de2000, 0xc42ae161c0, 0xc4c39a0200)
        /home/gaoqilin/usr/local/go/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc420242000, 0x1de2000, 0xc42ae161c0, 0xc4c39a0200)
        /home/gaoqilin/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42c48a780, 0x1de3000, 0xc467481780)
        /home/gaoqilin/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /home/gaoqilin/usr/local/go/src/net/http/server.go:2720 +0x288
```

**Comment by manishrjain** [comment]
Just submitted this commit: https://github.com/dgraph-io/dgraph/commit/290028dc48e419cc9ea9473364b2c6b6e8e0f5f2 which would fix this bug.
