### ISSUE TITLE
Node crashed due to badger error when moveing preidcate

### ISSUE THREAD

**Issue by chuerxiao** [dgraph-io/dgraph#2793]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
   v1.0.10 
   compile from source code
- Have you tried reproducing the issue with latest release?
     v1.0.10 is the latest release
- What is the hardware spec (RAM, OS)?
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
memory 256GB 
cores 80

- Steps to reproduce the issue (command/config used to run Dgraph).

  ```bash
  ~/dgraph/bin/dgraph zero -v 100 --telemetry=false --replicas=3 &    
  //pid=75028
   ```
  ```bash
  ~/dgraph/bin/dgraph alpha --lru_mb=1024 --zero=localhost:5080 --expose_trace=true  --v 100 &
   //pid=75438
   ```
   ```bash
  ~/dgraph/bin/dgraph alpha --lru_mb=1024 --zero=localhost:5080 --expose_trace=true  --v 100 -o 80& 
   //pid=75949
    ```
   ```bash
  ~/dgraph/bin/dgraph alpha --lru_mb=1024 --zero=localhost:5080 --expose_trace=true  --v 100 -o 81&
   //pid=76061
   ```

- Expected behaviour and actual result.

**75028**

```bash
I1129 11:08:30.098851   75028 assign.go:79] Got lease request for txn: true. Num: val:1
I1129 11:08:30.136358   75028 assign.go:79] Got lease request for txn: true. Num: val:1
I1129 11:08:30.175103   75028 assign.go:79] Got lease request for txn: true. Num: val:1
I1129 11:08:30.200798   75028 assign.go:79] Got lease request for txn: true. Num: val:1
I1129 11:08:33.831341   75028 oracle.go:100] Purged below ts:3992096, len(o.commits):0, len(o.rowCommit):0
I1129 11:13:03.829632   75028 tablet.go:189]

Groups sorted by size: [{gid:3 size:0} {gid:2 size:265214} {gid:1 size:342608}]

I1129 11:13:03.829837   75028 tablet.go:194] size_diff 342608
I1129 11:13:03.829932   75028 tablet.go:83] Going to move predicate: [info], size: [114 kB] from group 1 to 3
I1129 11:13:04.192772   75028 tablet.go:119] Predicate move done for: [info] from group 1 to 3
I1129 11:21:03.829614   75028 tablet.go:189]

Groups sorted by size: [{gid:3 size:114449} {gid:2 size:265214} {gid:1 size:337672}]
E1129 15:08:03.830222   75028 oracle.go:425] No healthy connection found to leader of group 3
I1129 11:21:03.829836   75028 tablet.go:194] size_diff 223223
I1129 11:21:03.829946   75028 tablet.go:83] Going to move predicate: [name], size: [92 kB] from group 1 to 3
E1129 11:21:04.099134   75028 tablet.go:231] Got error during move: While calling MovePredicate: rpc error: code = Unavailable desc = transport is closing
E1129 11:21:04.100370   75028 tablet.go:70] Error while trying to move predicate name from 1 to 3: While calling MovePredicate: rpc error: code = Unavailable desc = transport is closing

E1129 11:21:04.895531   75028 pool.go:178] Echo error from localhost:7161. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:7161: connect: connection refused"
E1129 11:21:33.830876   75028 oracle.go:425] No healthy connection found to leader of group 3
E1129 11:22:03.829560   75028 oracle.go:425] No healthy connection found to leader of group 3
E1129 11:22:33.830745   75028 oracle.go:425] No healthy connection found to leader of group 3
E1129 11:23:03.830432   75028 oracle.go:425] No healthy connection found to leader of group 3


```

 **75438**
```bash
I1129 11:08:30.072663   75438 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992092 .
I1129 11:08:30.097996   75438 server.go:441] Got a query: query:"{\n\t\t  var(func: eq(dg_type , \"component_inst\")) @filter(eq(id , \"f6d476d0-4790-4d49-9830-650b960d0ecd\")) @cascade {\n\t\t  p as _predicate_\n\t\t}\n\t\tresult(func: eq(dg_type , \"component_inst\")) @filter(eq(id , \"f6d476d0-4790-4d49-9830-650b960d0ecd\")){\n\t\t  uid\n\t\t  expand(val(p))\n\t\t }\n\t\t}" 
I1129 11:08:30.099513   75438 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992093 .
I1129 11:08:30.135697   75438 server.go:441] Got a query: query:"{\n\t\t  var(func: eq(dg_type , \"component_inst\")) @filter(eq(id , \"f886cad9-3ee6-4e21-8376-072907f09c3f\")) @cascade {\n\t\t  p as _predicate_\n\t\t}\n\t\tresult(func: eq(dg_type , \"component_inst\")) @filter(eq(id , \"f886cad9-3ee6-4e21-8376-072907f09c3f\")){\n\t\t  uid\n\t\t  expand(val(p))\n\t\t }\n\t\t}" 
I1129 11:08:30.137133   75438 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992094 .
I1129 11:08:30.174193   75438 server.go:441] Got a query: query:"{\n\t\t  var(func: eq(dg_type , \"component_inst\")) @filter(eq(id , \"fb93a021-1835-4a0a-a54b-c64bc42106f6\")) @cascade {\n\t\t  p as _predicate_\n\t\t}\n\t\tresult(func: eq(dg_type , \"component_inst\")) @filter(eq(id , \"fb93a021-1835-4a0a-a54b-c64bc42106f6\")){\n\t\t  uid\n\t\t  expand(val(p))\n\t\t }\n\t\t}" 
I1129 11:08:30.175672   75438 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992095 .
I1129 11:08:30.199931   75438 server.go:441] Got a query: query:"{\n\t\t  var(func: eq(dg_type , \"component_inst\")) @filter(eq(id , \"fbfaba34-56ed-47f3-8bc8-7e001e8120de\")) @cascade {\n\t\t  p as _predicate_\n\t\t}\n\t\tresult(func: eq(dg_type , \"component_inst\")) @filter(eq(id , \"fbfaba34-56ed-47f3-8bc8-7e001e8120de\")){\n\t\t  uid\n\t\t  expand(val(p))\n\t\t }\n\t\t}" 
I1129 11:08:30.201498   75438 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992096 .
I1129 11:10:22.105015   75438 stream_lists.go:243] Rolling up Time elapsed: 01s, bytes sent: 0 B, speed: 0 B/sec
I1129 11:10:23.105032   75438 stream_lists.go:243] Rolling up Time elapsed: 02s, bytes sent: 0 B, speed: 0 B/sec
I1129 11:10:24.105148   75438 stream_lists.go:243] Rolling up Time elapsed: 03s, bytes sent: 0 B, speed: 0 B/sec
I1129 11:10:25.105066   75438 stream_lists.go:243] Rolling up Time elapsed: 04s, bytes sent: 0 B, speed: 0 B/sec
I1129 11:10:26.105299   75438 stream_lists.go:243] Rolling up Time elapsed: 05s, bytes sent: 0 B, speed: 0 B/sec
I1129 11:10:27.105187   75438 stream_lists.go:243] Rolling up Time elapsed: 06s, bytes sent: 0 B, speed: 0 B/sec
I1129 11:10:27.911099   75438 stream_lists.go:224] Rolling up Created batch of size: 50 MB in 181.529561ms.
I1129 11:10:27.911155   75438 stream_lists.go:258] Rolling up Sent 1868259 keys
I1129 11:10:27.926801   75438 draft.go:358] List rollup at Ts 3991933: OK.
I1129 11:13:03.842596   75438 predicate_move.go:260] Move predicate request for pred: [info], src: [1], dst: [3]
I1129 11:13:03.850981   75438 predicate_move.go:270] Trying to abort pending mutations. Loop: 0
I1129 11:13:04.142571   75438 stream_lists.go:224] Sending predicate: [info] Created batch of size: 130 kB in 263.973µs.
I1129 11:13:04.142812   75438 stream_lists.go:258] Sending predicate: [info] Sent 374 keys
I1129 11:13:04.185828   75438 predicate_move.go:148] Received 375 keys
I1129 11:15:21.466596   75438 index.go:797] Dropping predicate: [info]
I1129 11:15:21.782289   75438 schema.go:73] Deleting schema for predicate: [info]
I1129 11:21:03.832275   75438 predicate_move.go:260] Move predicate request for pred: [name], src: [1], dst: [3]
I1129 11:21:03.840368   75438 predicate_move.go:270] Trying to abort pending mutations. Loop: 0
I1129 11:21:04.057731   75438 stream_lists.go:224] Sending predicate: [name] Created batch of size: 131 kB in 686.44µs.
I1129 11:21:04.057789   75438 stream_lists.go:258] Sending predicate: [name] Sent 2442 keys
E1129 11:21:10.802628   75438 pool.go:178] Echo error from localhost:7161. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:7161: connect: connection refused"
I1129 11:29:03.832141   75438 predicate_move.go:260] Move predicate request for pred: [name], src: [1], dst: [3]
I1129 11:29:03.839946   75438 predicate_move.go:270] Trying to abort pending mutations. Loop: 0
I1129 11:37:03.832407   75438 predicate_move.go:260] Move predicate request for pred: [name], src: [1], dst: [3]
I1129 11:37:03.840029   75438 predicate_move.go:270] Trying to abort pending mutations. Loop: 0
I1129 11:45:03.832192   75438 predicate_move.go:260] Move predicate request for pred: [name], src: [1], dst: [3]
I1129 11:45:03.840034   75438 predicate_move.go:270] Trying to abort pending mutations. Loop: 0
I1129 11:53:03.833758   75438 predicate_move.go:260] Move predicate request for pred: [name], src: [1], dst: [3]
I1129 11:53:03.841706   75438 predicate_move.go:270] Trying to abort pending mutations. Loop: 0
I1129 12:01:03.831438   75438 predicate_move.go:260] Move predicate request for pred: [name], src: [1], dst: [3]
I1129 12:01:03.839663   75438 predicate_move.go:270] Trying to abort pending mutations. Loop: 0
I1129 12:09:03.832911   75438 predicate_move.go:260] Move predicate request for pred: [name], src: [1], dst: [3]
I1129 12:09:03.840374   75438 predicate_move.go:270] Trying to abort pending mutations. Loop: 0

```
  
**75949**
```bash
I1129 11:08:30.072732   75949 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992092 .
I1129 11:08:30.099686   75949 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992093 .
I1129 11:08:30.137327   75949 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992094 .
I1129 11:08:30.175663   75949 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992095 .
I1129 11:08:30.201502   75949 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992096 .
I1129 11:08:37.134197   75949 draft.go:317] Creating snapshot at index: 4274. ReadTs: 3991933.
I1129 11:08:37.134258   75949 storage.go:532] CreateSnapshot i=4274, cs=nodes:2 
I1129 11:10:37.253213   75949 stream_lists.go:224] Rolling up Created batch of size: 224 kB in 74.73896ms.
I1129 11:10:37.253267   75949 stream_lists.go:258] Rolling up Sent 5290 keys
I1129 11:10:37.264736   75949 draft.go:358] List rollup at Ts 3991933: OK.
E1129 11:21:07.117670   75949 pool.go:178] Echo error from localhost:7161. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:7161: connect: connection refused"


```

  **76061**

```bash
I1129 11:08:30.043718   76061 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992091 .
I1129 11:08:30.072666   76061 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992092 .
I1129 11:08:30.099707   76061 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992093 .
I1129 11:08:30.137273   76061 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992094 .
I1129 11:08:30.175852   76061 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992095 .
I1129 11:08:30.201408   76061 groups.go:818] Batched 1 updates. Proposing Delta: max_assigned:3992096 .
I1129 11:08:42.492467   76061 draft.go:317] Creating snapshot at index: 3894. ReadTs: 3991933.
I1129 11:08:42.492563   76061 storage.go:532] CreateSnapshot i=3894, cs=nodes:3 
I1129 11:10:42.486080   76061 stream_lists.go:258] Rolling up Sent 0 keys
I1129 11:10:42.486170   76061 draft.go:358] List rollup at Ts 3991933: OK.
I1129 11:13:03.851634   76061 predicate_move.go:204] Got ReceivePredicate. Group: 3. Am leader: true
I1129 11:13:03.851785   76061 predicate_move.go:153] Receiving predicate. Batching and proposing key values
I1129 11:13:04.145299   76061 predicate_move.go:173] Predicate being received: info
I1129 11:13:04.149421   76061 index.go:797] Dropping predicate: [info]
I1129 11:13:04.149482   76061 schema.go:73] Deleting schema for predicate: [info]
I1129 11:13:04.167705   76061 predicate_move.go:51] Writing 375 keys
I1129 11:13:04.185408   76061 schema.go:264] Setting schema for attr info: default, tokenizer: [], directive: NONE, count: false

I1129 11:13:04.185519   76061 predicate_move.go:238] Proposed 375 keys. Error: <nil>
I1129 11:21:03.841220   76061 predicate_move.go:204] Got ReceivePredicate. Group: 3. Am leader: true
I1129 11:21:03.841363   76061 predicate_move.go:153] Receiving predicate. Batching and proposing key values
I1129 11:21:04.061325   76061 predicate_move.go:173] Predicate being received: name
I1129 11:21:04.063074   76061 index.go:797] Dropping predicate: [name]
I1129 11:21:04.063216   76061 schema.go:73] Deleting schema for predicate: [name]
I1129 11:21:04.081770   76061 predicate_move.go:51] Writing 2443 keys
panic: Commit cannot be called with managedDB=true. Use CommitAt.

goroutine 251 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Txn).commitPrecheck(0xc421496800)
	/home/chujunlin/dgraph/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/txn.go:557 +0x86
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Txn).CommitWith(0xc421496800, 0xc4211ad2c0)
	/home/chujunlin/dgraph/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/txn.go:628 +0x2f
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Txn).CommitAt(0xc421496800, 0x0, 0xc4211ad2c0, 0x10, 0x0)
	/home/chujunlin/dgraph/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/managed_db.go:66 +0x56
github.com/dgraph-io/dgraph/worker.populateKeyValues(0x13becc0, 0xc42186c000, 0xc421cb8000, 0x98b, 0xc00, 0x0, 0x17)
	/home/chujunlin/dgraph/src/github.com/dgraph-io/dgraph/worker/predicate_move.go:68 +0x2ba
github.com/dgraph-io/dgraph/worker.(*node).applyCommitted(0xc4211b2ea0, 0xc420158600, 0xf3b, 0x17, 0x1aca5a0)
	/home/chujunlin/dgraph/src/github.com/dgraph-io/dgraph/worker/draft.go:286 +0xb26
github.com/dgraph-io/dgraph/worker.(*node).processApplyCh.func1(0xc421c79770, 0x1, 0x1)
	/home/chujunlin/dgraph/src/github.com/dgraph-io/dgraph/worker/draft.go:401 +0x3bd
github.com/dgraph-io/dgraph/worker.(*node).processApplyCh(0xc4211b2ea0)
	/home/chujunlin/dgraph/src/github.com/dgraph-io/dgraph/worker/draft.go:429 +0x25d
created by github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode
	/home/chujunlin/dgraph/src/github.com/dgraph-io/dgraph/worker/draft.go:1088 +0x503
```

**Comment by manishrjain** [comment]
Saw the same thing while working on Jepsen move tablet tests. Have a fix I'm working on.

**Comment by dmrlsn** [comment]
Hello,

I was wondering if you had any news on this issue.

I just made up a 4 machines cluster for testing purposes, but after a couple of mutations one of the machines presented this very same error. In no ways I could restart the aborted instance. The only option has been to stop everything and restart with a clean database.

The codebase is 94ca02824c3bd40c93723888d0c6370aef21f282 on master branch (pulled few hours ago through go get -v github.com/dgraph-io/dgraph/dgraph).

The issue is pretty deterministic in my setup (I am able to reproduce it in less than 3 mins), so I can provide details/traces if helps/anyone interested.

Thanks

**Comment by manishrjain** [comment]
This was fixed in `v1.0.12-rc3`. Commit: #2800 .

**Comment by jueyoq** [comment]
When can we solve it? Can we solve this problem now?

**Comment by manishrjain** [comment]
We are cutting a new rc tomorrow. It would be part of it. Otherwise, you can build from release/v1.0 branch, to get the fix right now.
