### ISSUE TITLE
start alpha has panic when first start after bulk load

### ISSUE THREAD

**Issue by relunctance** [dgraph-io/dgraph#2839]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
```
Dgraph version   : v1.0.11-rc4-12-gb0742078
Commit SHA-1     : b0742078
Commit timestamp : 2018-12-12 15:10:22 -0800
Branch           : master
Go version       : go1.11
```

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?

```
CentOS release 6.2 (Final)
64G RAM
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup00-LogVol03
                      1.8T  990G  683G  60% /
tmpfs                  32G     0   32G   0% /dev/shm
/dev/sda1              97M   32M   61M  35% /boot
/dev/mapper/VolGroup00-LogVol01
                     1008M   45M  913M   5% /tmp
/dev/mapper/VolGroup00-LogVol02
                      4.0G  353M  3.4G  10% /var
/dev/sdb              1.9T   33M  1.9T   1% /data1
/dev/sdc              1.9T   33M  1.9T   1% /data2
/dev/sdd              1.9T   33M  1.9T   1% /data3
```

- Steps to reproduce the issue (command/config used to run Dgraph).
```
{
  "custom_tokenizers": "/home/s/dgraph/ext/splushash.so",
  "alsologtostderr": false,
  "lru_mb": 4096,
  "bindall": true,
  "wal": "/home/s/dgraph/w",
  "postings": "/home/s/dgraph/p",
  "export": "/home/s/dgraph/export",
  "debugmode": true,
  "log_backtrace_at": 1,
  "v": 1,
  "log_dir": "/home/s/dgraph/logs",
  "expose_trace": "true",
  "zero": "xxx.xxx.xxx.xxx:5080",
  "port_offset": 0,
  "my": "xxx.xxx.xxx.xxx:7080",
  "idx": 1
}

dgraph alpha --config /home/s/dgraph/conf/alpha.json
```
1.  bulk load 650 million node and 830 million predicate with one group 
2. cp the data dir to /home/s/dgraph/p
3. start alpha and get panic from log

- Expected behaviour and actual result.

```
I1221 10:10:13.680884   28069 server.go:113] Setting Badger table load option: mmap
I1221 10:10:13.680903   28069 server.go:125] Setting Badger value log load option: mmap
I1221 10:10:13.680913   28069 server.go:153] Opening write-ahead log BadgerDB with options: {Dir:/home/s/dgraph/w ValueDir:/home/s/dgraph/w SyncWrites:true TableLoadingMode:1 ValueLogLoadingMode:2 NumVersionsToKeep:1 MaxTableSize:671088
64 LevelSizeMultiplier:10 MaxLevels:7 ValueThreshold:65500 NumMemtables:5 NumLevelZeroTables:5 NumLevelZeroTablesStall:10 LevelOneSize:268435456 ValueLogFileSize:1073741823 ValueLogMaxEntries:10000 NumCompactors:3 managedTxns:false DoNo
tCompact:false maxBatchCount:0 maxBatchSize:0 ReadOnly:false Truncate:true}
I1221 10:10:13.719259   28069 server.go:113] Setting Badger table load option: mmap
I1221 10:10:13.719327   28069 server.go:125] Setting Badger value log load option: mmap
I1221 10:10:13.719337   28069 server.go:167] Opening postings BadgerDB with options: {Dir:/home/s/dgraph/p ValueDir:/home/s/dgraph/p SyncWrites:true TableLoadingMode:2 ValueLogLoadingMode:2 NumVersionsToKeep:2147483647 MaxTableSize:6710
8864 LevelSizeMultiplier:10 MaxLevels:7 ValueThreshold:1024 NumMemtables:5 NumLevelZeroTables:5 NumLevelZeroTablesStall:10 LevelOneSize:268435456 ValueLogFileSize:1073741823 ValueLogMaxEntries:1000000 NumCompactors:3 managedTxns:false D
oNotCompact:false maxBatchCount:0 maxBatchSize:0 ReadOnly:false Truncate:true}
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.(*Table).read(0xc029cceb60, 0xffffffffffeffff3, 0x160009, 0x7fa372ab4ffc, 0x4, 0x4, 0x0, 0x0)
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/table.go:184 +0x1cf
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.(*Table).readNoFail(0xc029cceb60, 0xffffffffffeffff3, 0x160009, 0x7fa372ab4ffc, 0x4, 0x4)
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/table.go:198 +0x43
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.(*Table).readIndex(0xc029cceb60, 0x60000, 0x60000)
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/table.go:211 +0x9b
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.OpenTable(0xc08d502028, 0x2, 0x0, 0x0, 0x0)
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/table.go:153 +0x164
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.newLevelsController(0xc00007f880, 0xc00b02f2e8, 0xc00007f880, 0xc0006fb4a0, 0x1)
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:118 +0x4b0
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.Open(0xc0006d2330, 0x10, 0xc0006d2330, 0x10, 0x1, 0x2, 0x2, 0x7fffffff, 0x4000000, 0xa, ...)
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:266 +0x84e
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.OpenManaged(0xc0006d2330, 0x10, 0xc0006d2330, 0x10, 0x1, 0x2, 0x2, 0x7fffffff, 0x4000000, 0xa, ...)
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/managed_db.go:36 +0x68
github.com/dgraph-io/dgraph/edgraph.(*ServerState).initStorage(0x1f8bb40)
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/edgraph/server.go:168 +0x488
github.com/dgraph-io/dgraph/edgraph.InitServerState()
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/edgraph/server.go:74 +0xd3
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.run()
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:446 +0x887
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.init.1.func1(0xc0000f3d40, 0xc0002a5c40, 0x0, 0x2)
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:81 +0x52
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute(0xc0000f3d40, 0xc0002a5c00, 0x2, 0x2, 0xc0000f3d40, 0xc0002a5c00)
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702 +0x2d3
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1ee34c0, 0x3, 0x0, 0x0)
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute(0x1ee34c0, 0x8b394d, 0x1eeb6ac)
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/dgraph-io/dgraph/dgraph/cmd.Execute()
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:58 +0x36
main.main()
    /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/dgraph/main.go:33 +0x88
```

**Comment by srfrog** [comment]
Version 1.0.11 has been released. Can you try with that version and report back? Thanks
https://github.com/dgraph-io/dgraph/releases/tag/v1.0.11

**Comment by manishrjain** [comment]
It looks like the data on disk got modified. Badger isn't able to read the table index.

**Comment by relunctance** [comment]
> Version 1.0.11 has been released. Can you try with that version and report back? Thanks
> https://github.com/dgraph-io/dgraph/releases/tag/v1.0.11

yes

**Comment by manishrjain** [comment]
How much data is in sst files and how much in vlog files?

**Comment by relunctance** [comment]
> How much data is in sst files and how much in vlog files?

```
node num: 0.65 Billion
predicate: 0.83 Billion
.vlog file num: 3827
.vlog file total size: 321G
.sst file num: 2561
.sst file total size: 142G
```

**Comment by manishrjain** [comment]
You can file a bug in Badger about this, so we can add a better error there.
