### ISSUE TITLE
alpha "slice bounds out of range" panic

### ISSUE THREAD

**Issue by codexnull** [dgraph-io/dgraph#3123]
A process was inserting data into dgraph when one of the alpha processed died with a "slice bounds out of range" panic. Unfortunately, I have no way of finding out what the transaction was that cause this. The tail of the log is below.

--- 

I0309 22:08:17.148355       1 node.go:83] Rolling up Time elapsed: 02s, bytes sent: 7.0 MB, speed: 3.5 MB/sec
I0309 22:08:17.422592       1 node.go:83] Rolling up Created batch of size: 1.9 MB in 270.873486ms.
I0309 22:08:17.737731       1 node.go:83] Rolling up Created batch of size: 1.9 MB in 228.893129ms.
I0309 22:08:18.666300       1 node.go:83] Rolling up Created batch of size: 3.4 MB in 926.652982ms.
panic: runtime error: slice bounds out of range

goroutine 82399967 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).Read(0xc000400458, 0x445000000cc, 0x65a1db6, 0xc041f56140, 0xd, 0x10, 0x793f1, 0x0, 0xc010433a50, 0xead66f)
        /home/javier/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:1026 +0x2c7
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Item).yieldItemValue(0xc0232ded10, 0x0, 0xc010433b01, 0xc010433b98, 0xfb7615, 0xc03140a060, 0xc010433b98)
        /home/javier/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:168 +0x136
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Item).Value(0xc0232ded10, 0xc010433c28, 0x0, 0x0)
        /home/javier/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:103 +0xe8
github.com/dgraph-io/dgraph/posting.ReadPostingList(0xc010e8aaa0, 0x17, 0x20, 0xc03a3f2000, 0x0, 0xc010e8aaa0, 0xc03140a060)
        /home/javier/go/src/github.com/dgraph-io/dgraph/posting/mvcc.go:215 +0x221
github.com/dgraph-io/dgraph/worker.(*node).rollupLists.func3(0xc010e8aaa0, 0x17, 0x20, 0xc03a3f2000, 0x17, 0xc010e8aaa0, 0x0)
        /home/javier/go/src/github.com/dgraph-io/dgraph/worker/draft.go:890 +0x68
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).produceKVs.func1(0xc05f24c340, 0x1f, 0x20, 0xc05f24c360, 0x1f, 0x20, 0x0, 0x0, 0x0)
        /home/javier/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:167 +0x377
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).produceKVs(0xc02e8e3ea0, 0x1609940, 0xc0000b6020, 0x0, 0x0)
        /home/javier/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:195 +0x271
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).Orchestrate.func1(0xc011130820, 0xc02e8e3ea0, 0x1609940, 0xc0000b6020, 0xc05734b7a0)
        /home/javier/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:298 +0x69
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).Orchestrate
        /home/javier/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:295 +0x181

**Comment by srfrog** [comment]
From 500ft view it looks like this could be a badger bug.
