### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#3185]
not sure if it is already tracked. got it right now on data load on 1.0.14-rc1
```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: Unclosed iterator at time of Txn.Discard.
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xe81578]

goroutine 81461552 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Txn).Discard(0xc041ce9c00)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/txn.go:490 +0xde
panic(0x13a03a0, 0x20201c0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).deleteLogFile(0xc0005da458, 0x0, 0x1e, 0x20feae0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:558 +0x38
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).decrIteratorCount(0xc0005da458, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:550 +0x25b
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Iterator).Close(0xc03fcc21e0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:484 +0xb7
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).produceKVs.func1(0x0, 0x0, 0x0, 0xc032c83ee0, 0x1b, 0x20, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:185 +0x6ed
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).produceKVs(0xc0652aed20, 0x1678aa0, 0xc0000c0010, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:195 +0x28c
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).Orchestrate.func1(0xc042eec440, 0xc0652aed20, 0x1678aa0, 0xc0000c0010, 0xc00198d740)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:298 +0x69
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).Orchestrate
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:295 +0x175
```

logs are here: https://drive.google.com/file/d/1aGPt9msqDC-iFAA2PzZWTpr4l3XN4_c4/view?usp=sharing

**Comment by srfrog** [comment]
Couldn't reproduce on master. Closing this please reopen if you think it's still an issue.

**Comment by manishrjain** [comment]
I can replicate this. This happens due to:

```
	for _, id := range vlog.filesToBeDeleted {
		lfs = append(lfs, vlog.filesMap[id])
		delete(vlog.filesMap, id)
	}
	lfs = append(lfs, nil) // HACK I added to replicate this bug.
```
if `lfs` has a nil pointer in the list, it would cause this panic later. 

```$ go test -v -run TestStream
=== RUN   TestStream
badger 2019/04/25 18:30:02 INFO: All 0 tables opened in 0s
panic: runtime error: invalid memory address or nil pointer dereference
	panic: Unclosed iterator at time of Txn.Discard.
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7c1086]

goroutine 93 [running]:
github.com/dgraph-io/badger.(*Txn).Discard(0xc420192000)
	/home/mrjn/go/src/github.com/dgraph-io/badger/txn.go:498 +0xe3
panic(0x88fd40, 0xba5e50)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
github.com/dgraph-io/badger.(*valueLog).deleteLogFile(0xc4203fe158, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:560 +0x26
github.com/dgraph-io/badger.(*valueLog).decrIteratorCount(0xc4203fe158, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:552 +0x2a6
github.com/dgraph-io/badger.(*Iterator).Close(0xc4203ce1e0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/iterator.go:490 +0xb9
github.com/dgraph-io/badger.(*Stream).produceKVs.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/stream.go:185 +0x6f1
github.com/dgraph-io/badger.(*Stream).produceKVs(0xc4257b2230, 0x97b2c0, 0xc420024180, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/stream.go:195 +0x28c
github.com/dgraph-io/badger.(*Stream).Orchestrate.func1(0xc4257f1cb0, 0xc4257b2230, 0x97b2c0, 0xc420024180, 0xc4257a4660)
	/home/mrjn/go/src/github.com/dgraph-io/badger/stream.go:298 +0x69
created by github.com/dgraph-io/badger.(*Stream).Orchestrate
	/home/mrjn/go/src/github.com/dgraph-io/badger/stream.go:295 +0x19c
```
