### ISSUE TITLE
panic: runtime error: slice bounds out of range everywhere

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#3212]
release/v1.0
v1.0.14-rc1-2-gd386fa5d-oss

this error is happening in:

Opening postings BadgerDB with options: {Dir:p ValueDir:p SyncWrites:true TableLoadingMode:2 ValueLogLoadingMode:2 NumVersionsToKeep:2147483647 MaxTableSize:67108864 LevelSizeMultiplier:10 MaxLevels:7 ValueThreshold:1024 NumMemtables:5 NumLevelZeroTables:5 NumLevelZeroTablesStall:10 LevelOneSize:268435456 ValueLogFileSize:1073741823 ValueLogMaxEntries:1000000 NumCompactors:2 CompactL0OnClose:true managedTxns:false maxBatchCount:0 maxBatchSize:0 ReadOnly:false Truncate:true Logger:0x1c6d7c0}
panic: runtime error: slice bounds out of range

Sending Snapshot Created batch of size: 125 MB in 13.820585169s.
panic: runtime error: slice bounds out of range

143 tables out of 198 opened in 3.026s
panic: runtime error: slice bounds out of range

full log with panics from last day here:
https://drive.google.com/file/d/1JLj4WmVtz_Qe6kDHuFXQqVfw9CPPvv4M/view?usp=sharing

```
Sending Snapshot Created batch of size: 125 MB in 13.820585169s.
panic: runtime error: slice bounds out of range

goroutine 872 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).Read(0xc42029a458, 0x5e00000054, 0x15672b, 0xc482964200, 0x2, 0x0, 0x800, 0xc48dcca9f0, 0xb2ffcf, 0xc48d831bd0)
	/home/l/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:1026 +0x2bf
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Item).yieldItemValue(0xc4ab25e160, 0x95d8d2, 0xc4b986e7e0, 0x0, 0x20, 0x0, 0x0)
	/home/l/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:168 +0x14d
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Item).ValueCopy(0xc4ab25e160, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/l/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:125 +0x181
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).ToList(0xc493e05880, 0xc4e9fd8f20, 0x13, 0x20, 0xc493d78320, 0x20, 0x13, 0xc4e9fd8f20)
	/home/l/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:89 +0x12e
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).ToList-fm(0xc4e9fd8f20, 0x13, 0x20, 0xc493d78320, 0x13, 0xc4e9fd8f20, 0x0)
	/home/l/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:285 +0x52
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).produceKVs.func1(0xc5544faec0, 0x1b, 0x20, 0xc5544faf00, 0x1b, 0x20, 0x0, 0x0, 0x0)
	/home/l/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:167 +0x366
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).produceKVs(0xc493e05880, 0x14a6580, 0xc4900bcea0, 0x0, 0x0)
	/home/l/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:195 +0x28c
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).Orchestrate.func1(0xc493f220f0, 0xc493e05880, 0x14a6580, 0xc4900bcea0, 0xc4909375c0)
	/home/l/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:298 +0x69
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).Orchestrate
	/home/l/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:295 +0x19c
```

**Comment by makitka2007** [comment]
ok, seems like it's master, we've built that branch wrong for some reason

**Comment by srfrog** [comment]
If you built from dgraph master that includes a vendored badger. I'm trying to replicate this, so if you have any ideas that would help.

**Comment by srfrog** [comment]
No activity, closing. Please reopen if you are still experiencing this.
