### ISSUE TITLE
Panic while running tests in query module

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#345]
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7efecc01bc50 pc=0x7efecc01bc50]

runtime stack:
runtime.throw(0x9d5ab8, 0x2a)
	/usr/lib/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 674 [syscall, locked to thread]:
runtime.cgocall(0x8ade80, 0xc420496490, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:131 +0x110 fp=0xc420496440 sp=0xc420496400
github.com/dgraph-io/dgraph/rdb._Cfunc_rdb_put(0x7efecc06f410, 0x7efecc01bf00, 0xc42029eb70, 0xd, 0xc4201f0990, 0x24, 0xc4202285f0)
	github.com/dgraph-io/dgraph/rdb/_obj/_cgo_gotypes.go:635 +0x45 fp=0xc420496490 sp=0xc420496440
github.com/dgraph-io/dgraph/rdb.(*DB).Put(0xc4206b98a0, 0xc42030c550, 0xc42029eb70, 0xd, 0xd, 0xc4201f0990, 0x24, 0x24, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/rdb/db.go:110 +0x27a fp=0xc420496538 sp=0xc420496490
github.com/dgraph-io/dgraph/store.(*Store).SetOne(0xc420344e70, 0xc42029eb70, 0xd, 0xd, 0xc4201f0990, 0x24, 0x24, 0xc4204965f8, 0x411e7b)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/store/store.go:98 +0x80 fp=0xc420496598 sp=0xc420496538
github.com/dgraph-io/dgraph/posting.(*List).commit(0xc420494960, 0xc42000c500, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/posting/list.go:522 +0x388 fp=0xc4204966c8 sp=0xc420496598
github.com/dgraph-io/dgraph/posting.(*List).CommitIfDirty(0xc420494960, 0xe64980, 0xc42000c588, 0x5afebc, 0xc4206b98e0, 0xbd76ee7e112d0460)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/posting/list.go:485 +0x101 fp=0xc420496710 sp=0xc4204966c8
github.com/dgraph-io/dgraph/posting.mergeAndUpdate(0xc420494960, 0xc4201f0510)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/posting/lists.go:320 +0x50 fp=0xc420496760 sp=0xc420496710
github.com/dgraph-io/dgraph/posting.mergeAndUpdateKeys(0xc4202ff400, 0x66, 0x12c)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/posting/lists.go:125 +0xf2 fp=0xc4204967a8 sp=0xc420496760
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4204967b0 sp=0xc4204967a8
created by github.com/dgraph-io/dgraph/posting.gentleMerge
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/posting/lists.go:148 +0x219
```

**Comment by manishrjain** [comment]
Also, this stack trace:

```
goroutine 646 [syscall, locked to thread]:
github.com/dgraph-io/dgraph/rdb._Cfunc_rdb_close(0x7efecc06f410)
	github.com/dgraph-io/dgraph/rdb/_obj/_cgo_gotypes.go:285 +0x41
github.com/dgraph-io/dgraph/rdb.(*DB).Close(0xc4206b98a0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/rdb/db.go:66 +0x78
github.com/dgraph-io/dgraph/store.(*Store).Close(0xc420344e70)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/store/store.go:113 +0x2e
github.com/dgraph-io/dgraph/query.TestToJSONOrderOffset(0xc42019e600)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/query/query_test.go:1400 +0x4cf
testing.tRunner(0xc42019e600, 0xa0a6c0)
	/usr/lib/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:646 +0x2ec
```

**Comment by manishrjain** [comment]
Nvm. Fixed it. It was caused by indexing tasks taking longer than the 200ms sleep imparted at the end of `populateGraph` in query_test.go. Because this is specific just to the query_test.go; I fixed it by avoiding closing RocksDB store.

**Comment by manishrjain** [comment]
The downside I think is that my `/tmp` directory tends to get full really fast.
