### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference with split posting list

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#3861]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
master

```
Dgraph version   : v1.0.12-rc3-682-ge3660d4f0
Dgraph SHA-256   : f1a0ec60a452be980cb611c7586d541695289e49aaa89f24f2e182bfcf226a85
Commit SHA-1     : e3660d4f0
Commit timestamp : 2019-08-22 10:57:43 -0700
Branch           : master
Go version       : go1.12.7
```

- Have you tried reproducing the issue with latest release?
No. Split posting list is only in master.

- Steps to reproduce the issue (command/config used to run Dgraph).

I'm not sure how to reproduce this. I was doing data loading via live loader. Here's the Alpha logs from the panic:

```

I0823 22:26:04.823286       1 draft.go:1093] TryAbort 93 txns with start ts. Error: <nil>
I0823 22:26:04.823337       1 draft.go:1116] TryAbort selectively proposing only aborted txns: txns:<start_ts:22933 > txns:<start_ts:22967 > txns:<start_ts:22928 > txns:<start_ts:22952 > txns:<start_ts:22949 > txns:<start_ts:22869 > txns:<start_ts:22870 >
 txns:<start_ts:22900 > txns:<start_ts:22941 > txns:<start_ts:22921 > txns:<start_ts:22880 > txns:<start_ts:22914 > txns:<start_ts:22872 > txns:<start_ts:22939 > txns:<start_ts:22940 > txns:<start_ts:22957 > txns:<start_ts:22936 > txns:<start_ts:22930 > txns:<start_ts:22965 > txns:<start_ts:22958 > txns:<start_ts:22881 > txns:<start_ts:22888 > txns:<start_ts:22904 > txns:<start_ts:22946 > txns:<start_ts:22917 > txns:<start_ts:22963 > txns:<start_ts:22942 > txns:<start_ts:22924 > txns:<start_ts:22968 > txns:<start_ts:22918 > txns:<start_ts:22885 > txns:<start_ts:22884 > txns:<start_ts:22911 > txns:<start_ts:22937 > txns:<start_ts:22925 > txns:<start_ts:22882 > txns:<start_ts:22950 > txns:<start_ts:22873 > txns:<start_ts:22915 > txns:<start_ts:22932 > txns:<start_ts:22964 > txns:<start_ts:22961 > txns:<start_ts:22906 > txns:<start_ts:22953 > txns:<start_ts:22898 > txns:<start_ts:22887 > txns:<start_ts:22908 > txns:<start_ts:22920 > txns:<start_ts:22874 > txns:<start_ts:22944 > txns:<start_ts:22889 > txns:<start_ts:22943 > txns:<start_ts:22954 > txns:<start_ts:22916 > txns:<start_ts:22931 > txns:<start_ts:22969 > txns:<start_ts:22899 > txns:<start_ts:22866 > txns:<start_ts:22960 > txns:<start_ts:22926 > txns:<start_ts:22951 > txns:<start_ts:22871 > txns:<start_ts:22896 > txns:<start_ts:22970 > txns:<start_ts:22966 > txns:<start_ts:22878 > txns:<start_ts:22897 > txns:<start_ts:22929 > txns:<start_ts:22867 > txns:<start_ts:22956 > txns:<start_ts:22886 > txns:<start_ts:22863 > txns:<start_ts:22947 > txns:<start_ts:22948 > txns:<start_ts:22922 > txns:<start_ts:22877 > txns:<start_ts:22955 > txns:<start_ts:22907 > txns:<start_ts:22935 > txns:<start_ts:22923 > txns:<start_ts:22919 > txns:<start_ts:22891 > txns:<start_ts:22865 > txns:<start_ts:22927 > txns:<start_ts:22934 > txns:<start_ts:22913 > txns:<start_ts:22938 > txns:<start_ts:22861 > txns:<start_ts:22903 > txns:<start_ts:22895 > txns:<start_ts:22959 > txns:<start_ts:22962 > txns:<start_ts:22945 > 
I0823 22:26:04.857732       1 draft.go:1135] Done abortOldTransactions for 93 txns. Error: <nil>
I0823 22:27:02.831786       1 draft.go:668] [0x1] Set Raft progress to index: 3275.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x11fefd6]

goroutine 23424 [running]:
github.com/dgraph-io/dgraph/posting.(*pIterator).selectInitialSplit(0xc0027398a0, 0x75f25117b1d56ea5, 0x0)
        /home/dmai/go/src/github.com/dgraph-io/dgraph/posting/list.go:143 +0x16
github.com/dgraph-io/dgraph/posting.(*pIterator).init(0xc0027398a0, 0xc04540a0c0, 0x75f25117b1d56ea5, 0x0, 0x67, 0x80)
        /home/dmai/go/src/github.com/dgraph-io/dgraph/posting/list.go:111 +0x74
github.com/dgraph-io/dgraph/posting.(*List).iterate(0xc04540a0c0, 0x5aa0, 0x75f25117b1d56ea5, 0xc002739948, 0x8, 0x75f25117b1d56ea6)
        /home/dmai/go/src/github.com/dgraph-io/dgraph/posting/list.go:615 +0x112
github.com/dgraph-io/dgraph/posting.(*List).findPosting(0xc04540a0c0, 0x5aa0, 0x75f25117b1d56ea6, 0x0, 0x0, 0x1d0beb66bb0, 0x22c13a0)
        /home/dmai/go/src/github.com/dgraph-io/dgraph/posting/list.go:1116 +0x96
github.com/dgraph-io/dgraph/posting.(*List).findValue(0xc04540a0c0, 0x5aa0, 0x75f25117b1d56ea6, 0x0, 0x0, 0x0, 0xc096997b60, 0xc002739a68, 0x11f919f)
        /home/dmai/go/src/github.com/dgraph-io/dgraph/posting/list.go:1106 +0x61
github.com/dgraph-io/dgraph/posting.(*Txn).addMutationHelper(0xc0ad83aac0, 0x194a0e0, 0xc046801a40, 0xc04540a0c0, 0x1, 0xc05e064e60, 0xc000000000, 0x0, 0x0, 0xc000040500, ...)
        /home/dmai/go/src/github.com/dgraph-io/dgraph/posting/index.go:317 +0x829
github.com/dgraph-io/dgraph/posting.(*List).AddMutationWithIndex(0xc04540a0c0, 0x194a0e0, 0xc046801a40, 0xc05e064e60, 0xc0ad83aac0, 0x0, 0xc002712090)
        /home/dmai/go/src/github.com/dgraph-io/dgraph/posting/index.go:384 +0x11e
github.com/dgraph-io/dgraph/worker.runMutation(0x194a0e0, 0xc046801a40, 0xc05e064e60, 0xc0ad83aac0, 0x0, 0x0)
        /home/dmai/go/src/github.com/dgraph-io/dgraph/worker/mutation.go:115 +0x35d
github.com/dgraph-io/dgraph/worker.(*node).applyMutations.func3(0xc05e05afa0, 0x1f4, 0x20c, 0x120c77e, 0xc09699c340)
        /home/dmai/go/src/github.com/dgraph-io/dgraph/worker/draft.go:284 +0xb1
github.com/dgraph-io/dgraph/worker.(*node).applyMutations.func4(0xc04540a060, 0xc017104fc0, 0xc0ad83e1e0, 0x1f4, 0x3e8)
        /home/dmai/go/src/github.com/dgraph-io/dgraph/worker/draft.go:313 +0x7d
created by github.com/dgraph-io/dgraph/worker.(*node).applyMutations
        /home/dmai/go/src/github.com/dgraph-io/dgraph/worker/draft.go:312 +0x9a7
```

**Comment by gitlw** [comment]
I tried a couple of things, including forcing a snapshot & rollup followed by a mutation with deletion that can go through the code in the stacktrace, but still couldn't reproduce the bug.

Also the data you attached has this
```
"type": [                                                                                                                                      
        "Normal",                                                                                                                                    
        {                                                                                                                                            
          "uid": "_:Flying",                                                                                                                         
          "name": "Flying"                                                                                                                           
        }                                                                                                                                            
      ]
```

and when I manually sent the type of "type" to [uid], dgraph complains it cannot accept the string "Normal".
