### ISSUE TITLE
OOM and performance issue while bulk importing on master

### ISSUE THREAD

**Issue by eawer** [dgraph-io/dgraph#3918]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
```
Dgraph version   : master
Dgraph SHA-256   : 4f93faa8e7954e77ab3f03899e492fa8aff80a85b4701ff430d0befd0cc2ebc5
Commit SHA-1     : b99709c6
Commit timestamp : 2019-08-28 18:47:41 +0530
Branch           : master
Go version       : go1.12.5
```

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
I will compare `master` performance to `latest`, so:
for `latest`: 30GB, 8 x Intel(R) Xeon(R) CPU @ 2.30GHz, Ubuntu 16.04 
for `master`: 60GB, 16 x Intel(R) Xeon(R) CPU @ 2.30GHz, Ubuntu 16.04

- Steps to reproduce the issue (command/config used to run Dgraph).

For master:
1. `docker run -it --rm -p 5080:5080 -p 6080:6080 -p 8080:8080 -p 9080:9080 -p 8000:8000 -v ~/freebase/dgraph:/dgraph --name dgraph dgraph/dgraph:master dgraph zero`
2.  `docker exec -it dgraph dgraph bulk -f freebase.rdf.gz -s freebase.schema -v 3 --zero localhost:5080`
For latest - I've described in #3916 

- Expected behaviour and actual result.
Despite I've used two times more powerful machine for `master`, the import process was slower. For example,  performance for `latest` at the MAP stage:

```
start:
MAP nquad_speed: ~220k/sec edge_speed: ~220k/sec
end:
MAP 04h25m09s nquad_count:3.114G err_count:0.000 nquad_speed:195.7k/sec edge_count:6.227G edge_speed:391.4k/sec
```
We can see some performance degradation, but not that big. The situation changes for the MAP at `master`, where speed loss in more than 30%:

```
start:
MAP 15s nquad_count:4.645M err_count:0.000 nquad_speed:309.3k/sec edge_count:4.645M edge_speed:309.3k/sec
end:
MAP 04h34m54s nquad_count:3.114G err_count:0.000 nquad_speed:188.8k/sec edge_count:3.114G edge_speed:188.8k/sec
```

Things are getting even weirder when it comes to REDUCE stage.
For `latest` (though it crashed right after that #3916):

```
started
REDUCE 04h26m15s [1.18%] edge_count:73.77M edge_speed:1.201M/sec plist_count:804.4k plist_speed:13.09k/sec
ended
REDUCE 07h43m18s [100.00%] edge_count:6.227G edge_speed:524.0k/sec plist_count:1.202G plist_speed:101.2k/sec
```

`master`:
```
start:
REDUCE 04h35m18s 0.06% edge_count:1.932M edge_speed:91.68k/sec plist_count:1.868M plist_speed:88.64k/sec
GC: 1734. InUse: 42 GB. Idle: 1.2 GB
right before it crashed:
REDUCE 05h29m17s 21.72% edge_count:676.2M edge_speed:207.3k/sec plist_count:340.3M plist_speed:104.4k/sec
GC: 2057. InUse: 145 GB. Idle: 395 MB
```
So on twice as powerful machine on `master`, the speed is `edge_speed:91.68k/sec` vs `edge_speed:1.201M/sec` on the latest (though I must confess I'm not sure what that speed means).

Right after that, `master` crashed with OOM (on `latest` memory usage did not exceed ~15Gb):
<details>
  <summary>Stack trace here</summary>

```
  fatal error: runtime: cannot allocate memory

runtime stack:
runtime.throw(0x177c2b8, 0x1f)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.persistentalloc1(0x4000, 0x0, 0x24d4ed8, 0x7fea1757d008)
	/usr/local/go/src/runtime/malloc.go:1235 +0x2b7
runtime.persistentalloc.func1()
	/usr/local/go/src/runtime/malloc.go:1189 +0x45
runtime.persistentalloc(0x4000, 0x0, 0x24d4ed8, 0x7fea17580f08)
	/usr/local/go/src/runtime/malloc.go:1188 +0x82
runtime.(*fixalloc).alloc(0x24be240, 0x1)
	/usr/local/go/src/runtime/mfixalloc.go:80 +0xf5
runtime.(*mheap).allocSpanLocked(0x24bbd40, 0x1, 0x24d4ea8, 0x7fea17580e78)
	/usr/local/go/src/runtime/mheap.go:1175 +0x169
runtime.(*mheap).alloc_m(0x24bbd40, 0x1, 0x9f000b, 0x7fea17580e78)
	/usr/local/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:1048 +0x4c
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1153

goroutine 6002 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc0000818c0 sp=0xc0000818b8 pc=0x9fe1b0
runtime.(*mheap).alloc(0x24bbd40, 0x1, 0x7fea2a01000b, 0x7fea17580d58)
	/usr/local/go/src/runtime/mheap.go:1047 +0x8a fp=0xc000081910 sp=0xc0000818c0 pc=0x9c72ca
runtime.(*mcentral).grow(0x24bc380, 0x0)
	/usr/local/go/src/runtime/mcentral.go:256 +0x95 fp=0xc000081958 sp=0xc000081910 pc=0x9ba215
runtime.(*mcentral).cacheSpan(0x24bc380, 0x3f)
	/usr/local/go/src/runtime/mcentral.go:106 +0x2ff fp=0xc0000819b8 sp=0xc000081958 pc=0x9b9d1f
runtime.(*mcache).refill(0x7ff51e872008, 0xb)
	/usr/local/go/src/runtime/mcache.go:135 +0x86 fp=0xc0000819d8 sp=0xc0000819b8 pc=0x9b97b6
runtime.(*mcache).nextFree(0x7ff51e872008, 0xc63d9cb20b, 0xe1be7c6fc0, 0x7fea17580d58, 0x1000)
	/usr/local/go/src/runtime/malloc.go:786 +0x88 fp=0xc000081a10 sp=0xc0000819d8 pc=0x9adf38
runtime.mallocgc(0x40, 0x0, 0x0, 0xe1be7c7fc0)
	/usr/local/go/src/runtime/malloc.go:939 +0x76e fp=0xc000081ab0 sp=0xc000081a10 pc=0x9ae84e
runtime.growslice(0x1599b20, 0x0, 0x0, 0x0, 0x3a, 0xe1be7c7fc0, 0x0, 0x40)
	/usr/local/go/src/runtime/slice.go:175 +0x151 fp=0xc000081b18 sp=0xc000081ab0 pc=0x9e7581
github.com/dgraph-io/dgraph/protos/pb.(*MapEntry).Unmarshal(0xe1be7ca4b0, 0xc97c76f130, 0x45, 0x45, 0x1, 0x7ff2552a1120)
	/tmp/go/src/github.com/dgraph-io/dgraph/protos/pb/pb.pb.go:17684 +0x272 fp=0xc000081c68 sp=0xc000081b18 pc=0xece1d2
github.com/dgraph-io/dgraph/protos/pb.(*MapEntry).XXX_Unmarshal(0xe1be7ca4b0, 0xc97c76f130, 0x45, 0x45, 0xe1be7ca4b0, 0xc000081d01)
	/tmp/go/src/github.com/dgraph-io/dgraph/protos/pb/pb.pb.go:3145 +0x49 fp=0xc000081ca8 sp=0xc000081c68 pc=0xe7c139
github.com/dgraph-io/dgraph/vendor/github.com/gogo/protobuf/proto.Unmarshal(0xc97c76f130, 0x45, 0x45, 0x193ab60, 0xe1be7ca4b0, 0x45, 0x45)
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/gogo/protobuf/proto/decode.go:338 +0x1bd fp=0xc000081d10 sp=0xc000081ca8 pc=0x128015d
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*mapIterator).Next(0xc0050852c0, 0x3a)
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/reduce.go:128 +0x21f fp=0xc000081dc0 sp=0xc000081d10 pc=0x13f58bf
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*reducer).reduce(0xc00263c070, 0xc089ee4000, 0x11eb, 0x1400, 0xc02116ed80)
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/reduce.go:213 +0x379 fp=0xc000081ef0 sp=0xc000081dc0 pc=0x13f62f9
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*reducer).run.func1(0xc03f1ca700, 0xc000298a00, 0x1, 0x64, 0xc00263c070, 0x0, 0xc288c06380)
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/reduce.go:73 +0x216 fp=0xc000081fa8 sp=0xc000081ef0 pc=0x13fb466
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000081fb0 sp=0xc000081fa8 pc=0xa00281
created by github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*reducer).run
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/reduce.go:57 +0x1c5
```
</details>

And just one more weird thing I've spotted for master - considering pretty big dataset (freebase, 30Gb gzipped, ~350Gb decompressed) I saw this:
```
sudo du -sh out tmp zw
29G	out
33G	tmp
2.8M	zw
```
while for the `latest` both `out` and `temp` were 350-500GB

**Comment by ashish-goswami** [comment]
Hey @eawer, We have done some optimisations in bulk loader in following commits to address high memory usage issue:
https://github.com/dgraph-io/dgraph/commit/240f8e2778102b5a7c12cda70ac225e9db24dc7c
https://github.com/dgraph-io/dgraph/commit/ae679e6c1b3cf2cc9a0c323de9df13bfa10f6c13

We are trying to bring down memory usage further.
We did testing on 16 core, 64 GB ubuntu machine(on above data). Bulk loader did not go OOM during map and reduce phase separately. It went OOM while transitioning from map to reduce phase. We know why this is happening and working on the solution.
Also time to run bulk loader is around 4 hours with 2 hour for map and reduce phase each.
