### ISSUE TITLE
Sigpanic error on alpha node

### ISSUE THREAD

**Issue by igormiletic** [dgraph-io/dgraph#4100]
Version:

I0930 06:17:27.809113 1 init.go:98]
Dgraph version : v1.1.0
Dgraph SHA-256 : 7d4294a80f74692695467e2cf17f74648c18087ed7057d798f40e1d3a31d2095
Commit SHA-1 : ef7cdb2
Commit timestamp : 2019-09-04 00:12:51 -0700
Branch : HEAD
Go version : go1.12.7

Kubernetes 1.13.
Setup is from HA documentation of DGraph. 3 alpha nodes and 3 zero nodes

```
	I0930 06:27:21.453797       1 log.go:34] Rolling up Created batch of size: 4.2 MB in 6.299609ms.
unexpected fault address 0xc05c000000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc05c000000 pc=0x11ef2b1]
goroutine 973797 [running]:
runtime.throw(0x175d0cb, 0x5)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc04583f740 sp=0xc04583f710 pc=0x9d0fd2
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:397 +0x401 fp=0xc04583f770 sp=0xc04583f740 pc=0x9e7151
github.com/dgraph-io/dgraph/vendor/github.com/dgryski/go-groupvarint.Decode4(0xc04583f7e8, 0x4, 0x4, 0xc05bfffff1, 0xd, 0xf)
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgryski/go-groupvarint/decode_amd64.s:11 +0x11 fp=0xc04583f778 sp=0xc04583f770 pc=0x11ef2b1
github.com/dgraph-io/dgraph/codec.(*Decoder).unpackBlock(0xc03075ae70, 0x0, 0x0, 0xc03121ce18)
	/tmp/go/src/github.com/dgraph-io/dgraph/codec/codec.go:145 +0x226 fp=0xc04583f820 sp=0xc04583f778 pc=0x11efaa6
github.com/dgraph-io/dgraph/codec.(*Decoder).Next(...)
/tmp/go/src/github.com/dgraph-io/dgraph/codec/codec.go:270
github.com/dgraph-io/dgraph/posting.(*pIterator).next(0xc04583f930, 0x0, 0x0)
	/tmp/go/src/github.com/dgraph-io/dgraph/posting/list.go:220 +0x8f fp=0xc04583f850 sp=0xc04583f820 pc=0x11fb6bf
github.com/dgraph-io/dgraph/posting.(*List).iterate(0xc0006ba9c0, 0xffffffffffffffff, 0x0, 0xc04583fa20, 0xc013fa5fc0, 0xc04583fa18)
	/tmp/go/src/github.com/dgraph-io/dgraph/posting/list.go:644 +0x3a2 fp=0xc04583f9a8 sp=0xc04583f850 pc=0x11fd432
github.com/dgraph-io/dgraph/posting.(*List).rollup(0xc0006ba9c0, 0xffffffffffffffff, 0xc0006ba9c0, 0xc04583fac8, 0x1202fe3)
	/tmp/go/src/github.com/dgraph-io/dgraph/posting/list.go:837 +0x2c8 fp=0xc04583fa70 sp=0xc04583f9a8 pc=0x11fe4a8
github.com/dgraph-io/dgraph/posting.(*List).Rollup(0xc0006ba9c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/dgraph-io/dgraph/posting/list.go:730 +0xab fp=0xc04583fb80 sp=0xc04583fa70 pc=0x11fdadb
github.com/dgraph-io/dgraph/worker.(*node).rollupLists.func3(0xc01880d570, 0xd, 0x10, 0xc0294ea000, 0xd, 0xc01880d570, 0x0)
	/tmp/go/src/github.com/dgraph-io/dgraph/worker/draft.go:1019 +0x9e fp=0xc04583fc08 sp=0xc04583fb80 pc=0x136c5de
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).produceKVs.func1(0xc00205aee0, 0x1d, 0x20, 0xc00205af00, 0x1b, 0x20, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:191 +0x3e4 fp=0xc04583fe28 sp=0xc04583fc08 pc=0x11d9de4
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).produceKVs(0xc0001c58f0, 0x19465a0, 0xc0000b4010, 0x0, 0x0)
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:234 +0x2b1 fp=0xc04583ff70 sp=0xc04583fe28 pc=0x11c2df1
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).Orchestrate.func1(0xc02072daf0, 0xc0001c58f0, 0x19465a0, 0xc0000b4010, 0xc02387ab40)
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:337 +0x69 fp=0xc04583ffb8 sp=0xc04583ff70 pc=0x11daa59
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc04583ffc0 sp=0xc04583ffb8 pc=0xa010d1
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).Orchestrate
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:334 +0x175
goroutine 1 [semacquire, 60 minutes]:
sync.runtime_Semacquire(0xc000141428)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc000141420)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.setupServer()
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:419 +0x838
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.run()
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:565 +0xd4c
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.init.2.func1(0xc0003f4d80, 0xc0000c0aa0, 0x0, 0x5)
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:87 +0x52
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute(0xc0003f4d80, 0xc0000c0a50, 0x5, 0x5, 0xc0003f4d80, 0xc0000c0a50)
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702 +0x289
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x22121a0, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783 +0x2ca
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736
github.com/dgraph-io/dgraph/dgraph/cmd.Execute()
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:68 +0x85
main.main()
/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/main.go:33 +0x99
goroutine 19 [chan receive]:
github.com/dgraph-io/dgraph/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x22b9b20)
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/dgraph-io/dgraph/vendor/github.com/golang/glog.init.0
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/golang/glog/glog.go:410 +0x272
goroutine 51 [select]:
github.com/dgraph-io/dgraph/vendor/go.opencensus.io/stats/view.(*worker).start(0xc0002bc0a0)
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by github.com/dgraph-io/dgraph/vendor/go.opencensus.io/stats/view.init.0
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57
goroutine 52 [syscall, 60 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
```

**Comment by mangalaman93** [comment]
This PR https://github.com/dgraph-io/dgraph/pull/4066 fixes this issue. Could you try running on latest master once?

**Comment by mangalaman93** [comment]
closing this for now.

**Comment by igormiletic** [comment]
I can not try it on master. My devops can deploy only official versions. Do you have idea when this can be released?

**Comment by mangalaman93** [comment]
ah, we should release a new version in some time. We are waiting for some bug fixes to go in. We do not have a release date yet. Let me figure this out. Thanks for getting back to us.
