### ISSUE TITLE
panic: interface conversion

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#415]
```
panic: interface conversion: interface is *graph.Value, not []uint8

goroutine 77294 [running]:
panic(0x9b4980, 0xc453063140)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/dgraph-io/dgraph/types.Convert(0xc400000006, 0xa2c320, 0xc42a032980, 0xc512fa7870, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/types/conversion.go:41 +0x9b
main.validateTypes(0xc42a028000, 0x3e8, 0x400, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:326 +0x15d
main.runMutations(0x7f80d3320468, 0xc4ae758b40, 0xc51b35fb00, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:251 +0x44
main.(*grpcServer).Run(0xf61f58, 0x7f80d3320468, 0xc4ae758b40, 0xc4530694c0, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:547 +0x300
github.com/dgraph-io/dgraph/query/graph._Dgraph_Run_Handler(0x9a3920, 0xf61f58, 0x7f80d3320468, 0xc51b35f830, 0xc4cc150f00, 0x0, 0x0, 0x0, 0x9, 0x10)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/query/graph/graphresponse.pb.go:621 +0x27d
google.golang.org/grpc.(*Server).processUnaryRPC(0xc420336000, 0xf224c0, 0xc420066270, 0xc50c9da900, 0xc42015ab10, 0xf0a4d0, 0xc51b35fa10, 0x0, 0x0)
	/home/mrjn/go/src/google.golang.org/grpc/server.go:709 +0xbd8
google.golang.org/grpc.(*Server).handleStream(0xc420336000, 0xf224c0, 0xc420066270, 0xc50c9da900, 0xc51b35fa10)
	/home/mrjn/go/src/google.golang.org/grpc/server.go:893 +0x6a4
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420324350, 0xc420336000, 0xf224c0, 0xc420066270, 0xc50c9da900)
	/home/mrjn/go/src/google.golang.org/grpc/server.go:469 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/mrjn/go/src/google.golang.org/grpc/server.go:470 +0xa3
```

I got this while loading up the 21M RDFs using the new 21M schema I've created in benchmarks.

**Comment by pawanrawal** [comment]
Fixed and merged.
