### ISSUE TITLE
Panic when parsing query

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#417]
```
$ curl localhost:8080/query -XPOST -d '{me(anyof("type.object.name.en", "tom") {type.object.name.en})}'

2016/12/23 13:30:27 server.go:2317: http: panic serving [::1]:48998: runtime error: invalid memory address or nil pointer dereference
goroutine 128176 [running]:
net/http.(*conn).serve.func1(0xc42d704000)
	/usr/lib/go/src/net/http/server.go:1491 +0x12a
panic(0x9b1000, 0xc4200120f0)
	/usr/lib/go/src/runtime/panic.go:458 +0x243
github.com/dgraph-io/dgraph/gql.getRoot(0xc53b824140, 0xc44c0f68f8, 0x45f020, 0xc44c0f68a0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/gql/parser.go:843 +0x637
github.com/dgraph-io/dgraph/gql.getQuery(0xc53b824140, 0xc44c0f68a0, 0xc4201718f0, 0xc420171901)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/gql/parser.go:398 +0x2f
github.com/dgraph-io/dgraph/gql.Parse(0xc480dcee00, 0x3f, 0xa58763, 0x12, 0xc53b4cdd40, 0x1)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/gql/parser.go:332 +0x5de
main.queryHandler(0xf1ff60, 0xc4eb728000, 0xc4591f8000)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:398 +0x41f
net/http.HandlerFunc.ServeHTTP(0xaa0528, 0xf1ff60, 0xc4eb728000, 0xc4591f8000)
	/usr/lib/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xf44f60, 0xf1ff60, 0xc4eb728000, 0xc4591f8000)
	/usr/lib/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420118480, 0xf1ff60, 0xc4eb728000, 0xc4591f8000)
	/usr/lib/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42d704000, 0xf20a60, 0xc480dceac0)
	/usr/lib/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:2293 +0x44d
```

**Comment by pawanrawal** [comment]
Fixed by handling error.
