### ISSUE TITLE
Panic when passing xid without underscores

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#420]
```
$ curl localhost:8080/query -XPOST -d '{me(xid: base.americancomedy.movie.runtime) {type.object.name.en}}'

2016/12/23 18:31:52 server.go:2317: http: panic serving [::1]:54366: runtime error: invalid memory address or nil pointer dereference
goroutine 127843 [running]:
net/http.(*conn).serve.func1(0xc517970000)
	/usr/lib/go/src/net/http/server.go:1491 +0x12a
panic(0x9b1000, 0xc4200120f0)
	/usr/lib/go/src/runtime/panic.go:458 +0x243
github.com/dgraph-io/dgraph/gql.getRoot(0xc441630230, 0xc45e2a8538, 0x45f020, 0xc45e2a84e0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/gql/parser.go:843 +0x637
github.com/dgraph-io/dgraph/gql.getQuery(0xc441630230, 0xc45e2a84e0, 0xc4203238f0, 0xc420323901)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/gql/parser.go:398 +0x2f
github.com/dgraph-io/dgraph/gql.Parse(0xc4416301e0, 0x42, 0xa58763, 0x12, 0xc47fc28210, 0x1)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/gql/parser.go:332 +0x5de
main.queryHandler(0xf1ff60, 0xc4c69b00d0, 0xc52dcb0690)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:398 +0x41f
net/http.HandlerFunc.ServeHTTP(0xaa0528, 0xf1ff60, 0xc4c69b00d0, 0xc52dcb0690)
	/usr/lib/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xf44f60, 0xf1ff60, 0xc4c69b00d0, 0xc52dcb0690)
	/usr/lib/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420310000, 0xf1ff60, 0xc4c69b00d0, 0xc52dcb0690)
	/usr/lib/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc517970000, 0xf20a60, 0xc45ce93e40)
	/usr/lib/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:2293 +0x44d

```

**Comment by pawanrawal** [comment]
Error was not handled, fixed it https://github.com/dgraph-io/dgraph/commit/a6a21ba85acb831d5fa6c766b38d4ddc3e568e4f
