### ISSUE TITLE
unsafe pointer conversion in TestRebuildIndex

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#4205]
### What version of Dgraph are you using?

tip

### Have you tried reproducing the issue with the latest release?

yes

### What is the hardware spec (RAM, OS)?

n/a/

### Steps to reproduce the issue (command/config used to run Dgraph).

I updated Go to the latest version on tip 

```
$ go version
go version devel +7d891d5e4d Tue Oct 22 21:23:03 2019 +0000 linux/amd64
```

Then I modified `./test.sh` to enable checkptr.

```patch
diff --git a/test.sh b/test.sh
index 1cfd7f98..7138c7bc 100755
--- a/test.sh
+++ b/test.sh
@@ -30,7 +30,7 @@ readonly DGRAPH_ROOT=${GOPATH:-$HOME}/src/github.com/dgraph-io/dgraph
 source $DGRAPH_ROOT/contrib/scripts/functions.sh
 
 PATH+=:$DGRAPH_ROOT/contrib/scripts/
-GO_TEST_OPTS=( )
+GO_TEST_OPTS=('-gcflags=all=-d=checkptr')
 TEST_FAILED=0
 TEST_SET="unit"
 BUILD_TAGS=
```

Then ran `make test`

### Expected behaviour and actual result.

I expected the tests to pass correctly, instead this test failed.

```go
INFO: Running test for github.com/dgraph-io/dgraph/posting
[Decoder]: Using assembly version of decoder
badger 2019/10/22 15:12:40 INFO: All 0 tables opened in 0s
E1022 15:12:40.852116   11342 langbase.go:56] While trying to parse lang "xx". Error: language: subtag "xx" is well-formed but unknown
badger 2019/10/22 15:12:40 INFO: Writes flushed. Stopping compactions now...
badger 2019/10/22 15:12:40 DEBUG: Flushing memtable
badger 2019/10/22 15:12:40 DEBUG: Storing value log head: {Fid:0 Len:29 Offset:445}
badger 2019/10/22 15:12:40 INFO: Got compaction priority: {level:0 score:1.74 dropPrefix:[0 0 5 110 97 109 101 50 2 0 1]}
badger 2019/10/22 15:12:40 INFO: Running for level: 0
badger 2019/10/22 15:12:40 INFO: Resuming writes
--- FAIL: TestRebuildIndex (0.01s)
panic: runtime error: unsafe pointer conversion [recovered]
	panic: runtime error: unsafe pointer conversion

goroutine 26 [running]:
testing.tRunner.func1(0xc0003f6200)
	/home/francesc/src/github.com/golang/go/src/testing/testing.go:881 +0x3a3
panic(0x137f540, 0xc00000e140)
	/home/francesc/src/github.com/golang/go/src/runtime/panic.go:679 +0x1b2
github.com/dgraph-io/badger/table.(*header).Decode(...)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/table/builder.go:52
github.com/dgraph-io/badger/table.(*blockIterator).setIdx(0xc00027e010, 0x3)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/table/iterator.go:82 +0x20a
github.com/dgraph-io/badger/table.(*blockIterator).next(...)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/table/iterator.go:145
github.com/dgraph-io/badger/table.(*Iterator).next(0xc00027e000)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/table/iterator.go:307 +0x250
github.com/dgraph-io/badger/table.(*Iterator).Next(0xc00027e000)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/table/iterator.go:367 +0x47
github.com/dgraph-io/badger/y.(*MergeIterator).Next(0xc0002b00f0)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/y/iterator.go:216 +0x52
github.com/dgraph-io/badger.(*levelsController).compactBuildTables(0xc0002a2c40, 0x0, 0x15a4240, 0xc0000b2000, 0xc0000d2ae0, 0xc0000d2b40, 0xc0000101a8, 0x1, 0x1, 0x1d21f90, ...)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/levels.go:507 +0x70d
github.com/dgraph-io/badger.(*levelsController).runCompactDef(0xc0002a2c40, 0x0, 0x15a4240, 0xc0000b2000, 0xc0000d2ae0, 0xc0000d2b40, 0xc0000101a8, 0x1, 0x1, 0x1d21f90, ...)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/levels.go:797 +0xc6
github.com/dgraph-io/badger.(*levelsController).doCompact(0xc0002a2c40, 0x0, 0x3ffbd70a3d70a3d7, 0xc0001560c0, 0xb, 0x20, 0x0, 0x0)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/levels.go:866 +0x4b7
github.com/dgraph-io/badger.(*levelsController).dropPrefix(0xc0002a2c40, 0xc0001560c0, 0xb, 0x20, 0xc0001560c0, 0xb)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/levels.go:287 +0x178
github.com/dgraph-io/badger.(*DB).DropPrefix(0xc000460000, 0xc0001560c0, 0xb, 0x20, 0x0, 0x0)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/db.go:1482 +0x543
github.com/dgraph-io/dgraph/posting.deleteTokensFor(0x14176da, 0x5, 0x1416991, 0x4, 0xc0001f5b90, 0x2)
	/home/francesc/src/github.com/dgraph-io/dgraph/posting/index.go:450 +0x175
github.com/dgraph-io/dgraph/posting.rebuildIndex(0x159cc00, 0xc00003a118, 0xc0003b1590, 0xc0000be01d, 0x5)
	/home/francesc/src/github.com/dgraph-io/dgraph/posting/index.go:724 +0x37d
github.com/dgraph-io/dgraph/posting.TestRebuildIndex(0xc0003f6200)
	/home/francesc/src/github.com/dgraph-io/dgraph/posting/index_test.go:272 +0x2e3
testing.tRunner(0xc0003f6200, 0x14642d8)
	/home/francesc/src/github.com/golang/go/src/testing/testing.go:916 +0xc9
created by testing.(*T).Run
	/home/francesc/src/github.com/golang/go/src/testing/testing.go:967 +0x351
FAIL	github.com/dgraph-io/dgraph/posting	0.080s
FAIL
```

**Comment by mangalaman93** [comment]
This is a badger issue and fixed by https://github.com/dgraph-io/badger/pull/1097

**Comment by mangalaman93** [comment]
Checked on master that this doesn't occur anymore.
