### ISSUE TITLE
unsafe pointer conversion in github.com/dgraph-io/dgraph/xidmap

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#4206]
### What version of Dgraph are you using?

tip

### Have you tried reproducing the issue with the latest release?

yes

### What is the hardware spec (RAM, OS)?

n/a/

### Steps to reproduce the issue (command/config used to run Dgraph).

I updated Go to the latest version on tip 

```
$ go version
go version devel +7d891d5e4d Tue Oct 22 21:23:03 2019 +0000 linux/amd64
```

Then I modified `./test.sh` to enable checkptr.

```patch
diff --git a/test.sh b/test.sh
index 1cfd7f98..7138c7bc 100755
--- a/test.sh
+++ b/test.sh
@@ -30,7 +30,7 @@ readonly DGRAPH_ROOT=${GOPATH:-$HOME}/src/github.com/dgraph-io/dgraph
 source $DGRAPH_ROOT/contrib/scripts/functions.sh
 
 PATH+=:$DGRAPH_ROOT/contrib/scripts/
-GO_TEST_OPTS=( )
+GO_TEST_OPTS=('-gcflags=all=-d=checkptr')
 TEST_FAILED=0
 TEST_SET="unit"
 BUILD_TAGS=
```

Then ran `make test`

### Expected behaviour and actual result.

I expected the tests to pass correctly, instead this test failed.

```go
INFO: Running test for github.com/dgraph-io/dgraph/xidmap
[Decoder]: Using assembly version of decoder
badger 2019/10/22 15:14:55 INFO: All 0 tables opened in 0s
badger 2019/10/22 15:14:55 DEBUG: Storing value log head: {Fid:0 Len:29 Offset:72}
panic: runtime error: unsafe pointer conversion

goroutine 99 [running]:
github.com/dgraph-io/badger/table.(*header).Decode(...)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/table/builder.go:52
github.com/dgraph-io/badger/table.(*blockIterator).setIdx(0xc0001b00d0, 0x2)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/table/iterator.go:82 +0x20a
github.com/dgraph-io/badger/table.(*blockIterator).seekToLast(...)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/table/iterator.go:141
github.com/dgraph-io/badger/table.(*Iterator).seekToLast(0xc0001b00c0)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/table/iterator.go:217 +0x18d
github.com/dgraph-io/badger/table.(*Iterator).Rewind(0xc0001b00c0)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/table/iterator.go:378 +0x34
github.com/dgraph-io/badger/table.(*Table).initBiggestAndSmallest(0xc0001b0000, 0x0, 0x0)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/table/table.go:243 +0xf5
github.com/dgraph-io/badger/table.OpenInMemoryTable(0xc0058d0000, 0x10f, 0x100000, 0x1, 0x0, 0x0, 0x0)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/table/table.go:228 +0xbc
github.com/dgraph-io/badger.(*DB).handleFlushTask(0xc000035880, 0xc00000e0a0, 0x1d00000000, 0x48, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/db.go:897 +0x3be
github.com/dgraph-io/badger.(*DB).flushMemtable(0xc000035880, 0xc00000e4c0, 0x0, 0x0)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/db.go:949 +0x16b
github.com/dgraph-io/badger.Open.func4(0xc00040a010)
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/db.go:304 +0x37
created by github.com/dgraph-io/badger.Open
	/home/francesc/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/db.go:303 +0x15f8
FAIL	github.com/dgraph-io/dgraph/xidmap	0.090s
```

**Comment by mangalaman93** [comment]
This is a badger issue and fixed by https://github.com/dgraph-io/badger/pull/1097

**Comment by mangalaman93** [comment]
Checked on master that this doesn't occur any more.
