### ISSUE TITLE
Error when processing data "1million.rdf.gz" in dgraph tour (panic: interface conversion: interface {} is *time.Time, not time.Time)

### ISSUE THREAD

**Issue by iuryfukuda** [dgraph-io/dgraph#4780]
### What version of Dgraph are you using?
[v1.2.1 in docker](https://hub.docker.com/layers/dgraph/dgraph/v1.2.1/images/sha256-7338825cf04c148374b9fba05ac55e2427d95c53a4610431b422b719416e3a3e?context=explore)

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
RAM:
```
$ sudo dmidecode --type 17
Memory Device
        Array Handle: 0x0024
        Error Information Handle: No Error
        Total Width: 64 bits
        Data Width: 64 bits
        Size: 4096 MB
        Form Factor: SODIMM
        Set: None
        Locator: ChannelA-DIMM0
        Bank Locator: BANK 0
        Type: DDR4
        Type Detail: Synchronous Unbuffered (Unregistered)
        Speed: 2133 MT/s
        Manufacturer: Samsung
        Serial Number: 00000000
        Asset Tag: 9876543210
        Part Number: M471A5244CB0-CRC
        Rank: 1
        Configured Memory Speed: 2133 MT/s
        Minimum Voltage: 1.5 V
        Maximum Voltage: 1.5 V
        Configured Voltage: 1.2 V
```
OS:
[Void Linux](https://voidlinux.org/)  5.4.17_1
```
$ uname -srvmo
Linux 5.4.17_1 #1 SMP PREEMPT Sat Feb 1 12:57:58 UTC 2020 x86_64 GNU/Linux
```
### Steps to reproduce the issue (command/config used to run Dgraph).
Run dgraph with this script:
```sh
#!/bin/sh

# Make sure dgraph folder is created
mkdir -p ~/dgraph

# trap stopDgraph function to run when ctrl+c is pressed
trap stopDgraph INT
stopDgraph() {
        docker stop $pid 1> /dev/null
        exit
}

# Run dgraph zero
pid=$(docker run -d --rm -it \
       -p 5080:5080 -p 6080:6080 -p 8080:8080 -p 9080:9080 -p 8000:8000 \
       -v ~/dgraph:/dgraph --name dgraph dgraph/dgraph dgraph zero)

# Run dgraph alpha
docker exec -d -it dgraph dgraph alpha --lru_mb 4096 --zero localhost:5080

# Run ratel (Dgraph UI)
docker exec -d -it dgraph dgraph-ratel

echo Dgraph Alpha: :8080
echo Dgraph Ratel: :8000

while true; do
      sleep 100
done
```

make sure all data is clean with this command (optional, after the first command failed, i start use it):
```
$ curl -X POST --data '{"drop_all": true}' http://localhost:8080/alter
```

Run define directives in https://tour.dgraph.io/moredata/1/#
```
# Define Directives and index

director.film: [uid] @reverse .
genre: [uid] @reverse .
initial_release_date: dateTime @index(year) .
name: string @index(exact, term) @lang .
```

get 1million.rdf.gz data and import it with commands described in https://tour.dgraph.io/moredata/1/#
```
cd ~/dgraph
wget "https://github.com/dgraph-io/tutorial/blob/master/resources/1million.rdf.gz?raw=true" -O 1million.rdf.gz -q
docker exec -it dgraph dgraph live -f 1million.rdf.gz --alpha localhost:9080 --zero localhost:5080 -c 1
```
### Expected behaviour and actual result.
expected: import all data
got:
```
$ docker exec -it dgraph dgraph live -f 1million.rdf.gz --alpha localhost:9080 --zero localhost:5080 -c 1
[Decoder]: Using assembly version of decoder
I0214 19:55:38.234719     477 init.go:98]

Dgraph version   : v1.2.1
Dgraph SHA-256   : 3f18ff84570b2944f4d75f6f508d55d902715c7ca2310799cc2991064eb046f8
Commit SHA-1     : ddcda9296
Commit timestamp : 2020-02-06 15:31:05 -0800
Branch           : HEAD
Go version       : go1.13.5

For Dgraph official documentation, visit https://docs.dgraph.io.
For discussions about Dgraph     , visit https://discuss.dgraph.io.
To say hi to the community       , visit https://dgraph.slack.com.

Licensed variously under the Apache Public License 2.0 and Dgraph Community License.
Copyright 2015-2018 Dgraph Labs, Inc.



Running transaction with dgraph endpoint: localhost:9080
Found 1 data file(s) to process
Processing data file "1million.rdf.gz"
panic: interface conversion: interface {} is *time.Time, not time.Time

goroutine 158 [running]:
github.com/dgraph-io/dgraph/tok.YearTokenizer.Tokens(0x18732a0, 0xc000ea6b60, 0x10, 0xc002a3e050, 0x14, 0xc00298a123, 0xc000304a80)
        /tmp/go/src/github.com/dgraph-io/dgraph/tok/tok.go:214 +0x185
github.com/dgraph-io/dgraph/tok.BuildTokens(0x18732a0, 0xc000ea6b60, 0x1a864e0, 0x249ab50, 0x1a864e0, 0x249ab50, 0x0, 0x1, 0xc002a3e040)
        /tmp/go/src/github.com/dgraph-io/dgraph/tok/tok.go:104 +0x63
github.com/dgraph-io/dgraph/dgraph/cmd/live.(*loader).conflictKeysForNQuad(0xc00039e0e0, 0xc0031de7e0, 0x10, 0x2, 0x2, 0x0, 0x0)
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/live/batch.go:309 +0x49e
github.com/dgraph-io/dgraph/dgraph/cmd/live.(*loader).conflictKeysForReq(0xc00039e0e0, 0xc00288bf88, 0xc000eda001, 0x57e, 0x800)
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/live/batch.go:330 +0xe9
github.com/dgraph-io/dgraph/dgraph/cmd/live.(*loader).makeRequests(0xc00039e0e0)
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/live/batch.go:392 +0x1db
created by github.com/dgraph-io/dgraph/dgraph/cmd/live.setup
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/live/run.go:359 +0x2f0
```

**Comment by MichelDiz** [comment]
Thank you for the very detailed issue. But it is a duplicated of https://github.com/dgraph-io/dgraph/issues/4468

Sorry for the inconvenience, and also there is a workaround in the issue.

Cheers.
