### ISSUE TITLE
ReadTs should not be retrieved for managed DB

### ISSUE THREAD

**Issue by calummoore** [dgraph-io/dgraph#5022]
### What version of Dgraph are you using?
standalone:v20.03.0-beta.20200320

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
MacOS - 4GB Ram - Docker

### Steps to reproduce the issue (command/config used to run Dgraph).
Docker Compose:
```
  dgraph:
    image: dgraph/standalone:v20.03.0-beta.20200320
    ports:
      - "9080:9080"
      - "8080:8080"
      - "8000:8000"
    volumes:
      - "dgraph-data:/dgraph"

```

### Expected behaviour and actual result.

I'm getting this error - looks like as a result of performing an index.

```
dgraph_1  | I0324 20:54:20.064957      33 index.go:896] Rebuilding index for attr custom.custom.insights_data_0_cpm.string.date.day and tokenizers [exact]
dgraph_1  | panic: ReadTs should not be retrieved for managed DB
dgraph_1  |
dgraph_1  | goroutine 10348 [running]:
dgraph_1  | github.com/dgraph-io/badger/v2.(*oracle).readTs(0xc000744140, 0xc029b8a180)
dgraph_1  | 	/tmp/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200316175624-91c31ebe8c22/txn.go:106 +0x15d
dgraph_1  | github.com/dgraph-io/badger/v2.(*DB).newTransaction(0xc00066b200, 0x0, 0x0)
dgraph_1  | 	/tmp/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200316175624-91c31ebe8c22/txn.go:668 +0xc7
dgraph_1  | github.com/dgraph-io/badger/v2.(*DB).NewTransaction(...)
dgraph_1  | 	/tmp/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200316175624-91c31ebe8c22/txn.go:636
dgraph_1  | github.com/dgraph-io/badger/v2.(*Stream).produceKVs(0xc029bae070, 0x1b55100, 0xc0062a2030, 0x0, 0x0)
dgraph_1  | 	/tmp/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200316175624-91c31ebe8c22/stream.go:155 +0x38f
dgraph_1  | github.com/dgraph-io/badger/v2.(*Stream).Orchestrate.func1(0xc029b861a0, 0xc029bae070, 0x1b55100, 0xc0062a2030, 0xc000340cc0)
dgraph_1  | 	/tmp/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200316175624-91c31ebe8c22/stream.go:337 +0x6b
dgraph_1  | created by github.com/dgraph-io/badger/v2.(*Stream).Orchestrate
dgraph_1  | 	/tmp/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200316175624-91c31ebe8c22/stream.go:334 +0x175
dgraph_1  | [Sentry] 2020/03/24 20:54:20 ModuleIntegration wasn't able to extract modules: module integration failed
dgraph_1  | [Sentry] 2020/03/24 20:54:20 Sending fatal event [a8af8c9c40d74d7988ecd6e7d39ae05d] to sentry.io project: 1805390
dgraph_1  | [Sentry] 2020/03/24 20:54:20 Buffer flushed successfully.
```

**Comment by mangalaman93** [comment]
@calummoore This doesn't seem like a full stack trace. Could you provide one? You could also attach full alpha logs if that is possible.
