### ISSUE TITLE
Crash when executing var query

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#510]
```
{
	var(allof(type.object.name.en, "cox")) {
		film.film.starring {
			CF as film.performance.film {
				CC as film.film.country
			}
		}
	}
	var(allof(type.object.name.en, "jennifer aniston")) {
		film.film.starring {
			JF as film.performance.film {
				JC as film.film.country
			}
		}
	}

	country(CC) @filter(id(JC)) {
		type.object.name.en
		~film.film.country @filter(id(CF) || id(JF)) {
			type.object.name.en
		}
	}
}
```

goroutine 367 [running]:
panic(0x9c0fe0, 0xc420012120)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/dgraph-io/dgraph/algo.IntersectWith(0x0, 0xc42087eb00)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/algo/uidlist.go:25 +0x29
github.com/dgraph-io/dgraph/query.ProcessGraph(0xf35b80, 0xc421ce08d0, 0xc4200a2dc0, 0xc4200a2b40, 0xc4201965a0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/query/query.go:658 +0x1ae2
created by github.com/dgraph-io/dgraph/query.ProcessGraph
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/query/query.go:706 +0x937

**Comment by manishrjain** [comment]
Tested again from master. Works now, no issues.
