### ISSUE TITLE
Dgraph crashes while trying to load data.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#550]
I was able to reproduce the issue twice where probably `l.water` is nil in `posting/list.go`. This was while trying to load the 21million RDF's with the schema.
```
goroutine 4185 [running]:
panic(0xdf77a0, 0xc4200141f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/dgraph-io/dgraph/posting.(*List).addMutation(0xc46442a9a0, 0x1492760, 0xc42325c570, 0xc467a14cc0, 0x14ee840, 0x5, 0x5beae0)
	/home/ubuntu/go/src/github.com/dgraph-io/dgraph/posting/list.go:335 +0x385
github.com/dgraph-io/dgraph/posting.(*List).AddMutationWithIndex(0xc46442a9a0, 0x1492760, 0xc42325c570, 0xc467a14cc0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/dgraph-io/dgraph/posting/index.go:172 +0x2f3
github.com/dgraph-io/dgraph/worker.runMutations(0x7f4a75979be0, 0xc42325c570, 0xc4678ec000, 0x693, 0x6a0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/mutation.go:50 +0x24c
github.com/dgraph-io/dgraph/worker.(*node).processMutation(0xc420092120, 0x2, 0x7d1, 0x0, 0xc45490a000, 0x9dd3, 0x9dd3, 0x0, 0x0, 0x0, ...)
	/home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/draft.go:372 +0x13b
github.com/dgraph-io/dgraph/worker.(*node).process(0xc420092120, 0x2, 0x7d1, 0x0, 0xc45490a000, 0x9dd3, 0x9dd3, 0x0, 0x0, 0x0, ...)
	/home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/draft.go:405 +0x387
created by github.com/dgraph-io/dgraph/worker.(*node).processApplyCh
	/home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/draft.go:444 +0x49b
```

**Comment by pawanrawal** [comment]
On latest master, this is still an issue. Latest logs
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5f5dc5]

goroutine 17023 [running]:
panic(0x9e0f60, 0xc420010110)
    /home/styles/.gvm/gos/go1.7.4/src/runtime/panic.go:500 +0x1a1
github.com/dgraph-io/dgraph/posting.(*List).addMutation(0xc4f712bb20, 0xf677e0, 0xc4f6ae7770, 0xc4f7092e80, 0x5, 0x5, 0x461970)
    /home/styles/golang/src/github.com/dgraph-io/dgraph/posting/list.go:390 +0x385
github.com/dgraph-io/dgraph/posting.(*List).AddMutationWithIndex(0xc4f712bb20, 0xf677e0, 0xc4f6ae7770, 0xc4f7092e80, 0x0, 0x0)
    /home/styles/golang/src/github.com/dgraph-io/dgraph/posting/index.go:151 +0x2f3
github.com/dgraph-io/dgraph/worker.runMutations(0x7fbe3f680148, 0xc4f6ae7770, 0xc4f7080000, 0x3e8, 0x400, 0x0, 0x0)
    /home/styles/golang/src/github.com/dgraph-io/dgraph/worker/mutation.go:50 +0x24c
github.com/dgraph-io/dgraph/worker.(*node).processMutation(0xc4205d4000, 0x2, 0x212f, 0x0, 0xc4f6b34000, 0xd2fd, 0xd2fd, 0x0, 0x0, 0x0, ...)
    /home/styles/golang/src/github.com/dgraph-io/dgraph/worker/draft.go:375 +0x13b
github.com/dgraph-io/dgraph/worker.(*node).process(0xc4205d4000, 0x2, 0x212f, 0x0, 0xc4f6b34000, 0xd2fd, 0xd2fd, 0x0, 0x0, 0x0, ...)
    /home/styles/golang/src/github.com/dgraph-io/dgraph/worker/draft.go:408 +0x387
created by github.com/dgraph-io/dgraph/worker.(*node).processApplyCh
    /home/styles/golang/src/github.com/dgraph-io/dgraph/worker/draft.go:447 +0x49b 
```

**Comment by manishrjain** [comment]
Found the issue. Submitted a fix: https://github.com/dgraph-io/dgraph/commit/583576793f9a99f269a6b71a40fd640ed4250254. Can you please verify the fix?

**Comment by pawanrawal** [comment]
Verified twice, didn't crash. Looks like its fixed. Also did a new release v0.7.2-1 and pushed the latest binaries.
