### ISSUE TITLE
Test: Custom Cluster Tests Exit Prematurely

### ISSUE THREAD

**Issue by darkn3rd** [dgraph-io/dgraph#5933]
When running custom cluster tests with `test.sh` the tests terminate without cleanup and a exit code of success (`0`).  

I think this may be an issue in the shell script (`test.sh`), so have debug snippets below.

### What version of Dgraph are you using?

`latest`

### Have you tried reproducing the issue with the latest release?

yes

### What is the hardware spec (RAM, OS)?

Ubuntu Bionic Beaver

### Steps to reproduce the issue (command/config used to run Dgraph).

```
$ ./test.sh -C 2>&1 | tee /tmp/master.custom_cluster.$(date +%Y%m%d_%H%M).txt
```

#### Expected

If the tests fails, a report of failures and exit code of `1` or greater.
If the tests pass, the message `INFO: All tests passed!` and exit code of `0`.

#### Actual

This happens with high frequency (27.3%)

1. Test Failure occurs
1. Last test completes sucessfully. `github.com/dgraph-io/dgraph/graphql/e2e/normal`
1. `test.sh` terminates with exit code of 0
1. leftover containers are running 

### Additional Notes

When there are no tests failing, `test.sh` exits normally and removes running containers.  When there is a failure, `test.sh` consistently exits early and still reports success with exit code of 0.

#### Successful Run Example

```shell
+ popd
+ read -r LINE
+ DIR=graphql/e2e/normal
+ CFG=graphql/e2e/normal/docker-compose.yml
+ Info 'Running tests in directory graphql/e2e/normal'
+ echo -e '\e[1;36mINFO: Running tests in directory graphql/e2e/normal\e[0m'
[1;36mINFO: Running tests in directory graphql/e2e/normal[0m
+ restartCluster graphql/e2e/normal/docker-compose.yml
+ [[ -z graphql/e2e/normal/docker-compose.yml ]]
++ readlink -f graphql/e2e/normal/docker-compose.yml
+ compose_file=/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/e2e/normal/docker-compose.yml
++ dirname ./contrib/scripts/functions.sh
+ basedir=./contrib/scripts/../..
+ pushd ./contrib/scripts/../../dgraph
+ echo 'Rebuilding dgraph ...'
Rebuilding dgraph ...
+ docker_compose_gopath=/home/pawan0201/go
+ make install
Commit SHA256: 5e7f443a5fccf9445076e89c9e6ad0e8f7ddaffa
Old SHA256: 578eb8cc4d5ebadc12c99f6dbce63299a8cb6f3e082197fac586d9c0a4a855d9
New SHA256: 578eb8cc4d5ebadc12c99f6dbce63299a8cb6f3e082197fac586d9c0a4a855d9
+ [[ linux-gnu == \d\a\r\w\i\n* ]]
+ docker ps -a --filter label=cluster=test --format '{{.Names}}'
+ xargs -r docker rm -f
alpha3
alpha2
zero1
alpha1
+ GOPATH=/home/pawan0201/go
+ docker-compose -p dgraph -f /home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/e2e/normal/docker-compose.yml up --force-recreate --remove-orphans -d
Creating alphaAdmin ...
Creating zeroAdmin  ...
Creating alpha1     ...
Creating zero1      ...
[4A[2K
Creating alphaAdmin ... [32mdone[0m
[4B[3A[2K
Creating zeroAdmin  ... [32mdone[0m
[3B[2A[2K
Creating alpha1     ... [32mdone[0m
[2B[1A[2K
Creating zero1      ... [32mdone[0m
[1B+ popd
+ ./contrib/scripts/../../contrib/wait-for-it.sh -t 60 localhost:6180
wait-for-it.sh: waiting 60 seconds for localhost:6180
wait-for-it.sh: localhost:6180 is available after 0 seconds
+ ./contrib/scripts/../../contrib/wait-for-it.sh -t 60 localhost:9180
wait-for-it.sh: waiting 60 seconds for localhost:9180
wait-for-it.sh: localhost:9180 is available after 0 seconds
+ sleep 10
+ pushd graphql/e2e/normal
+ CURRENT_TEST=graphql/e2e/normal
+ Run
+ set -o pipefail
+ echo -en '...\r'
...
+ IsCi
+ [[ ! -z '' ]]
+ go test
+ GREP_COLORS='ne:mt=01;32'
+ egrep --line-buffered --color=always '^ok\ .*|$'
+ GREP_COLORS='ne:mt=00;38;5;226'
+ egrep --line-buffered --color=always '^\?\ .*|$'
+ GREP_COLORS='ne:mt=01;31'
+ egrep --line-buffered --color=always '.*FAIL.*|$'
[Decoder]: Using assembly version of decoder
{"addStudent":{"student":[{"xid":"HS1","name":"Stud1","taughtBy":[{"id":"0x92","xid":"HT0","name":"Teacher0","subject":"English","teaches":[{"xid":"HS1","taughtBy":[{"name":"Teacher0","xid":"HT0","subject":"English"}]},{"xid":"HS2","taughtBy":[{"name":"Teacher0","xid":"HT0","subject":"English"}]}]}]}]}}
E0710 15:19:30.784047   16531 panics.go:33] panic:
****
this test should trap this panic.
It's working as expected if this message is logged with a stack trace
****.
 trace: goroutine 3347 [running]:
runtime/debug.Stack(0xc00061db70, 0x18d8140, 0xc0000b1a20)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/dgraph-io/dgraph/graphql/api.PanicHandler(0xc00061df48)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/api/panics.go:33 +0x57
panic(0x18d8140, 0xc0000b1a20)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/dgraph-io/dgraph/x.Panic(...)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/x/error.go:81
github.com/dgraph-io/dgraph/graphql/e2e/common.(*panicClient).Execute(0x29d03e8, 0x1cca9a0, 0xc000226360, 0xc000258150, 0xc000228540, 0xc0004a81a0, 0x0)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/e2e/common/error.go:267 +0x59
github.com/dgraph-io/dgraph/graphql/resolve.(*queryResolver).rewriteAndExecute(0xc0002264e0, 0x1cca9a0, 0xc000226360, 0x1ce8160, 0xc0002264b0, 0xc0002136e8)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/query.go:122 +0x572
github.com/dgraph-io/dgraph/graphql/resolve.(*queryResolver).Resolve(0xc0002264e0, 0x1cca9a0, 0xc000226360, 0x1ce8160, 0xc0002264b0, 0x0)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/query.go:82 +0x35f
github.com/dgraph-io/dgraph/graphql/resolve.(*RequestResolver).Resolve.func2.1(0xc0005744f0, 0xc000010048, 0x1, 0x1, 0xc0006326a0, 0x1cca9a0, 0xc000226360, 0x1ce8160, 0xc0002264b0, 0x0)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/resolver.go:449 +0x1b5
created by github.com/dgraph-io/dgraph/graphql/resolve.(*RequestResolver).Resolve.func2
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/resolver.go:438 +0x1e0
E0710 15:19:30.786849   16531 panics.go:33] panic:
****
this test should trap this panic.
It's working as expected if this message is logged with a stack trace
****.
 trace: goroutine 3335 [running]:
runtime/debug.Stack(0xc0004a5090, 0x18d8140, 0xc0000b1de0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/dgraph-io/dgraph/graphql/api.PanicHandler(0xc0004a5bc0)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/api/panics.go:33 +0x57
panic(0x18d8140, 0xc0000b1de0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/dgraph-io/dgraph/x.Panic(...)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/x/error.go:81
github.com/dgraph-io/dgraph/graphql/e2e/common.(*panicClient).Execute(0x29d03e8, 0x1cca9a0, 0xc0004da3f0, 0xc00027d340, 0xc0003f0a40, 0xc000570118, 0x1)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/e2e/common/error.go:267 +0x59
github.com/dgraph-io/dgraph/graphql/resolve.(*dgraphResolver).rewriteAndExecute(0xc0004da540, 0x1cca9a0, 0xc0004da3f0, 0x1ce8760, 0xc0004da510, 0x0, 0xc0004a5600)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/mutation.go:259 +0x78f
github.com/dgraph-io/dgraph/graphql/resolve.(*dgraphResolver).Resolve(0xc0004da540, 0x1cca9a0, 0xc0004da3f0, 0x1ce8760, 0xc0004da510, 0x0, 0x1cca900)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/mutation.go:185 +0x383
github.com/dgraph-io/dgraph/graphql/resolve.(*RequestResolver).Resolve(0xc0006326a0, 0x1cca9a0, 0xc0004da3f0, 0xc0004da330, 0x0)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/resolver.go:497 +0x5c4
github.com/dgraph-io/dgraph/graphql/web.(*graphqlHandler).ServeHTTP(0xc0006326c0, 0x1cc4b20, 0xc00023a1c0, 0xc000498500)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/web/http.go:172 +0x21f
github.com/graph-gophers/graphql-transport-ws/graphqlws.NewHandlerFunc.func1(0x1cc4b20, 0xc00023a1c0, 0xc000498500)
	/home/pawan0201/go/pkg/mod/github.com/graph-gophers/graphql-transport-ws@v0.0.0-20190611222414-40c048432299/graphqlws/http.go:39 +0xd5
net/http.HandlerFunc.ServeHTTP(0xc000209980, 0x1cc4b20, 0xc00023a1c0, 0xc000498500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/dgraph-io/dgraph/graphql/web.commonHeaders.func1(0x1cc4b20, 0xc00023a1c0, 0xc000498500)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/web/http.go:263 +0x258
net/http.HandlerFunc.ServeHTTP(0xc0006326e0, 0x1cc4b20, 0xc00023a1c0, 0xc000498500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/dgraph-io/dgraph/graphql/web.recoveryHandler.func1(0x1cc4b20, 0xc00023a1c0, 0xc000498500)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/web/http.go:276 +0xef
net/http.HandlerFunc.ServeHTTP(0xc000632700, 0x1cc4b20, 0xc00023a1c0, 0xc000498500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc00023a0e0, 0x1cc4b20, 0xc00023a1c0, 0xc000498500)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0004ae8c0, 0x1cca8e0, 0xc0004e8040)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384
PASS
[01;32mok  	github.com/dgraph-io/dgraph/graphql/e2e/normal	12.343s[m
+ popd
+ read -r LINE
+ CURRENT_TEST=
+ return 0
+ [[ :cluster: == *:systest:* ]]
+ Info 'Stopping cluster'
+ echo -e '\e[1;36mINFO: Stopping cluster\e[0m'
[1;36mINFO: Stopping cluster[0m
+ stopCluster
+ docker ps --filter label=cluster=test --format '{{.Names}}'
+ xargs -r docker stop
+ sed 's/^/Stopped /'
Stopped zero1
Stopped alpha1
+ docker ps -a --filter label=cluster=test --format '{{.Names}}'
+ xargs -r docker rm
+ sed 's/^/Removed /'
Removed zero1
Removed alpha1
++ date +%s
+ END_TIME=1594394371
++ FmtTime 797
++ local secs=17 min=13 hrs=0
++ [[ 0 -gt 0 ]]
++ [[ 0 -gt 0 ]]
++ [[ 13 -gt 0 ]]
++ printf '%dm ' 13
++ printf %ds 17
+ Info 'Tests completed in' 13m 17s
+ echo -e '\e[1;36mINFO: Tests completed in 13m 17s\e[0m'
[1;36mINFO: Tests completed in 13m 17s[0m
+ [[ 0 -eq 0 ]]
+ Info '\e[1;32mAll tests passed!'
+ echo -e '\e[1;36mINFO: \e[1;32mAll tests passed!\e[0m'
[1;36mINFO: [1;32mAll tests passed![0m
+ exit 0
+ rm -rf /tmp/test.sh.tmp-93yRKd
```

#### Test Failure, Script Exits Early without Cleanup, Success Exit Code Example

```shell
+ popd
+ read -r LINE
+ DIR=graphql/e2e/normal
+ CFG=graphql/e2e/normal/docker-compose.yml
+ Info 'Running tests in directory graphql/e2e/normal'
+ echo -e '\e[1;36mINFO: Running tests in directory graphql/e2e/normal\e[0m'
[1;36mINFO: Running tests in directory graphql/e2e/normal[0m
+ restartCluster graphql/e2e/normal/docker-compose.yml
+ [[ -z graphql/e2e/normal/docker-compose.yml ]]
++ readlink -f graphql/e2e/normal/docker-compose.yml
+ compose_file=/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/e2e/normal/docker-compose.yml
++ dirname ./contrib/scripts/functions.sh
+ basedir=./contrib/scripts/../..
+ pushd ./contrib/scripts/../../dgraph
+ echo 'Rebuilding dgraph ...'
Rebuilding dgraph ...
+ docker_compose_gopath=/home/pawan0201/go
+ make install
Commit SHA256: 5e7f443a5fccf9445076e89c9e6ad0e8f7ddaffa
Old SHA256: 99379f39df1f462208c082016be8d991df5ccc62b940039647a4ecc33f3b368c
New SHA256: 99379f39df1f462208c082016be8d991df5ccc62b940039647a4ecc33f3b368c
+ [[ linux-gnu == \d\a\r\w\i\n* ]]
+ docker ps -a --filter label=cluster=test --format '{{.Names}}'
+ xargs -r docker rm -f
alpha3
alpha2
zero1
alpha1
+ GOPATH=/home/pawan0201/go
+ docker-compose -p dgraph -f /home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/e2e/normal/docker-compose.yml up --force-recreate --remove-orphans -d
Creating zeroAdmin ...
Creating zero1     ...
Creating alpha1    ...
Creating alphaAdmin ...
[4A[2K
Creating zeroAdmin  ... [32mdone[0m
[4B[2A[2K
Creating alpha1     ... [32mdone[0m
[2B[1A[2K
Creating alphaAdmin ... [32mdone[0m
[1B[3A[2K
Creating zero1      ... [32mdone[0m
[3B+ popd
+ ./contrib/scripts/../../contrib/wait-for-it.sh -t 60 localhost:6180
wait-for-it.sh: waiting 60 seconds for localhost:6180
wait-for-it.sh: localhost:6180 is available after 0 seconds
+ ./contrib/scripts/../../contrib/wait-for-it.sh -t 60 localhost:9180
wait-for-it.sh: waiting 60 seconds for localhost:9180
wait-for-it.sh: localhost:9180 is available after 0 seconds
+ sleep 10
+ pushd graphql/e2e/normal
+ CURRENT_TEST=graphql/e2e/normal
+ Run
+ set -o pipefail
+ echo -en '...\r'
...
+ IsCi
+ [[ ! -z '' ]]
+ go test
+ GREP_COLORS='ne:mt=01;32'
+ egrep --line-buffered --color=always '^ok\ .*|$'
+ GREP_COLORS='ne:mt=00;38;5;226'
+ egrep --line-buffered --color=always '^\?\ .*|$'
+ GREP_COLORS='ne:mt=01;31'
+ egrep --line-buffered --color=always '.*FAIL.*|$'
[Decoder]: Using assembly version of decoder
{"addStudent":{"student":[{"xid":"HS1","name":"Stud1","taughtBy":[{"id":"0x92","xid":"HT0","name":"Teacher0","subject":"English","teaches":[{"xid":"HS1","taughtBy":[{"name":"Teacher0","xid":"HT0","subject":"English"}]},{"xid":"HS2","taughtBy":[{"name":"Teacher0","xid":"HT0","subject":"English"}]}]}]}]}}
E0710 15:08:19.435538   28406 panics.go:33] panic:
****
this test should trap this panic.
It's working as expected if this message is logged with a stack trace
****.
 trace: goroutine 3316 [running]:
runtime/debug.Stack(0xc000197090, 0x18d81e0, 0xc0004822f0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/dgraph-io/dgraph/graphql/api.PanicHandler(0xc000197bc0)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/api/panics.go:33 +0x57
panic(0x18d81e0, 0xc0004822f0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/dgraph-io/dgraph/x.Panic(...)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/x/error.go:81
github.com/dgraph-io/dgraph/graphql/e2e/common.(*panicClient).Execute(0x29d03e8, 0x1ccaa40, 0xc00046a2d0, 0xc0004861c0, 0xc00046c680, 0xc0000101b0, 0x1)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/e2e/common/error.go:267 +0x59
github.com/dgraph-io/dgraph/graphql/resolve.(*dgraphResolver).rewriteAndExecute(0xc00046a420, 0x1ccaa40, 0xc00046a2d0, 0x1ce8800, 0xc00046a3f0, 0x0, 0xc000197600)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/mutation.go:259 +0x78f
github.com/dgraph-io/dgraph/graphql/resolve.(*dgraphResolver).Resolve(0xc00046a420, 0x1ccaa40, 0xc00046a2d0, 0x1ce8800, 0xc00046a3f0, 0x0, 0x1ccaa00)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/mutation.go:185 +0x383
github.com/dgraph-io/dgraph/graphql/resolve.(*RequestResolver).Resolve(0xc00059b640, 0x1ccaa40, 0xc00046a2d0, 0xc00046a210, 0x0)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/resolver.go:497 +0x5c4
github.com/dgraph-io/dgraph/graphql/web.(*graphqlHandler).ServeHTTP(0xc00059b660, 0x1cc4bc0, 0xc0004b60e0, 0xc0005f0000)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/web/http.go:172 +0x21f
github.com/graph-gophers/graphql-transport-ws/graphqlws.NewHandlerFunc.func1(0x1cc4bc0, 0xc0004b60e0, 0xc0005f0000)
	/home/pawan0201/go/pkg/mod/github.com/graph-gophers/graphql-transport-ws@v0.0.0-20190611222414-40c048432299/graphqlws/http.go:39 +0xd5
net/http.HandlerFunc.ServeHTTP(0xc0003d0690, 0x1cc4bc0, 0xc0004b60e0, 0xc0005f0000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/dgraph-io/dgraph/graphql/web.commonHeaders.func1(0x1cc4bc0, 0xc0004b60e0, 0xc0005f0000)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/web/http.go:263 +0x258
net/http.HandlerFunc.ServeHTTP(0xc00059b6a0, 0x1cc4bc0, 0xc0004b60e0, 0xc0005f0000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/dgraph-io/dgraph/graphql/web.recoveryHandler.func1(0x1cc4bc0, 0xc0004b60e0, 0xc0005f0000)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/web/http.go:276 +0xef
net/http.HandlerFunc.ServeHTTP(0xc00059b6c0, 0x1cc4bc0, 0xc0004b60e0, 0xc0005f0000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc0001200e0, 0x1cc4bc0, 0xc0004b60e0, 0xc0005f0000)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0001c20a0, 0x1cca980, 0xc000438000)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384
E0710 15:08:19.440068   28406 panics.go:33] panic:
****
this test should trap this panic.
It's working as expected if this message is logged with a stack trace
****.
 trace: goroutine 3319 [running]:
runtime/debug.Stack(0xc000583b70, 0x18d81e0, 0xc000586240)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/dgraph-io/dgraph/graphql/api.PanicHandler(0xc000583f48)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/api/panics.go:33 +0x57
panic(0x18d81e0, 0xc000586240)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/dgraph-io/dgraph/x.Panic(...)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/x/error.go:81
github.com/dgraph-io/dgraph/graphql/e2e/common.(*panicClient).Execute(0x29d03e8, 0x1ccaa40, 0xc0005a2180, 0xc0004dc150, 0xc000269a40, 0xc000270000, 0x0)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/e2e/common/error.go:267 +0x59
github.com/dgraph-io/dgraph/graphql/resolve.(*queryResolver).rewriteAndExecute(0xc0005a2300, 0x1ccaa40, 0xc0005a2180, 0x1ce8200, 0xc0005a22d0, 0xc00048c360)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/query.go:122 +0x572
github.com/dgraph-io/dgraph/graphql/resolve.(*queryResolver).Resolve(0xc0005a2300, 0x1ccaa40, 0xc0005a2180, 0x1ce8200, 0xc0005a22d0, 0x0)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/query.go:82 +0x35f
github.com/dgraph-io/dgraph/graphql/resolve.(*RequestResolver).Resolve.func2.1(0xc0005f6080, 0xc000010138, 0x1, 0x1, 0xc00059b640, 0x1ccaa40, 0xc0005a2180, 0x1ce8200, 0xc0005a22d0, 0x0)
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/resolver.go:449 +0x1b5
created by github.com/dgraph-io/dgraph/graphql/resolve.(*RequestResolver).Resolve.func2
	/home/pawan0201/go/src/github.com/dgraph-io/dgraph/graphql/resolve/resolver.go:438 +0x1e0
PASS
[01;32mok  	github.com/dgraph-io/dgraph/graphql/e2e/normal	13.901s[m
+ popd
+ read -r LINE
+ CURRENT_TEST=
+ return 1
+ TestFailed
+ TEST_FAILED=1
+ [[ -n '' ]]
+ rm -rf /tmp/test.sh.tmp-pYu58I
```

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8587). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
