### ISSUE TITLE
ListIterator bug

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#609]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8b22c8]

goroutine 154833 [running]:
github.com/dgraph-io/dgraph/algo.(*ListIterator).Seek(0xc4205b95a8, 0x90c0f9b2885d82de, 0x1)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/algo/uidlist.go:128 +0x48
github.com/dgraph-io/dgraph/posting.(*List).intersectingPostings.func1(0xc477329c70, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/posting/list.go:615 +0xb4
github.com/dgraph-io/dgraph/posting.(*List).iterate(0xc460dc4540, 0x0, 0xc4205b95f8)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/posting/list.go:469 +0x24b
github.com/dgraph-io/dgraph/posting.(*List).intersectingPostings(0xc460dc4540, 0x0, 0xc48cfa25a0, 0xc458628540, 0xc4205b9670)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/posting/list.go:622 +0x1ff
github.com/dgraph-io/dgraph/posting.(*List).Uids(0xc460dc4540, 0x0, 0xc48cfa25a0, 0xc458628540, 0xc48cfa2860)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/posting/list.go:583 +0xd3
github.com/dgraph-io/dgraph/worker.intersectBucket(0xc48cf9e780, 0xc47fcb2202, 0x14, 0xc48bac69b0, 0x5, 0xc460038140, 0x3, 0x3, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/worker/sort.go:203 +0x4bb
github.com/dgraph-io/dgraph/worker.processSort(0xc48cf9e780, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/worker/sort.go:145 +0x60f
github.com/dgraph-io/dgraph/worker.SortOverNetwork(0x7fba5c0742b0, 0xc48cde81e0, 0xc48cf9e780, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/worker/sort.go:24 +0x799
github.com/dgraph-io/dgraph/query.(*SubGraph).applyOrderAndPagination(0xc47fcc0c00, 0xffd1e0, 0xc48cde81e0, 0xc48cfa2680, 0xc48cfa2660)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/query/query.go:1138 +0x146
github.com/dgraph-io/dgraph/query.ProcessGraph(0xffd1e0, 0xc48cde81e0, 0xc47fcc0c00, 0xc47fcc0a80, 0xc48cde8480)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/query/query.go:1020 +0x820
created by github.com/dgraph-io/dgraph/query.ProcessGraph
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/query/query.go:1058 +0x3aa
```

**Comment by pawanrawal** [comment]
This has been fixed.
