### ISSUE TITLE
Server crash while doing query.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#642]
This is related to #586.

Starting Dgraph with the following schema
```
scalar (
    objectId : id @index
    type : string @index
    name : string @index
)
```

and doing the following query without any mutation crashes the server. 
```
{
  obj(func: eq("objectId", "d507e730cc4f4ce2847743d23eda02f2")) @filter(eq("type", "website")) {
    _uid_
  }
}
```

Error log 
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc64ec9]

runtime stack:
runtime.throw(0xeedf9a, 0x2a)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 39 [syscall, locked to thread]:
runtime.cgocall(0xac7c10, 0xc421ea7368, 0x0)
	/usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc421ea7338 sp=0xc421ea72f8
github.com/dgraph-io/dgraph/rdb._Cfunc_rdb_iter_value(0x7fac4a833000, 0xc420134d78, 0x0)
	github.com/dgraph-io/dgraph/rdb/_obj/_cgo_gotypes.go:518 +0x4e fp=0xc421ea7368 sp=0xc421ea7338
github.com/dgraph-io/dgraph/rdb.(*Iterator).Value(0xc4200a40c0, 0xc420173ef0)
	/home/ubuntu/go/src/github.com/dgraph-io/dgraph/rdb/iterator.go:63 +0xa7 fp=0xc421ea73c8 sp=0xc421ea7368
github.com/dgraph-io/dgraph/worker.getInequalityTokens(0xc421f9c191, 0x8, 0xc420140c40, 0x20, 0xc421f9c18d, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/tokens.go:27 +0x13b fp=0xc421ea74e8 sp=0xc421ea73c8
github.com/dgraph-io/dgraph/worker.processTask(0xc4201429c0, 0xc400000001, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/task.go:183 +0x25e8 fp=0xc421ea7a58 sp=0xc421ea74e8
github.com/dgraph-io/dgraph/worker.ProcessTaskOverNetwork(0x7fac51e50890, 0xc420142780, 0xc4201429c0, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/task.go:50 +0x20e fp=0xc421ea7b80 sp=0xc421ea7a58
github.com/dgraph-io/dgraph/query.ProcessGraph(0x14e9ea0, 0xc420142780, 0xc420150300, 0x0, 0xc420142960)
	/home/ubuntu/go/src/github.com/dgraph-io/dgraph/query/query.go:948 +0x13a6 fp=0xc421ea7f78 sp=0xc421ea7b80
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc421ea7f80 sp=0xc421ea7f78
created by github.com/dgraph-io/dgraph/query.ProcessQuery
	/home/ubuntu/go/src/github.com/dgraph-io/dgraph/query/query.go:774 +0x680
```

I could reproduce this on v0.7.3.

**Comment by ashwin95r** [comment]
Fixed.
