### ISSUE TITLE
Crash in worker directory when tests run with benchmarks

### ISSUE THREAD

**Issue by ashishnegi** [dgraph-io/dgraph#652]
Reported by @Motakjuq on slack :

If we add a benchmark in `worker_test.go` like

```
func BenchmarkA(b *testing.B) {
	time.Sleep(time.Second)
}
```

and run `go test -bench . -benchtime=2s -v`, tests crash with following stack trace.
You might have to change value of bench time to reproduce.

Stack trace :

```[root@localhost worker]# go test -bench . -benchtime 1s
Starting commit routine.
[   1] Writing batch of size: 8
Backing up at: /tmp/backup222112863/dgraph-3-2017-03-02-02-27.rdf.gz
Backing up at: /tmp/backup222112863/dgraph-8-2017-03-02-02-27.rdf.gz
Starting commit routine.
Starting commit routine.
[   1] Writing batch of size: 5
Starting commit routine.
[   1] Writing batch of size: 3
[   2] Writing batch of size: 3
2017/03/02 02:27:48 lists.go:228: Dirty map size: 8
[   2] Writing batch of size: 3
2017/03/02 02:27:49 lists.go:228: Dirty map size: 6
[   2] Writing batch of size: 1
2017/03/02 02:27:49 lists.go:136: Commit counters. done:     3 noop:     0
[   3] Writing batch of size: 2
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0x8bcecb]
runtime stack:
runtime.throw(0x9e8b4c, 0x2a)
        /root/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
        /root/go/src/runtime/sigpanic_unix.go:12 +0x2cc
goroutine 62 [syscall, locked to thread]:
runtime.cgocall(0x8bc1e0, 0xc420456bb8, 0xc400000000)
        /root/go/src/runtime/cgocall.go:131 +0x110 fp=0xc420456b88 sp=0xc420456b48
github.com/dgraph-io/dgraph/rdb._Cfunc_rdb_write(0x7fbd6c016260, 0x7fbd6c000ad0, 0x106d3b0, 0xc420478020)
        github.com/dgraph-io/dgraph/rdb/_obj/_cgo_gotypes.go:721 +0x45 fp=0xc420456bb8 sp=0xc420456b88
github.com/dgraph-io/dgraph/rdb.(*DB).Write(0xc42013ecc0, 0xc420478010, 0xc4200c4000, 0x0, 0x0)
        /mnt/go/src/github.com/dgraph-io/dgraph/rdb/db.go:136 +0x27e fp=0xc420456c60 sp=0xc420456bb8
github.com/dgraph-io/dgraph/store.(*Store).WriteBatch(0xc4201706c0, 0xc4200c4000, 0x10, 0x10)
        /mnt/go/src/github.com/dgraph-io/dgraph/store/store.go:129 +0x41 fp=0xc420456c98 sp=0xc420456c60
github.com/dgraph-io/dgraph/posting.batchSync()
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:485 +0x4f2 fp=0xc420456fb0 sp=0xc420456c98
runtime.goexit()
        /root/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420456fb8 sp=0xc420456fb0
created by github.com/dgraph-io/dgraph/posting.Init
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:336 +0x1a2
goroutine 1 [chan receive]:
testing.(*B).run1(0xc42009c140, 0xc42009c140)
        /root/go/src/testing/benchmark.go:210 +0xac
testing.(*B).Run(0xc42009c000, 0x9d8230, 0xe, 0xa19e58, 0x474200)
        /root/go/src/testing/benchmark.go:486 +0x1ee
testing.runBenchmarksInternal.func1(0xc42009c000)
        /root/go/src/testing/benchmark.go:399 +0x6d
testing.(*B).runN(0xc42009c000, 0x1)
        /root/go/src/testing/benchmark.go:139 +0xaa
testing.runBenchmarksInternal(0xa1a5f0, 0xe5afc0, 0x1, 0x1, 0xc420028001)
        /root/go/src/testing/benchmark.go:405 +0x4a7
testing.(*M).Run(0xc4202ffef8, 0xc42006e058)
        /root/go/src/testing/testing.go:746 +0x1ac
github.com/dgraph-io/dgraph/worker.TestMain(0xc4202ffef8)
        /mnt/go/src/github.com/dgraph-io/dgraph/worker/worker_test.go:612 +0x30
main.main()
        github.com/dgraph-io/dgraph/worker/_test/_testmain.go:66 +0xc6
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /root/go/src/runtime/asm_amd64.s:2086 +0x1
goroutine 5 [chan receive]:
github.com/dgraph-io/dgraph/uid.(*lockManager).clean(0xc42013ebc0)
        /mnt/go/src/github.com/dgraph-io/dgraph/uid/assigner.go:55 +0x88
created by github.com/dgraph-io/dgraph/uid.init.1
        /mnt/go/src/github.com/dgraph-io/dgraph/uid/assigner.go:74 +0xeb
goroutine 26 [sleep]:
time.Sleep(0xb2d05e00)
        /root/go/src/runtime/time.go:59 +0xe1
github.com/dgraph-io/dgraph/worker.BenchmarkSleep(0xc42009c140)
        /mnt/go/src/github.com/dgraph-io/dgraph/worker/backup_test.go:192 +0x2b
testing.(*B).runN(0xc42009c140, 0x1)
        /root/go/src/testing/benchmark.go:139 +0xaa
testing.(*B).run1.func1(0xc42009c140)
        /root/go/src/testing/benchmark.go:208 +0x5a
created by testing.(*B).run1
        /root/go/src/testing/benchmark.go:209 +0x7f
goroutine 7 [select]:
github.com/dgraph-io/dgraph/posting.periodicCommit()
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:221 +0x447
created by github.com/dgraph-io/dgraph/posting.Init
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:335 +0x18a
goroutine 8 [sleep]:
time.Sleep(0x987d1e)
        /root/go/src/runtime/time.go:59 +0xe1
github.com/dgraph-io/dgraph/posting.batchSync()
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:498 +0x2a8
created by github.com/dgraph-io/dgraph/posting.Init
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:336 +0x1a2
goroutine 9 [chan receive]:
github.com/dgraph-io/dgraph/x.(*WaterMark).process(0xc420016f80)
        /mnt/go/src/github.com/dgraph-io/dgraph/x/watermark.go:137 +0x1f9
created by github.com/dgraph-io/dgraph/x.(*WaterMark).Init
        /mnt/go/src/github.com/dgraph-io/dgraph/x/watermark.go:60 +0xc4
goroutine 12 [chan receive]:
github.com/dgraph-io/dgraph/posting.(*counters).periodicLog(0xc42013f7c0)
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:121 +0x6a
created by github.com/dgraph-io/dgraph/posting.newCounters
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:142 +0x7e
goroutine 61 [select]:
github.com/dgraph-io/dgraph/posting.periodicCommit()
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:221 +0x447
created by github.com/dgraph-io/dgraph/posting.Init
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:335 +0x18a
goroutine 63 [chan receive]:
github.com/dgraph-io/dgraph/x.(*WaterMark).process(0xc4202de300)
        /mnt/go/src/github.com/dgraph-io/dgraph/x/watermark.go:137 +0x1f9
created by github.com/dgraph-io/dgraph/x.(*WaterMark).Init
        /mnt/go/src/github.com/dgraph-io/dgraph/x/watermark.go:60 +0xc4
goroutine 86 [select]:
github.com/dgraph-io/dgraph/posting.periodicCommit()
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:221 +0x447
created by github.com/dgraph-io/dgraph/posting.Init
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:335 +0x18a
goroutine 65 [chan receive]:
github.com/dgraph-io/dgraph/posting.(*counters).periodicLog(0xc4202da180)
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:121 +0x6a
created by github.com/dgraph-io/dgraph/posting.newCounters
        /mnt/go/src/github.com/dgraph-io/dgraph/posting/lists.go:142 +0x7e
```

**Comment by ashishnegi** [comment]
PR #651 seems to fix this.
