### ISSUE TITLE
min aggregation query panics server.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#713]
Another variation of #708 
```
{
  directors(
	func: anyofterms(name, "spielberg nolan tarantino"))

	@filter(gt(count(director.film), 5)) {
		min(initial_release_date)
    director.film {
      name
    }
  }
}
```

Panics the server with error
```
2017/03/17 15:41:19 server.go:2753: http: panic serving 127.0.0.1:33350: interface conversion: interface {} is *time.Time, not time.Time
goroutine 226 [running]:
net/http.(*conn).serve.func1(0xc4201a4be0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xb7d540, 0xc420b26940)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/dgraph-io/dgraph/query.valToBytes(0xc400000005, 0xc25a40, 0xc420152be0, 0x5207af0c8, 0x409a3e, 0xc4207af0e0, 0xc4207af0f0, 0xc25a01)
	/home/pawan/work/src/github.com/dgraph-io/dgraph/query/outputnode.go:312 +0x6e2
github.com/dgraph-io/dgraph/query.(*fastJsonNode).AddValue(0xc4207c4d00, 0xc420152b40, 0x19, 0xc400000005, 0xc25a40, 0xc420152be0)
	/home/pawan/work/src/github.com/dgraph-io/dgraph/query/outputnode.go:236 +0x4a
github.com/dgraph-io/dgraph/query.(*SubGraph).preTraverse(0xc4207bb380, 0x3b0de646eaf32b75, 0x119b200, 0xc4207c4ca0, 0x119b200, 0xc4207c4ca0, 0x0, 0x0)
	/home/pawan/work/src/github.com/dgraph-io/dgraph/query/query.go:273 +0x54a
github.com/dgraph-io/dgraph/query.processNodeUids(0xc4207c4b00, 0xc4207bb380, 0xc420171290, 0x0)
	/home/pawan/work/src/github.com/dgraph-io/dgraph/query/outputnode.go:422 +0x1f9
github.com/dgraph-io/dgraph/query.(*SubGraph).ToFastJSON(0xc4207af838, 0xc4207afbc0, 0x1190980, 0xc4201f6a80, 0x0, 0xc42042c028, 0x0)
	/home/pawan/work/src/github.com/dgraph-io/dgraph/query/outputnode.go:455 +0x1b0
github.com/dgraph-io/dgraph/query.ToJson(0xc4207afbc0, 0xc4201468b8, 0x1, 0x1, 0x1190980, 0xc4201f6a80, 0x0, 0x1, 0x0)
	/home/pawan/work/src/github.com/dgraph-io/dgraph/query/outputnode.go:68 +0x24b
main.queryHandler(0x1197a40, 0xc4201f6a80, 0xc42000bb00)
	/home/pawan/work/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:464 +0x100d
net/http.HandlerFunc.ServeHTTP(0xc63f98, 0x1197a40, 0xc4201f6a80, 0xc42000bb00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x1201900, 0x1197a40, 0xc4201f6a80, 0xc42000bb00)
	/usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc42046e000, 0x1197a40, 0xc4201f6a80, 0xc42000bb00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4201a4be0, 0x1198480, 0xc420b28640)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by ashwin95r** [comment]
Fixed.
