### ISSUE TITLE
Crash on query with negative first on inverse edge

### ISSUE THREAD

**Issue by dpeek** [dgraph-io/dgraph#750]
```
panic: runtime error: integer divide by zero

goroutine 16093 [running]:
panic(0x49c64c0, 0xc420014140)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
github.com/dgraph-io/dgraph/query.(*SubGraph).applyPagination(0xc42ad2a780, 0x4e1e360, 0xc441856180, 0xc457b7dbe0, 0xc457b7dbc0)
	/Users/xa_xx/go/src/github.com/dgraph-io/dgraph/query/query.go:1133 +0x19e
github.com/dgraph-io/dgraph/query.ProcessGraph(0x4e1e360, 0xc441856180, 0xc42ad2a780, 0xc42ad2a300, 0xc441856420)
	/Users/xa_xx/go/src/github.com/dgraph-io/dgraph/query/query.go:1033 +0x8c1
created by github.com/dgraph-io/dgraph/query.ProcessGraph
	/Users/xa_xx/go/src/github.com/dgraph-io/dgraph/query/query.go:1079 +0x3dd
```

When running this query:

```
{
  me(func:eq(type, "Genre"))  {
    ~genres (first:-1) { name.en }
  }
}
```

Which is getting all genres, then getting the last movie in each genre.

Version 0.7.3

**Comment by pawanrawal** [comment]
Fixed with a test https://github.com/dgraph-io/dgraph/commit/bf8c3fd52bb110c2b5b9f60b2220c72922224a18 in the release branch.
