### ISSUE TITLE
Panic while trying to load schema file through dgraphloader

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#753]
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.processSchemaFile(0x7ffc1afe6f10, 0x4a, 0xc42019a930)
	/home/pawan/work/src/github.com/dgraph-io/dgraph/cmd/dgraphloader/main.go:92 +0x706
main.main()
	/home/pawan/work/src/github.com/dgraph-io/dgraph/cmd/dgraphloader/main.go:182 +0x60a
```
Schema files
```
director.film: uid @reverse
genre: uid @reverse
initial_release_date: date @index
rating: uid @reverse
country: uid @reverse
loc: geo @index
name: string @index

```
Fails on the last empty line.

We should skip `schema.Parse` if the line is empty. Fixing this.

**Comment by pawanrawal** [comment]
Fixed https://github.com/dgraph-io/dgraph/commit/bf8c3fd52bb110c2b5b9f60b2220c72922224a18
