### ISSUE TITLE
Mutations cause panic via GRPC client

### ISSUE THREAD

**Issue by dan-compton** [dgraph-io/dgraph#83]
Sending a mutation via GRPC client causes panic because mutations are not processed.  See: https://github.com/dgraph-io/dgraph/blob/master/server/main.go#L224

```
anic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x59e428]

goroutine 27 [running]:
panic(0x9453e0, 0xc82000e120)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/dgraph-io/dgraph/query.ToSubGraph(0x0, 0x160, 0x0, 0x0)
	/home/dan/work/src/github.com/dgraph-io/dgraph/query/query.go:393 +0x28
main.(*server).Query(0xef6970, 0x7f338ca05828, 0xc8201144e0, 0xc820116210, 0xd, 0x0, 0x0)
	/home/dan/work/src/github.com/dgraph-io/dgraph/server/main.go:230 +0x53b
github.com/dgraph-io/dgraph/query/graph._DGraph_Query_Handler(0x91eaa0, 0xef6970, 0x7f338ca05828, 0xc8201144e0, 0xc820110680, 0x0, 0x0, 0x0, 0x0)
	/home/dan/work/src/github.com/dgraph-io/dgraph/query/graph/graphresponse.pb.go:129 +0x132
github.com/dgraph-io/dgraph/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc820126c80, 0x7f338ca4a7c0, 0xc8200fc000, 0xc820132460, 0xc8201194c0, 0xeb8810, 0xc820114390, 0x0, 0x0)
	/home/dan/work/src/github.com/dgraph-io/dgraph/vendor/google.golang.org/grpc/server.go:497 +0xe13
github.com/dgraph-io/dgraph/vendor/google.golang.org/grpc.(*Server).handleStream(0xc820126c80, 0x7f338ca4a7c0, 0xc8200fc000, 0xc820132460, 0xc820114390)
	/home/dan/work/src/github.com/dgraph-io/dgraph/vendor/google.golang.org/grpc/server.go:646 +0x109d
github.com/dgraph-io/dgraph/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc82000e450, 0xc820126c80, 0x7f338ca4a7c0, 0xc8200fc000, 0xc820132460)
	/home/dan/work/src/github.com/dgraph-io/dgraph/vendor/google.golang.org/grpc/server.go:323 +0xa0
created by github.com/dgraph-io/dgraph/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/dan/work/src/github.com/dgraph-io/dgraph/vendor/google.golang.org/grpc/server.go:324 +0x9a
```

I [fixed](https://github.com/dan-compton/dgraph/commit/2199cbf6d6ef353364d77f2128922cf001c27981) this issue in my much diverged govendor->aws branch by adapting [these lines](https://github.com/dgraph-io/dgraph/blob/master/server/main.go#L156-L168) from the http endpoint.  However, I'm not sure if this was left out for a reason/implications

**Comment by manishrjain** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;MFLrHLjr&#x2F;97-support-mutation-in-the-go-client"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Support mutation in the go client</a>

**Comment by manishrjain** [comment]
I think more of an oversight than anything else. @pawanrawal created a task to fix this.

**Comment by pawanrawal** [comment]
@dan-compton This has been fixed via https://github.com/dgraph-io/dgraph/pull/89. Feel free to open it again if you face any problem.

**Comment by dan-compton** [comment]
LGTM and very much appreciated.
