### ISSUE TITLE
[BUG]: @generate causes server panic if only the update mutation for a type is set to true

### ISSUE THREAD

**Issue by Poolshark** [dgraph-io/dgraph#8641]
### What version of Dgraph are you using?

Dgraph Cloud `v21.03.0-92-g0c9f60156`

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

Tier: 2R
Storage: 32 GB
Dgraph Hosted: Yes
High Availability: No
SLA: 99.5%
Schema Mode: Flexible

This error can also be reproduced on a Shared Cluster (Free Tier) with a minimal schema.

#### 1. Add any type to the schema, eg
```graphql
type GeneateTest
  @generate(query: { query: true, get: false, aggregate: false }, mutation: {add: false, update: true, delete: false}) {
  id: ID!
  test: String
}
```

#### Note
If just a **single generate** for **mutations** is set, the server will respond with a `Panic` when running the single generated mutation.### 

#### Expected behaviour
We'd expect that, regarding to which mutations Dgraph auto-generates, we can run these mutations.

#### Actual result
Running the mutation
```graphql
mutation {
  updateGenerateTest(
    input: {
      filter: { id: "0x1" },
      set: {
        test: "testing"
      }
    }
  ) {
    numUids
  }
}
```
results in a Server Panic.

#### The following tests have been executed

- `mutation: { add: false, update: true, delete: false }`--> fails
- `mutation: { add: true, update: true, delete: false }` --> ok
- `mutation: { add: false, update: true, delete: true }` --> ok
- `mutation: { add: true, update: false, delete: false }` --> ok
- `mutation: { add: false, update: false, delete: true}` --> ok
- `@generate` for `query` seems not to be affected

#### Server Error

```
"Internal Server Error - a panic was trapped.  This indicates a bug in the GraphQL server.  A stack trace was logged.  Please let us know by filing an issue with the stack trace."
```

**Comment by mangalaman93** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference.
 query: mutation {
  updateGeneateTest(
    input: {
      filter: { id: "0x1" },
      set: {
        test: "testing"
      }
    }
  ) {
    numUids
  }
}
 trace: goroutine 1110 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/dgraph-io/dgraph/graphql/api.PanicHandler(0xc006ad1508, {0xc006760140, 0x94})
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/graphql/api/panics.go:34 +0x66
panic({0x1da4b20, 0x2d1bbc0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/dgraph-io/dgraph/graphql/schema.(*astType).Name(...)
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/graphql/schema/wrappers.go:2449
github.com/dgraph-io/dgraph/graphql/schema.(*astType).IDField(0xc008b00000)
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/graphql/schema/wrappers.go:2545 +0x18
github.com/dgraph-io/dgraph/graphql/resolve.existenceQueries({0x2289ce0, 0xc00066cba0}, {0x229c770, 0x0}, {0x0?, 0x0}, 0x0?, 0xc00066d860, 0xc0067d8438)
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/graphql/resolve/mutation_rewriter.go:1675 +0x9d
github.com/dgraph-io/dgraph/graphql/resolve.(*UpdateRewriter).RewriteQueries(0xc00066d590, {0x2289ce0, 0xc00066cba0}, {0x22a1590, 0xc00066d560})
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/graphql/resolve/mutation_rewriter.go:335 +0x2ba
github.com/dgraph-io/dgraph/graphql/resolve.(*dgraphResolver).rewriteAndExecute(0xc0005aaa20, {0x2289ce0?, 0xc00066cba0}, {0x22a1590, 0xc00066d560})
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/graphql/resolve/mutation.go:274 +0x40e
github.com/dgraph-io/dgraph/graphql/resolve.(*dgraphResolver).Resolve(0xc0070501e0?, {0x2289ce0, 0xc00066cba0}, {0x22a1590, 0xc00066d560})
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/graphql/resolve/mutation.go:201 +0x41a
github.com/dgraph-io/dgraph/graphql/resolve.(*RequestResolver).Resolve(0xc006a337c0, {0x2289ce0, 0xc00681fe00}, 0xc0077f3b80)
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/graphql/resolve/resolver.go:601 +0xc97
github.com/dgraph-io/dgraph/graphql/admin.(*graphqlHandler).ServeHTTP(0xc00047e500, {0x2288b60, 0xc0081c0380}, 0xc0062f3000)
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/graphql/admin/http.go:279 +0x35b
github.com/dgraph-io/graphql-transport-ws/graphqlws.NewHandlerFunc.func1({0x2288b60, 0xc0081c0380}, 0xc0062f3000)
	/home/aman/gocode/pkg/mod/github.com/dgraph-io/graphql-transport-ws@v0.0.0-20210511143556-2cef522f1f15/graphqlws/http.go:40 +0x1d8
net/http.HandlerFunc.ServeHTTP(0x1e8c140?, {0x2288b60?, 0xc0081c0380?}, 0xc?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/dgraph-io/dgraph/graphql/admin.commonHeaders.func1({0x2288b60, 0xc0081c0380}, 0xc007947170?)
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/graphql/admin/http.go:387 +0xfc
net/http.HandlerFunc.ServeHTTP(0x0?, {0x2288b60?, 0xc0081c0380?}, 0x10?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/dgraph-io/dgraph/graphql/admin.recoveryHandler.func1({0x2288b60?, 0xc0081c0380?}, 0x0?)
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/graphql/admin/http.go:400 +0xab
net/http.HandlerFunc.ServeHTTP(0xc00040f260?, {0x2288b60?, 0xc0081c0380?}, 0x8?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.setupServer.func1({0x2288b60, 0xc0081c0380}, 0xc0062f3000)
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:547 +0x18c
net/http.HandlerFunc.ServeHTTP(0xc0079470b1?, {0x2288b60?, 0xc0081c0380?}, 0x8?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0xb9afb4?, {0x2288b60, 0xc0081c0380}, 0xc0062f3000)
	/usr/local/go/src/net/http/server.go:2500 +0x149
github.com/dgraph-io/dgraph/ee/audit.AuditRequestHttp.func1({0x2288b60?, 0xc0081c0380?}, 0xffffffffffffffff?)
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/ee/audit/interceptor_ee.go:94 +0xdd
net/http.HandlerFunc.ServeHTTP(0xc0081c0380?, {0x2288b60?, 0xc0081c0380?}, 0x1f7e700?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x2288b60, 0xc0081c0380}, 0xc0062f3000)
	/usr/local/go/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0x2283010?}, {0x2288b60, 0xc0081c0380}, 0xc0062f3000)
	/usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc006a6c5a0, {0x2289ce0, 0xc00023c1e0})
	/usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x5ed
```

**Comment by mangalaman93** [comment]
Thanks for filing the bug, we will look into it. I am able to reproduce it on `main` branch too.
