### ISSUE TITLE
[BUG]:  Alpha can't reach zero and panics

### ISSUE THREAD

**Issue by droslean** [dgraph-io/dgraph#9107]
### What version of Dgraph are you using?

v24.0.0

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

Kubernetes

### What steps will reproduce the bug?

Use the v24.0.0 version?

### Additional information

```console
E0701 14:00:12.248700      21 pool.go:314] CONN: Unable to connect with dgraph-alpha-0.dgraph-alpha.dgraph-prod.svc.cluster.local:7080 : rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 10.244.5.82:7080: connect: connection refused"
I0701 14:00:12.615829      21 groups.go:954] Leader idx=0x3 of group=1 is connecting to Zero for txn updates
I0701 14:00:12.615902      21 groups.go:966] Got Zero leader: dgraph-zero-0.dgraph-zero.dgraph-prod.svc.cluster.local:5080
W0701 14:00:12.660051      21 server.go:1219] error in sending grpc headers: rpc error: code = Canceled desc = context canceled
W0701 14:00:12.666958      21 server.go:1219] error in sending grpc headers: rpc error: code = Canceled desc = context canceled
W0701 14:00:12.667978      21 server.go:1219] error in sending grpc headers: rpc error: code = Canceled desc = context canceled
W0701 14:00:12.669245      21 server.go:1219] error in sending grpc headers: rpc error: code = Canceled desc = context canceled
W0701 14:00:12.669824      21 server.go:1219] error in sending grpc headers: rpc error: code = Canceled desc = context canceled
panic: runtime error: index out of range [1] with length 1

goroutine 1018 [running]:
github.com/dgraph-io/dgraph/x.ParseAttr(...)
	/home/runner/work/dgraph/dgraph/x/keys.go:120
github.com/dgraph-io/dgraph/query.expandSubgraph({0x25364c8, 0xc005a7e210}, 0xc005440f08)
	/home/runner/work/dgraph/dgraph/query/query.go:2032 +0x1115
github.com/dgraph-io/dgraph/query.ProcessGraph({0x25364c8, 0xc005a7e210}, 0xc005440f08, 0x0, 0xc00bf5f7a0)
	/home/runner/work/dgraph/dgraph/query/query.go:2332 +0x17c5
created by github.com/dgraph-io/dgraph/query.(*Request).ProcessQuery in goroutine 1010
	/home/runner/work/dgraph/dgraph/query/query.go:2890 +0xc7d
[Sentry] 2024/07/01 14:00:12 Sending fatal event [44a01ad5700b44b581b1299c006fd2d8] to o318308.ingest.sentry.io project: 1805390
[Sentry] 2024/07/01 14:00:12 Too many requests, backing off till: 2024-07-01 14:01:12.866703032 +0000 UTC m=+106.740155649
[Sentry] 2024/07/01 14:00:12 Buffer flushed successfully.

```

This is happening only on v24.0.0 and v23.1.1 (which I tried). On `v22.0.2` everything works fine.

**Comment by mangalaman93** [comment]
Sorry about the delay in response. Are you upgrading Dgraph binary here without exporting and importing from version v22.0.2?

**Comment by rarvikar** [comment]
Hi @droslean,
Could you please let us know the answer to Aman's question last with regards to a possible upgrade having caused this error ?

Otherwise, we're unable to reproduce the issue with either `v24.0.0` or `v23.1.1`, as the affected versions as per your note, as connections between Alphas and Zeroes seem to work seamlessly without any issues. 

Please feel free to re-open this issue if the issue still persists and if the steps to reproduce the same are available. 

Best regards.

**Comment by huynguyen-anduin** [comment]
Seem I got the same issue.

I upgraded Dgraph from v22.0.2 to v24.0.5 without importing/exporting from v22.0.2. 

But I did it 4 months ago, and this issue just happened recently. Also, other environments (same procedure) does not have issue.

Then I don't think upgrade led to this situation? In this case, is there any way to make system back to work?

```

I0325 07:03:19.219803      19 draft.go:208] Operation started with id: opRollup
I0325 07:03:19.219850      19 groups.go:158] Init and start Raft node: OK
I0325 07:03:19.219930      19 draft.go:1212] Found Raft progress: 183302
I0325 07:03:19.219980      19 groups.go:868] Got address of a Zero leader: dgraph-zero-0.dgraph-zero-headless.svc.cluster.local:5080
I0325 07:03:19.220156      19 groups.go:882] Starting a new membership stream receive from dgraph-zero-0.dgraph-zero-headless.strider2.svc.cluster.local:5080.
I0325 07:03:19.223281      19 groups.go:899] Received first state update from Zero: counter:83982 groups:<key:1 value:<members:<key:1 value:<id:1 group_id:1 addr:"dgraph-alpha-0.dgraph-alpha-headless.svc.cluster.local:7080" last_update:1742794297 > > tablets:<key:"\000\000\000\000\000\000\000\000AdvisorEntity.fund ...

I0325 07:03:19.250709      19 mutation.go:202] Max open files limit: 1048576
panic: runtime error: index out of range [1] with length 1

goroutine 282 [running]:
github.com/dgraph-io/dgraph/v24/x.ParseAttr(...)
	/home/runner/work/dgraph/dgraph/x/keys.go:120
github.com/dgraph-io/dgraph/v24/worker.checkSchema(0xc0007eabd0)
	/home/runner/work/dgraph/dgraph/worker/mutation.go:393 +0xa53
github.com/dgraph-io/dgraph/v24/worker.runSchemaMutation({0x270eb68, 0x386d1c0}, {0xc00b6abb08, 0xa4, 0x23eb93a?}, 0x0)
	/home/runner/work/dgraph/dgraph/worker/mutation.go:235 +0x49a
github.com/dgraph-io/dgraph/v24/worker.(*node).applyMutations(0x169fe3d4a005a?, {0x270eb68, 0x386d1c0}, 0xc000025300)
	/home/runner/work/dgraph/dgraph/worker/draft.go:420 +0x607
github.com/dgraph-io/dgraph/v24/worker.(*node).applyCommitted(0xc00027e300, 0xc000025300, 0x169fe3d4a005a)
	/home/runner/work/dgraph/dgraph/worker/draft.go:584 +0xe32
github.com/dgraph-io/dgraph/v24/worker.(*node).processApplyCh.func1({0xc0003e7e00, 0x1, 0x0?})
	/home/runner/work/dgraph/dgraph/worker/draft.go:784 +0x57f
github.com/dgraph-io/dgraph/v24/worker.(*node).processApplyCh(0xc00027e300)
	/home/runner/work/dgraph/dgraph/worker/draft.go:825 +0x212
created by github.com/dgraph-io/dgraph/v24/worker.(*node).InitAndStartNode in goroutine 180
	/home/runner/work/dgraph/dgraph/worker/draft.go:1884 +0x59e
[Sentry] 2025/03/25 07:03:19 Sending fatal event [a4d0e0a8171344979708a5fb731aa275] to o318308.ingest.sentry.io project: 1805390
[Sentry] 2025/03/25 07:03:19 Sending event failed with the following error: {"detail":"Sentry dropped data due to a quota or internal rate limit being reached. This will not affect your application. See https://docs.sentry.io/product/accounts/quotas/ for more information."}
[Sentry] 2025/03/25 07:03:19 Buffer flushed successfully.
```

**Comment by mangalaman93** [comment]
@huynguyen-anduin I am not sure why you are seeing this issue after 4 months. Is it possible that you have not used the old data since the upgrade at all, and only started to use this recently? This is uncharted territory, so I am not sure what is the right solution. I would recommend exporting the data and importing it into the the right dgraph version that you would like to use. Let us know how it goes.

**Comment by huynguyen-anduin** [comment]
@mangalaman93 I guess it's possible.

Cuz it's a non-critical environment. I ended up by deleting alpha node and its data.
