### ISSUE TITLE
Panic on groupby

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#939]
```
2017/05/15 14:58:15 server.go:2753: http: panic serving 127.0.0.1:49872: interface conversion: interface {} is nil, not string
goroutine 151 [running]:
net/http.(*conn).serve.func1(0xc4200986e0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xbebc80, 0xc420ad0200)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/dgraph-io/dgraph/query.valToBytes(0x0, 0x0, 0x0, 0xc420ae0ee8, 0x418718, 0x10, 0xc0e900, 0x1)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/query/outputnode.go:355 +0x1a9
github.com/dgraph-io/dgraph/query.(*fastJsonNode).AddValue(0xc4204d7dc0, 0xc4204d7d40, 0xa, 0x0, 0x0, 0x0)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/query/outputnode.go:281 +0x58
github.com/dgraph-io/dgraph/query.(*SubGraph).preTraverse(0xc420ad8000, 0x7e1, 0x1238300, 0xc4204d7d80, 0x1238300, 0xc4204d7d80, 0xc4202378f0, 0xc420ae1498)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/query/query.go:301 +0x21b1
github.com/dgraph-io/dgraph/query.processNodeUids(0xc4204d7d70, 0xc420ad8000, 0xc4202378f0, 0x0)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/query/outputnode.go:488 +0x241
github.com/dgraph-io/dgraph/query.(*SubGraph).ToFastJSON(0xc420ae1718, 0xc420ae1bc0, 0x122d5e0, 0xc420258c40, 0x0, 0xc42026a000, 0x0, 0x1)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/query/outputnode.go:517 +0x1b0
github.com/dgraph-io/dgraph/query.ToJson(0xc420ae1bc0, 0xc42000e388, 0x1, 0x1, 0x122d5e0, 0xc420258c40, 0x0, 0x0, 0x0, 0x0)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/query/outputnode.go:71 +0x25c
main.queryHandler(0x12349a0, 0xc420258c40, 0xc42000b600)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:603 +0x1003
net/http.HandlerFunc.ServeHTTP(0xcdbab0, 0x12349a0, 0xc420258c40, 0xc42000b600)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x12a4aa0, 0x12349a0, 0xc420258c40, 0xc42000b600)
	/usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4205280b0, 0x12349a0, 0xc420258c40, 0xc42000b600)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4200986e0, 0x1235460, 0xc420accd80)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

Mutation:
```
mutation{
  set {
    <china> <revenue> _:v1 .
    <2017> <revenue> _:v1 .
    _:v1 <value> "123123" .
    <2017> <name> "2017" .
    <china> <name> "china" .
  }
}
```
Query:
```
{
 year(id: <2017>) {
  revenue @groupby(name) {
   min(name)
  }
  }
}
```

**Comment by ashwin95r** [comment]
Fixed.
