### ISSUE TITLE
Groupby panics when doing aggregation on float

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#961]
This query panic the server.

```
{
  me(func: gt(count(name), 0)) @groupby(country) {
   max(score) 
  }
}
```

Panic log
```
2017/05/19 11:36:33 server.go:2753: http: panic serving 127.0.0.1:40498: interface conversion: interface {} is nil, not string
goroutine 5378 [running]:
net/http.(*conn).serve.func1(0xc42009edc0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xbed520, 0xc42962c200)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/dgraph-io/dgraph/query.valToBytes(0x0, 0x0, 0x0, 0xc42307a3c8, 0x1, 0x1, 0x0, 0x0)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/query/outputnode.go:379 +0x1a9
github.com/dgraph-io/dgraph/query.(*fastJsonNode).AddValue(0xc42a1a7a00, 0xc42a1a6a90, 0xa, 0x0, 0x0, 0x0)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/query/outputnode.go:309 +0x58
github.com/dgraph-io/dgraph/query.(*fastJsonNode).addGroupby(0xc42a1a7970, 0xc420579440, 0xc420b447d4, 0x2)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/query/outputnode.go:503 +0x33c
github.com/dgraph-io/dgraph/query.processNodeUids(0xc42a1a7970, 0xc420579440, 0xc421814930, 0x0)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/query/outputnode.go:531 +0x946
github.com/dgraph-io/dgraph/query.(*SubGraph).ToFastJSON(0xc424c8d6c8, 0xc424c8dbc0, 0x123a720, 0xc4231d3180, 0x0, 0xc42a250101, 0x0, 0x1)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/query/outputnode.go:572 +0x1ac
github.com/dgraph-io/dgraph/query.ToJson(0xc424c8dbc0, 0xc42a044108, 0x1, 0x1, 0x123a720, 0xc4231d3180, 0x0, 0x1, 0x0, 0x0)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/query/outputnode.go:71 +0x260
main.queryHandler(0x1241da0, 0xc4231d3180, 0xc420550300)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:611 +0x10f4
net/http.HandlerFunc.ServeHTTP(0xcdff30, 0x1241da0, 0xc4231d3180, 0xc420550300)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x12b2280, 0x1241da0, 0xc4231d3180, 0xc420550300)
	/usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc42058c000, 0x1241da0, 0xc4231d3180, 0xc420550300)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42009edc0, 0x1242860, 0xc42972c700)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by pawanrawal** [comment]
This also causes it.
```
{
  me(func: gt(count(name), 0)) @groupby(country) {
   max(email) 
  }
}
```

Email is of default type which should be string.

**Comment by ashwin95r** [comment]
Fixed.
