### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/dgraph#993]
version: 0.7.7

---

*Reproduce*

1. Load the following backup into dgraph
[dgraph-1-2017-05-29-15-00.rdf.gz](https://github.com/dgraph-io/dgraph/files/1035060/dgraph-1-2017-05-29-15-00.rdf.gz)
[dgraph-schema-1-2017-05-29-15-00.rdf.gz](https://github.com/dgraph-io/dgraph/files/1035061/dgraph-schema-1-2017-05-29-15-00.rdf.gz)

2. Run the following query

```
{
  questions(func: eq(Type, "Question"), orderdesc: Timestamp, first: 100) {
    _uid_

  	Title {
      Text
    }

    Owner {
      DisplayName
      Reputation
      _uid_
    }

    Tags {
      Text
    }

    Has.Answer(orderdesc: Timestamp, first: 1) {
      Owner {
        DisplayName
        Reputation
        _uid_
      }
      Timestamp
    }

    VoteCount: count(Vote)
    AnswerCount: count(Has.Answer)
    ViewCount
    Timestamp
  }

  topTags(func: gt(count(PostCount), 0), orderdesc: PostCount, first: 10) {
    PostCount
    TagName
    _uid_
  }
}
```

3. Dgraph replies with the following and crashes.

```
{"code":"ErrorInvalidRequest","message":"Got error: Undefined predicate: Type. while running: [eq Question]"}
```

Stacktrace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x46e3a18]

goroutine 179 [running]:
github.com/dgraph-io/dgraph/query.(*SubGraph).applyOrderAndPagination(0xc420973d40, 0x500b900, 0xc420279020, 0xc4204d6060, 0x0)
	/Users/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1903 +0x1b8
github.com/dgraph-io/dgraph/query.ProcessGraph(0x500b900, 0xc420279020, 0xc420973d40, 0x0, 0xc420279080)
	/Users/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1732 +0x1708
created by github.com/dgraph-io/dgraph/query.ProcessQuery
	/Users/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1234 +0x717
```

**Comment by pawanrawal** [comment]
Fixed and merged to release and master.
Reference 4e48993b0f4f8407477a39b1e135f9deaf0069e8
